// Kamus Pintasan Lentera — lengkap, dwibahasa (Inggris layar / Indonesia),
// bebas diakses semua peserta di level mana pun, dan bisa dicetak.
// k = tombol, en = istilah di layar, id = arti, ket = kapan dipakai.

export const HOTKEYS = [
  {
    cat: 'Penyelamat — hafalkan duluan',
    items: [
      { k: ['Ctrl', 'Z'], en: 'Undo', id: 'Batalkan', ket: 'Apa pun kekacauannya, tekan ini — bisa berkali-kali, mundur terus.' },
      { k: ['Ctrl', 'Y'], en: 'Redo', id: 'Maju lagi', ket: 'Kebalikan Undo — kalau kebanyakan mundur.' },
      { k: ['Ctrl', 'S'], en: 'Save', id: 'Simpan', ket: 'Refleks wajib: selesai sebagian, tekan.' },
      { k: ['Esc'], en: 'Escape', id: 'Batal / keluar', ket: 'Menutup menu atau kotak yang muncul tiba-tiba.' },
      { k: ['Ctrl', 'Shift', 'Esc'], en: 'Task Manager', id: 'Pengelola tugas', ket: 'Aplikasi macet total? Buka ini, pilih aplikasinya, End task.' },
      { k: ['Win', 'L'], en: 'Lock', id: 'Kunci layar', ket: 'Tinggalkan laptop sebentar dengan aman.' },
    ],
  },
  {
    cat: 'Windows — jendela & layar',
    items: [
      { k: ['Win'], en: 'Start', id: 'Menu mulai', ket: 'Lalu langsung ketik nama aplikasi yang dicari.' },
      { k: ['Alt', 'Tab'], en: 'Switch', id: 'Pindah jendela', ket: 'Tahan Alt, tekan Tab untuk memilih jendela.' },
      { k: ['Win', 'Panah Kiri'], en: 'Snap left', id: 'Tempel kiri', ket: 'Jurus belah layar — Lentera di kiri.' },
      { k: ['Win', 'Panah Kanan'], en: 'Snap right', id: 'Tempel kanan', ket: 'Aplikasi latihan di kanan.' },
      { k: ['Win', 'Panah Atas'], en: 'Maximize', id: 'Penuhi layar', ket: 'Jendela memenuhi satu layar.' },
      { k: ['Win', 'Panah Bawah'], en: 'Minimize', id: 'Sembunyikan', ket: 'Jendela turun ke taskbar.' },
      { k: ['Win', 'D'], en: 'Desktop', id: 'Tampilkan desktop', ket: 'Semua jendela minggir sekaligus.' },
      { k: ['Win', 'E'], en: 'Explorer', id: 'Buka File Explorer', ket: 'Lemari arsip filemu.' },
      { k: ['Win', 'I'], en: 'Settings', id: 'Pengaturan', ket: 'WiFi, layar, suara, dan lainnya.' },
      { k: ['Win', 'Shift', 'S'], en: 'Snip', id: 'Tangkap layar (pilih area)', ket: 'Hasilnya siap di-paste (Ctrl + V).' },
      { k: ['Win', 'V'], en: 'Clipboard history', id: 'Riwayat salinan', ket: 'Daftar semua yang pernah kamu salin.' },
      { k: ['Alt', 'F4'], en: 'Close app', id: 'Tutup aplikasi', ket: 'Menutup aplikasi yang sedang aktif.' },
    ],
  },
  {
    cat: 'Teks universal — berlaku hampir di mana saja',
    items: [
      { k: ['Ctrl', 'C'], en: 'Copy', id: 'Salin', ket: 'Yang terpilih masuk ke saku (clipboard).' },
      { k: ['Ctrl', 'X'], en: 'Cut', id: 'Potong', ket: 'Untuk dipindahkan, bukan digandakan.' },
      { k: ['Ctrl', 'V'], en: 'Paste', id: 'Tempel', ket: 'Keluarkan isi saku di posisi kursor.' },
      { k: ['Ctrl', 'A'], en: 'Select all', id: 'Pilih semua', ket: 'Seluruh isi dokumen/folder terpilih.' },
      { k: ['Ctrl', 'F'], en: 'Find', id: 'Cari', ket: 'Menemukan kata di dokumen atau halaman.' },
      { k: ['Home'], en: 'Home', id: 'Awal baris', ket: 'Kursor melompat ke awal baris.' },
      { k: ['End'], en: 'End', id: 'Akhir baris', ket: 'Kursor melompat ke akhir baris.' },
      { k: ['Ctrl', 'Home'], en: 'Top', id: 'Awal dokumen', ket: 'Langsung ke halaman paling atas.' },
      { k: ['Ctrl', 'End'], en: 'Bottom', id: 'Akhir dokumen', ket: 'Langsung ke bagian paling bawah.' },
      { k: ['Shift', 'Panah'], en: 'Select', id: 'Pilih per huruf/baris', ket: 'Tahan Shift sambil menekan panah.' },
      { k: ['Ctrl', 'Panah'], en: 'Jump word', id: 'Lompat per kata', ket: 'Kursor melompat kata demi kata.' },
      { k: ['Ctrl', 'Backspace'], en: 'Delete word', id: 'Hapus satu kata', ket: 'Lebih cepat dari menekan Backspace berkali-kali.' },
    ],
  },
  {
    cat: 'File Explorer — arsip & folder',
    items: [
      { k: ['Ctrl', 'Shift', 'N'], en: 'New folder', id: 'Folder baru', ket: 'Langsung ketik namanya, Enter.' },
      { k: ['F2'], en: 'Rename', id: 'Ganti nama', ket: 'Pilih file/folder, tekan F2, ketik nama baru.' },
      { k: ['Delete'], en: 'Delete', id: 'Hapus (ke Recycle Bin)', ket: 'Masih bisa dipulihkan dari tempat sampah.' },
      { k: ['Shift', 'Delete'], en: 'Delete permanently', id: 'Hapus permanen', ket: 'HATI-HATI: tidak lewat Recycle Bin.' },
      { k: ['Ctrl', 'klik'], en: 'Multi-select', id: 'Pilih beberapa', ket: 'Klik beberapa file sambil menahan Ctrl.' },
      { k: ['Shift', 'klik'], en: 'Range select', id: 'Pilih rentang', ket: 'Klik file pertama, Shift + klik file terakhir.' },
      { k: ['Alt', 'Panah Kiri'], en: 'Back', id: 'Kembali', ket: 'Mundur ke folder sebelumnya.' },
    ],
  },
  {
    cat: 'Word — dokumen',
    items: [
      { k: ['Ctrl', 'B'], en: 'Bold', id: 'Tebal', ket: 'Pilih teksnya dulu, lalu tekan.' },
      { k: ['Ctrl', 'I'], en: 'Italic', id: 'Miring', ket: 'Untuk istilah asing atau penekanan halus.' },
      { k: ['Ctrl', 'U'], en: 'Underline', id: 'Garis bawah', ket: 'Garis di bawah teks terpilih.' },
      { k: ['Ctrl', 'L'], en: 'Align left', id: 'Rata kiri', ket: 'Perataan bawaan untuk isi tulisan.' },
      { k: ['Ctrl', 'E'], en: 'Center', id: 'Rata tengah', ket: 'Untuk judul.' },
      { k: ['Ctrl', 'R'], en: 'Align right', id: 'Rata kanan', ket: 'Untuk tempat & tanggal surat.' },
      { k: ['Ctrl', 'J'], en: 'Justify', id: 'Rata kiri-kanan', ket: 'Isi surat resmi, rapi seperti koran.' },
      { k: ['Ctrl', '1'], en: 'Single spacing', id: 'Spasi 1', ket: 'Jarak baris rapat.' },
      { k: ['Ctrl', '5'], en: '1.5 spacing', id: 'Spasi 1.5', ket: 'Standar dokumen resmi Indonesia.' },
      { k: ['Ctrl', '2'], en: 'Double spacing', id: 'Spasi 2', ket: 'Jarak baris longgar.' },
      { k: ['F12'], en: 'Save As', id: 'Simpan sebagai', ket: 'Langsung buka jendela simpan-sebagai-file-baru.' },
      { k: ['Ctrl', 'P'], en: 'Print', id: 'Cetak', ket: 'Buka layar cetak beserta pratinjau.' },
      { k: ['Ctrl', 'N'], en: 'New', id: 'Dokumen baru', ket: 'Kertas kosong baru.' },
      { k: ['Ctrl', 'O'], en: 'Open', id: 'Buka', ket: 'Membuka dokumen yang sudah ada.' },
      { k: ['Ctrl', 'W'], en: 'Close', id: 'Tutup dokumen', ket: 'Dokumen tertutup, Word tetap terbuka.' },
      { k: ['Ctrl', 'H'], en: 'Replace', id: 'Cari & ganti', ket: 'Mengganti satu kata di seluruh dokumen sekaligus.' },
      { k: ['Ctrl', 'Enter'], en: 'Page break', id: 'Pindah halaman', ket: 'Lompat ke halaman baru tanpa menekan Enter banyak-banyak.' },
      { k: ['Shift', 'F3'], en: 'Change case', id: 'Ubah KAPITAL/kecil', ket: 'Pilih teks, tekan berulang: kecil → Kapital Awal → KAPITAL.' },
      { k: ['Tab'], en: 'Demote', id: 'Anak daftar', ket: 'Di dalam daftar: masuk satu tingkat.' },
      { k: ['Shift', 'Tab'], en: 'Promote', id: 'Naik tingkat daftar', ket: 'Keluar satu tingkat dari anak daftar.' },
    ],
  },
  {
    cat: 'Excel — tabel & angka (bekal modul berikutnya)',
    items: [
      { k: ['Enter'], en: 'Confirm', id: 'Isi & turun', ket: 'Mengunci isi sel lalu pindah ke bawah.' },
      { k: ['Tab'], en: 'Next cell', id: 'Isi & ke kanan', ket: 'Mengunci isi sel lalu pindah ke kanan.' },
      { k: ['F2'], en: 'Edit cell', id: 'Sunting sel', ket: 'Memperbaiki isi sel tanpa mengetik ulang semua.' },
      { k: ['Ctrl', 'Panah'], en: 'Jump edge', id: 'Lompat ke ujung data', ket: 'Langsung ke baris/kolom terakhir yang terisi.' },
      { k: ['Ctrl', 'Shift', 'Panah'], en: 'Select block', id: 'Pilih satu blok data', ket: 'Memilih banyak sel sekaligus dengan cepat.' },
      { k: ['Alt', '='], en: 'AutoSum', id: 'Jumlah otomatis', ket: 'Excel menuliskan rumus penjumlahan untukmu.' },
      { k: ['Ctrl', ';'], en: 'Today', id: 'Tanggal hari ini', ket: 'Mengetik tanggal hari ini sekali tekan.' },
      { k: ['F4'], en: 'Lock $ / repeat', id: 'Kunci alamat sel', ket: 'Saat menulis rumus: membekukan alamat sel dengan tanda $.' },
      { k: ['Ctrl', '1'], en: 'Format cells', id: 'Format sel', ket: 'Mengatur angka, rupiah, tanggal, garis tabel.' },
    ],
  },
  {
    cat: 'PowerPoint — presentasi (bekal modul berikutnya)',
    items: [
      { k: ['F5'], en: 'Slideshow', id: 'Mulai tayangan dari awal', ket: 'Slide memenuhi layar.' },
      { k: ['Shift', 'F5'], en: 'From current', id: 'Tayang dari slide ini', ket: 'Mulai dari slide yang sedang dibuka.' },
      { k: ['Esc'], en: 'End show', id: 'Keluar tayangan', ket: 'Kembali ke tampilan kerja.' },
      { k: ['Ctrl', 'M'], en: 'New slide', id: 'Slide baru', ket: 'Menambah slide setelah slide ini.' },
      { k: ['B'], en: 'Black screen', id: 'Layar hitam sejenak', ket: 'Saat presentasi, untuk menarik perhatian ke pembicara.' },
    ],
  },
  {
    cat: 'Browser & internet',
    items: [
      { k: ['Ctrl', 'T'], en: 'New tab', id: 'Tab baru', ket: 'Halaman baru tanpa menutup yang lama.' },
      { k: ['Ctrl', 'W'], en: 'Close tab', id: 'Tutup tab', ket: 'Menutup halaman yang sedang dibuka.' },
      { k: ['Ctrl', 'Shift', 'T'], en: 'Reopen tab', id: 'Buka lagi tab tertutup', ket: 'Penyelamat saat tak sengaja menutup halaman.' },
      { k: ['Ctrl', 'L'], en: 'Address bar', id: 'Ke kolom alamat', ket: 'Langsung ketik alamat atau kata pencarian.' },
      { k: ['F5'], en: 'Refresh', id: 'Muat ulang', ket: 'Halaman dimuat ulang dari awal.' },
      { k: ['Ctrl', '+'], en: 'Zoom in', id: 'Perbesar tampilan', ket: 'Tulisan di layar terlalu kecil? Tekan ini.' },
      { k: ['Ctrl', '-'], en: 'Zoom out', id: 'Perkecil tampilan', ket: 'Kebalikannya.' },
      { k: ['Ctrl', '0'], en: 'Reset zoom', id: 'Kembalikan ukuran normal', ket: 'Tampilan kembali 100%.' },
    ],
  },
]
