// MODUL 3 — PowerPoint Dasar
// Aturan bahasa Lentera: label yang TERTULIS di layar selalu disebut dwibahasa.

export const MODUL3 = {
  id: 'm3',
  title: 'Modul 3 — PowerPoint dasar',
  intro:
    'Word untuk dibaca, Excel untuk dihitung — PowerPoint untuk DITAYANGKAN. Inilah aplikasi membuat slide: layar-layar besar berisi poin penting yang menemanimu berbicara di depan orang: laporan kegiatan, sosialisasi warga, presentasi ke atasan. Di modul ini kamu membuat presentasi sungguhan dari nol: menulis judul, menambah slide, merapikan, sampai menayangkannya satu layar penuh dengan F5. Aturan bahasanya tetap: istilah layar ditulis berpasangan (New Slide/slide baru, Slide Show/tayangan).',
  bab: [
    /* ============ BAB 1 ============ */
    {
      id: 'm3.b1', no: 1,
      title: 'Kenalan dengan PowerPoint',
      desc: 'Membuka PowerPoint, mengenal slide, panel kiri, dan kotak isian.',
      blocks: [
        { t: 'p', text: 'Presentasi adalah tumpukan slide — bayangkan kartu-kartu besar yang ditayangkan satu per satu. Satu slide = satu layar. Tugasmu bukan menulis karangan di slide, melainkan menaruh POIN-POIN PENTING yang membantu pendengar mengikuti ceritamu.' },
        { t: 'h', text: 'Membuka PowerPoint' },
        { t: 'steps', items: [
          'Klik Start, langsung ketik: powerpoint.',
          'Tekan Enter. PowerPoint terbuka.',
          'Pilih "Blank Presentation/Presentasi kosong".',
        ]},
        { t: 'h', text: 'Peta layar PowerPoint' },
        { t: 'img', kind: 'ppt', props: {}, caption: 'Jendela PowerPoint: daftar slide kecil di panel kiri, slide yang sedang dikerjakan besar di tengah.' },
        { t: 'list', items: [
          'Panel kiri — daftar semua slide dalam bentuk gambar kecil (thumbnail). Klik untuk berpindah slide.',
          'Slide besar di tengah — lembar yang sedang kamu kerjakan.',
          'Kotak bergaris putus-putus — placeholder/kotak isian: "Click to add title/Klik untuk menambah judul". KLIK DULU kotaknya, baru mengetik.',
          'Ribbon di atas — saudara kembar ribbon Word: Home, Insert/Sisip, Design/Desain.',
        ]},
        { t: 'warn', text: 'Kesalahan pemula nomor satu: langsung mengetik tanpa mengeklik kotak isian — hurufnya tidak muncul di mana-mana. Selalu: klik kotaknya sampai kursor berkedip di dalamnya, baru mengetik.' },
        { t: 'p', text: 'Refleks lamamu tetap berlaku: Ctrl + S menyimpan (file PowerPoint berakhiran .pptx), Ctrl + Z membatalkan, Ctrl + B menebalkan.' },
        { t: 'try', text: 'Buka PowerPoint, pilih Blank Presentation. Klik kotak judul, ketik: Laporan Kegiatan Posyandu. Klik kotak di bawahnya, ketik namamu. Ctrl + S, simpan dengan nama "Latihan Presentasi".' },
        { t: 'glossary', items: [
          { term: 'Slide', def: 'Satu layar/halaman presentasi.' },
          { term: 'Placeholder', def: 'Kotak isian bergaris putus — klik dulu, baru ketik.' },
          { term: 'Thumbnail', def: 'Gambar kecil slide di panel kiri.' },
          { term: '.pptx', def: 'Akhiran file PowerPoint.' },
        ]},
      ],
      quiz: [
        { type: 'hotspot', q: 'Klik kotak tempat mengetik JUDUL slide.',
          img: { kind: 'ppt', props: {} }, accept: ['titlebox'],
          explain: 'Kotak isian atas — klik dulu sampai kursor berkedip, baru mengetik.' },
        { type: 'hotspot', q: 'Klik panel yang menampilkan DAFTAR semua slide.',
          img: { kind: 'ppt', props: {} }, accept: ['thumbs'],
          explain: 'Panel kiri — thumbnail tiap slide; klik untuk berpindah.' },
        { type: 'mc', q: 'Kamu mengetik tapi huruf tidak muncul di slide. Kemungkinan besar…',
          options: ['Belum mengeklik kotak isiannya dulu', 'PowerPoint rusak', 'Keyboard mati', 'Slide penuh'],
          answer: 0, explain: 'Klik kotak sampai kursor berkedip, baru huruf masuk.' },
        { type: 'mc', q: 'PowerPoint paling cocok untuk…',
          options: ['Menayangkan poin penting saat berbicara di depan orang', 'Menghitung total belanja', 'Mengetik surat izin', 'Menyimpan foto keluarga'],
          answer: 0, explain: 'Slide = pendamping bicara; hitungan = Excel; surat = Word.' },
      ],
    },

    /* ============ BAB 2 ============ */
    {
      id: 'm3.b2', no: 2,
      title: 'Menambah dan menyusun slide',
      desc: 'New Slide, memilih layout, memindah urutan, menghapus slide.',
      blocks: [
        { t: 'p', text: 'Satu slide tidak cukup untuk satu cerita. Menambah slide semudah satu klik — dan setiap slide baru menawarkan LAYOUT/tata letak: susunan kotak isian siap pakai (judul saja; judul + isi; dua kolom). Memakai layout membuat presentasimu rapi otomatis tanpa mengatur-atur kotak sendiri.' },
        { t: 'steps', items: [
          'Di tab Home, klik tombol "New Slide/Slide baru" — slide baru muncul setelah slide yang sedang aktif.',
          'Klik PANAH KECIL di bawah tombol New Slide untuk memilih layout: "Title and Content/Judul dan isi" adalah sahabat sehari-hari.',
          'Ulangi sampai kerangka ceritamu lengkap.',
        ]},
        { t: 'keys', items: [
          { combo: ['Ctrl', 'M'], label: 'New Slide/slide baru — tanpa menyentuh mouse' },
        ]},
        { t: 'h', text: 'Mengatur urutan dan menghapus' },
        { t: 'list', items: [
          'Memindah urutan: di panel kiri, klik thumbnail slide, TAHAN, seret ke posisi baru, lepas.',
          'Menghapus: klik thumbnail-nya, tekan Delete. (Salah hapus? Ctrl + Z.)',
          'Menggandakan: klik kanan thumbnail → Duplicate Slide/gandakan — berguna untuk slide berpola sama.',
        ]},
        { t: 'tip', text: 'Susun kerangka dulu, isi belakangan: slide 1 judul, slide 2 pembuka, slide 3–4 isi, slide terakhir penutup/terima kasih. Cerita yang urut lebih mudah diikuti.' },
        { t: 'try', text: 'Di Latihan Presentasi: tekan Ctrl + M dua kali — kini ada 3 slide. Di panel kiri, seret slide 3 ke posisi 2, lalu kembalikan. Hapus slide terakhir dengan Delete, lalu Ctrl + Z untuk mengembalikannya. Ctrl + S.' },
        { t: 'glossary', items: [
          { term: 'New Slide', def: 'Tombol menambah slide baru (Ctrl + M).' },
          { term: 'Layout', def: 'Susunan kotak isian siap pakai pada slide.' },
          { term: 'Duplicate', def: 'Menggandakan slide.' },
        ]},
      ],
      quiz: [
        { type: 'hotspot', q: 'Klik tombol untuk MENAMBAH slide baru.',
          img: { kind: 'ppt', props: {} }, accept: ['newslide'],
          explain: 'New Slide/slide baru — atau Ctrl + M.' },
        { type: 'mc', q: 'Pintasan keyboard menambah slide baru…',
          options: ['Ctrl + M', 'Ctrl + N', 'F5', 'Ctrl + P'],
          answer: 0, explain: 'Ctrl + M = New Slide. (Ctrl + N membuat FILE presentasi baru.)' },
        { type: 'mc', q: 'Mengubah urutan slide…',
          options: ['Seret thumbnail-nya di panel kiri ke posisi baru', 'Ketik ulang isinya di slide lain', 'Tidak bisa diubah', 'Hapus semua lalu buat ulang'],
          answer: 0, explain: 'Klik-tahan-seret di panel kiri — urutan berubah.' },
        { type: 'mc', q: 'Layout "Title and Content" berisi…',
          options: ['Kotak judul + kotak isi siap pakai', 'Slide kosong polos', 'Foto otomatis', 'Tabel Excel'],
          answer: 0, explain: 'Tata letak paling sering dipakai untuk slide isi.' },
      ],
    },

    /* ============ BAB 3 ============ */
    {
      id: 'm3.b3', no: 3,
      title: 'Menulis isi slide yang baik',
      desc: 'Butir singkat, huruf besar, satu slide satu gagasan.',
      blocks: [
        { t: 'p', text: 'Slide BUKAN dokumen Word yang ditembakkan ke dinding. Pendengar tidak bisa membaca paragraf panjang sambil mendengarkanmu — mereka akan memilih salah satu, dan biasanya berhenti mendengarkan. Slide yang baik berisi butir-butir pendek; ceritanya keluar dari MULUTMU.' },
        { t: 'list', items: [
          'Satu slide = satu gagasan. Gagasan baru? Slide baru (Ctrl + M murah).',
          'Tulis BUTIR, bukan kalimat panjang: "Peserta: 45 warga" — bukan "Kegiatan ini dihadiri oleh sebanyak 45 orang warga yang sangat antusias".',
          'Maksimal sekitar 6 butir per slide; lebih dari itu, pecah.',
          'Huruf harus terbaca dari kursi paling belakang: isi minimal sekitar 24, judul lebih besar lagi. Kalau ragu, BESARKAN.',
          'Angka penting boleh ditulis besar sendirian — lebih berbicara daripada sepuluh kalimat.',
        ]},
        { t: 'p', text: 'Saat mengetik di kotak isi, tiap kali menekan Enter, PowerPoint otomatis membuat butir baru (bullet). Tekan Tab untuk membuat anak butir, Shift + Tab untuk naik kembali — persis daftar di Word.' },
        { t: 'warn', text: 'Godaan terbesar pemula: menyalin paragraf utuh dari Word ke slide. Hasilnya huruf mengecil sendiri sampai tak terbaca. Ambil intinya saja — sisanya kamu yang bercerita.' },
        { t: 'try', text: 'Di slide 2, ketik judul: Hasil Kegiatan. Di kotak isi ketik tiga butir: Peserta: 45 warga (Enter), Lokasi: Balai Desa (Enter), Biaya: Rp 750.000. Perhatikan tiap Enter membuat butir baru. Ctrl + S.' },
        { t: 'glossary', items: [
          { term: 'Bullet (butir)', def: 'Satu baris poin di slide — dibuat otomatis tiap Enter.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Isi slide yang baik berupa…',
          options: ['Butir-butir pendek berisi inti', 'Paragraf panjang dan lengkap', 'Satu foto tanpa keterangan apa pun', 'Tabel sebesar mungkin'],
          answer: 0, explain: 'Slide menampilkan inti; ceritanya dari pembicara.' },
        { type: 'mc', q: 'Ukuran huruf ISI slide sebaiknya minimal sekitar…',
          options: ['24', '8', '11', '14'],
          answer: 0, explain: 'Harus terbaca dari kursi paling belakang.' },
        { type: 'mc', q: 'Di kotak isi, menekan Enter akan…',
          options: ['Membuat butir (bullet) baru', 'Menutup PowerPoint', 'Menayangkan slide', 'Menghapus slide'],
          answer: 0, explain: 'Satu Enter = satu butir baru.' },
        { type: 'mc', q: 'Materimu ada 10 butir untuk satu gagasan…',
          options: ['Pecah menjadi dua slide', 'Kecilkan huruf supaya muat', 'Hapus setengahnya sembarangan', 'Tulis bersambung ke pinggir'],
          answer: 0, explain: 'Slide baru itu gratis — keterbacaan tidak bisa ditawar.' },
      ],
    },

    /* ============ BAB 4 ============ */
    {
      id: 'm3.b4', no: 4,
      title: 'Gambar dan kerapian',
      desc: 'Menyisipkan gambar, mengubah ukuran dengan benar, menata posisi.',
      blocks: [
        { t: 'p', text: 'Satu gambar yang tepat menghidupkan slide: foto kegiatan, logo desa, grafik dari Excel. Menyisipkannya lewat tab Insert/Sisip.' },
        { t: 'steps', items: [
          'Klik tab Insert/Sisip → Pictures/Gambar → This Device/Perangkat ini.',
          'Cari file fotonya (latihan dari Modul 0 terpakai: kamu tahu fotomu di folder mana).',
          'Klik fotonya, klik Insert/Sisipkan — gambar masuk ke slide.',
        ]},
        { t: 'h', text: 'Mengubah ukuran TANPA penyok' },
        { t: 'p', text: 'Klik gambarnya — muncul bulatan-bulatan pegangan di tepinya. Seret bulatan di SUDUT: gambar membesar/mengecil dengan proporsi terjaga. Menyeret pegangan di sisi tengah membuat gambar gepeng atau melar — wajah orang jadi aneh. Sudut, selalu sudut.' },
        { t: 'list', items: [
          'Memindah: klik gambar, seret ke posisinya.',
          'Menghapus: klik gambar, tekan Delete.',
          'Gambar menutupi tulisan? Geser, atau kecilkan — jangan biarkan saling tindih.',
          'PowerPoint memunculkan garis bantu merah/abu saat gambar hampir sejajar tengah — manfaatkan agar rapi.',
        ]},
        { t: 'try', text: 'Sisipkan satu foto apa pun dari laptop ke slide 2. Kecilkan dari SUDUT sampai pas di samping butir-butirmu, lalu coba sekali seret dari sisi tengah — lihat gepengnya — dan Ctrl + Z. Ctrl + S.' },
        { t: 'glossary', items: [
          { term: 'Insert/Sisip', def: 'Tab untuk memasukkan gambar, tabel, dan lainnya.' },
          { term: 'Pegangan sudut', def: 'Bulatan di sudut gambar — penjaga proporsi saat mengubah ukuran.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Menyisipkan foto ke slide lewat…',
          options: ['Tab Insert/Sisip → Pictures/Gambar', 'Tab Design', 'Ctrl + P', 'Mengetik nama filenya di slide'],
          answer: 0, explain: 'Insert → Pictures → pilih file → Insert.' },
        { type: 'mc', q: 'Agar gambar membesar TANPA gepeng, seret pegangan di…',
          options: ['Sudutnya', 'Sisi tengah atas', 'Sisi tengah samping', 'Mana saja sama'],
          answer: 0, explain: 'Sudut menjaga proporsi panjang-lebar.' },
        { type: 'mc', q: 'Gambar menutupi tulisan slide…',
          options: ['Geser atau kecilkan gambarnya agar tidak menindih', 'Biarkan — yang penting ada gambar', 'Hapus tulisannya', 'Kecilkan hurufnya'],
          answer: 0, explain: 'Tulisan dan gambar harus sama-sama terbaca.' },
        { type: 'mc', q: 'Wajah di foto tampak melar/gepeng setelah diubah ukurannya. Penyebabnya…',
          options: ['Diseret dari pegangan sisi tengah, bukan sudut', 'File rusak', 'Slide kepenuhan', 'Foto terlalu tua'],
          answer: 0, explain: 'Sisi tengah mengubah satu arah saja — proporsi rusak.' },
      ],
    },

    /* ============ BAB 5 ============ */
    {
      id: 'm3.b5', no: 5,
      title: 'Menayangkan: saatnya tampil',
      desc: 'F5, Shift + F5, maju-mundur, layar hitam, dan keluar tayangan.',
      blocks: [
        { t: 'p', text: 'Inilah momen yang ditunggu: slide memenuhi seluruh layar dan kamu berbicara di depannya. Mode ini bernama Slide Show/tayangan.' },
        { t: 'keys', items: [
          { combo: ['F5'], label: 'Slide Show/tayangan dari slide PERTAMA' },
          { combo: ['Shift', 'F5'], label: 'Tayangan mulai dari slide yang SEDANG dibuka' },
          { combo: ['Esc'], label: 'Keluar dari tayangan, kembali ke layar kerja' },
        ]},
        { t: 'list', items: [
          'Maju: klik kiri, atau tekan Panah Kanan, atau Spasi.',
          'Mundur: Panah Kiri.',
          'Tombol B saat tayangan: layar jadi HITAM sejenak — semua mata kembali ke pembicara; tekan B lagi untuk kembali.',
          'Lompat ke slide tertentu: ketik nomornya lalu Enter (misal 3 Enter).',
        ]},
        { t: 'tip', text: 'Sebelum tampil sungguhan, latihan sekali penuh dengan F5: kamu akan menemukan salah ketik dan butir yang janggal — lebih baik ketahuan saat latihan daripada di depan atasan.' },
        { t: 'warn', text: 'Esc adalah pintu keluarnya. Banyak pemula panik karena "laptopnya terkunci di slide" — padahal cukup Esc.' },
        { t: 'try', text: 'Tekan F5 — presentasimu memenuhi layar. Maju dengan Spasi sampai habis, mundur dengan Panah Kiri, tekan B (gelap) lalu B lagi, lalu Esc untuk keluar.' },
        { t: 'glossary', items: [
          { term: 'Slide Show', def: 'Mode tayangan satu layar penuh.' },
          { term: 'B (saat tayang)', def: 'Layar hitam sejenak — perhatian ke pembicara.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Memulai tayangan dari slide PERTAMA…',
          options: ['F5', 'Esc', 'Ctrl + M', 'F2'],
          answer: 0, explain: 'F5 — Shift + F5 bila ingin mulai dari slide yang dibuka.' },
        { type: 'mc', q: 'Keluar dari mode tayangan…',
          options: ['Esc', 'Mematikan laptop', 'Ctrl + W', 'Menunggu habis sendiri'],
          answer: 0, explain: 'Esc — pintu keluar yang tenang.' },
        { type: 'mc', q: 'Saat tayangan, tombol B berguna untuk…',
          options: ['Menghitamkan layar sejenak agar perhatian ke pembicara', 'Menebalkan huruf', 'Membuka browser', 'Mencetak slide'],
          answer: 0, explain: 'B = black/hitam; tekan lagi untuk kembali.' },
        { type: 'hotspot', q: 'Klik tombol di ribbon untuk MEMULAI tayangan.',
          img: { kind: 'ppt', props: {} }, accept: ['present'],
          explain: 'Slide Show — kembarannya tombol F5.' },
      ],
    },

    /* ============ BAB 6 ============ */
    {
      id: 'm3.b6', no: 6,
      title: 'Desain seragam dan pantas',
      desc: 'Memilih tema, menjaga konsistensi, warna yang terbaca.',
      blocks: [
        { t: 'p', text: 'PowerPoint menyediakan Themes/tema di tab Design/Desain: paket warna + huruf + latar yang dirancang serasi. Satu klik, SEMUA slide langsung berdandan seragam — inilah cara tercepat tampil profesional tanpa jadi desainer.' },
        { t: 'steps', items: [
          'Klik tab Design/Desain.',
          'Arahkan mouse ke pilihan tema — slide ikut berubah sebagai pratinjau.',
          'Klik satu tema yang tenang. Selesai: seluruh presentasi seragam.',
        ]},
        { t: 'list', items: [
          'Satu presentasi = SATU tema. Ganti-ganti tema tiap slide terlihat berantakan.',
          'Kontras adalah raja: tulisan gelap di latar terang, atau terang di latar gelap. Kuning di atas putih = tak terbaca.',
          'Untuk laporan kerja, pilih tema sederhana — hindari yang ramai hiasan.',
          'Tema membuat judul dan butir otomatis serasi ukurannya antar-slide.',
        ]},
        { t: 'warn', text: 'Animasi dan suara berlebihan adalah jebakan: teks berputar-putar masuk justru membuat pendengar pusing dan terkesan main-main. Untuk presentasi kerja: tanpa animasi pun sudah pantas.' },
        { t: 'try', text: 'Buka tab Design, arahkan mouse ke beberapa tema dan lihat pratinjaunya, lalu pilih satu yang sederhana. Periksa semua slide ikut berubah. Ctrl + S.' },
        { t: 'glossary', items: [
          { term: 'Theme (tema)', def: 'Paket desain seragam untuk seluruh slide.' },
          { term: 'Kontras', def: 'Beda terang-gelap antara tulisan dan latar — kunci keterbacaan.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Cara tercepat membuat SEMUA slide berdandan seragam…',
          options: ['Pilih satu tema di tab Design/Desain', 'Mewarnai slide satu per satu', 'Memasang banyak animasi', 'Mengetik ulang semuanya'],
          answer: 0, explain: 'Satu klik tema = seluruh presentasi serasi.' },
        { type: 'mc', q: 'Pasangan warna yang TERBACA…',
          options: ['Tulisan gelap di latar terang', 'Kuning di atas putih', 'Abu muda di atas putih', 'Merah di atas oranye'],
          answer: 0, explain: 'Kontras tinggi = terbaca dari belakang ruangan.' },
        { type: 'mc', q: 'Jumlah tema yang pantas dalam SATU presentasi…',
          options: ['Satu', 'Satu per slide', 'Minimal tiga', 'Bebas, makin banyak makin bagus'],
          answer: 0, explain: 'Konsistensi = profesional.' },
        { type: 'mc', q: 'Animasi teks berputar-putar di presentasi laporan kerja…',
          options: ['Sebaiknya dihindari — mengganggu dan terkesan main-main', 'Wajib di tiap slide', 'Membuat nilai naik', 'Mempercepat presentasi'],
          answer: 0, explain: 'Isi yang jelas mengalahkan hiasan yang ramai.' },
      ],
    },

    /* ============ BAB 7 ============ */
    {
      id: 'm3.b7', no: 7,
      title: 'Simpan, kirim, dan siap tampil',
      desc: 'pptx vs PDF, nama file jelas, dan ritual sebelum presentasi.',
      blocks: [
        { t: 'p', text: 'Presentasimu hidup di file .pptx — itu bentuk yang bisa DISUNTING. Tapi saat dikirim ke orang lain atau dibuka di laptop berbeda, tampilannya bisa bergeser kalau laptop itu tidak punya huruf yang sama. Solusinya kawan lama kita: PDF — bentuk beku yang tampil sama di mana pun.' },
        { t: 'list', items: [
          'Akan DIEDIT lagi / DITAYANGKAN olehmu: simpan .pptx.',
          'Dikirim untuk DIBACA (laporan ke atasan, arsip): simpan juga sebagai PDF — F12 (Save As/simpan sebagai), pilih jenis PDF.',
          'Nama file jelas, seperti biasa: "Laporan Posyandu Juni 2026" — bukan "presentasi final fix".',
        ]},
        { t: 'h', text: 'Ritual sebelum tampil' },
        { t: 'steps', items: [
          'Buka filenya LEBIH AWAL — jangan lima detik sebelum giliran.',
          'Jalankan F5 sekali penuh: periksa salah ketik dan urutan.',
          'Tutup aplikasi lain yang tidak perlu — biar laptop ringan dan tak ada notifikasi nongol di tengah tayangan.',
          'Siapkan rencana cadangan: salinan PDF di flashdisk (Modul 0 Bab 7 terpakai).',
        ]},
        { t: 'tip', text: 'Kalau menayangkan lewat proyektor/TV dan layar tidak muncul: Win + P, pilih Duplicate/duplikat — jurus layar kembar.' },
        { t: 'try', text: 'Simpan presentasimu sebagai PDF lewat F12 (pilih jenis PDF). Buka PDF-nya, bandingkan dengan versi .pptx. Lalu jalankan ritual: F5 sekali penuh dari awal sampai akhir.' },
        { t: 'glossary', items: [
          { term: '.pptx', def: 'Bentuk presentasi yang bisa disunting dan ditayangkan.' },
          { term: 'Win + P', def: 'Pengaturan layar proyektor — pilih Duplicate.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Mengirim presentasi agar TAMPIL SAMA di perangkat siapa pun…',
          options: ['Simpan juga sebagai PDF', 'Kirim .pptx selalu', 'Foto tiap slide pakai HP', 'Print lalu difoto'],
          answer: 0, explain: 'PDF = bentuk beku; .pptx untuk menyunting/menayangkan.' },
        { type: 'mc', q: 'Tombol pintas membuka jendela Save As/simpan sebagai…',
          options: ['F12', 'F5', 'Ctrl + M', 'Esc'],
          answer: 0, explain: 'F12 — sama seperti di Word dan Excel.' },
        { type: 'mc', q: 'Proyektor terpasang tapi slide tidak muncul di layar besar…',
          options: ['Win + P, pilih Duplicate/duplikat', 'Restart berkali-kali', 'Tekan B', 'Cabut-pasang mouse'],
          answer: 0, explain: 'Win + P mengatur ke layar mana tampilan dikirim.' },
        { type: 'mc', q: 'Persiapan paling penting sebelum tampil…',
          options: ['Menjalankan F5 sekali penuh untuk memeriksa', 'Menambah animasi di menit akhir', 'Mengganti tema tiap slide', 'Menghapus slide penutup'],
          answer: 0, explain: 'Gladi bersih menangkap salah ketik sebelum pendengar melihatnya.' },
      ],
    },
  ],

  /* ============ UJIAN PRAKTEK MODUL 3 (unggah .pptx) ============ */
  praktik: {
    id: 'm3.praktik',
    title: 'Ujian praktek — Presentasi Laporan',
    pass: 80,
    ext: ['pptx'],
    brief: [
      'Buka PowerPoint, buat presentasi baru bertema laporan kegiatan versimu sendiri (bebas: posyandu, kerja bakti, rapat RT).',
      'Slide 1: judul laporan + namamu (klik kotak isiannya dulu).',
      'Tambahkan slide (Ctrl + M) hingga total MINIMAL 3 slide.',
      'Minimal satu slide berisi BUTIR-BUTIR: 3 poin atau lebih (tiap Enter = butir baru).',
      'Isi seluruh presentasi minimal 30 kata — singkat boleh, kosong jangan.',
      'Simpan (Ctrl + S) sebagai .pptx dengan nama jelas, lalu unggah file itu di sini.',
    ],
    rubric: [
      { id: 'pptx-valid', label: 'File PowerPoint (.pptx) terbaca dengan baik' },
      { id: 'slide-3', label: 'Ada minimal 3 slide' },
      { id: 'judul-slide1', label: 'Slide pertama berisi judul (ada tulisannya)' },
      { id: 'isi-butir', label: 'Ada slide berisi minimal 3 butir poin' },
      { id: 'kata-30', label: 'Total isi minimal 30 kata' },
    ],
  },

  /* ============ UJIAN AKHIR ============ */
  final: {
    id: 'm3.final',
    pass: 85,
    title: 'Ujian akhir Modul 3',
    intro: 'Lima belas soal dari semua bab PowerPoint dasar. Satu kesempatan jawab per soal, nilai lulus 85. Belum lulus? Pelajari pembahasan, ulangi — soal diacak ulang.',
    questions: [
      { type: 'hotspot', q: 'Klik kotak tempat mengetik JUDUL slide.',
        img: { kind: 'ppt', props: {} }, accept: ['titlebox'],
        explain: 'Klik kotak isiannya dulu, baru mengetik.' },
      { type: 'mc', q: 'Huruf tidak muncul saat mengetik di slide. Penyebab tersering…',
        options: ['Kotak isian belum diklik', 'Slide penuh', 'File rusak', 'Caps Lock menyala'],
        answer: 0, explain: 'Kursor harus berkedip di dalam kotak dulu.' },
      { type: 'mc', q: 'Menambah slide baru dengan keyboard…',
        options: ['Ctrl + M', 'Ctrl + N', 'Ctrl + S', 'F2'],
        answer: 0, explain: 'Ctrl + M = New Slide.' },
      { type: 'hotspot', q: 'Klik panel untuk MELIHAT dan MENYERET urutan slide.',
        img: { kind: 'ppt', props: {} }, accept: ['thumbs'],
        explain: 'Panel kiri — seret thumbnail untuk mengubah urutan.' },
      { type: 'mc', q: 'Isi slide yang baik…',
        options: ['Butir pendek berisi inti', 'Paragraf utuh dari Word', 'Sebanyak mungkin tulisan', 'Huruf kecil supaya muat'],
        answer: 0, explain: 'Slide = inti; cerita lengkap dari pembicara.' },
      { type: 'mc', q: 'Ukuran huruf isi sebaiknya minimal sekitar…',
        options: ['24', '10', '12', '8'],
        answer: 0, explain: 'Terbaca dari kursi paling belakang.' },
      { type: 'mc', q: 'Di kotak isi, satu tekanan Enter menghasilkan…',
        options: ['Satu butir baru', 'Slide baru', 'Tayangan dimulai', 'File tersimpan'],
        answer: 0, explain: 'Enter = butir; Ctrl + M = slide.' },
      { type: 'mc', q: 'Agar foto tidak gepeng saat diperbesar, seret pegangan di…',
        options: ['Sudut', 'Sisi tengah', 'Bagian dalam foto', 'Mana pun sama saja'],
        answer: 0, explain: 'Sudut menjaga proporsi.' },
      { type: 'mc', q: 'Menyisipkan foto kegiatan ke slide…',
        options: ['Insert/Sisip → Pictures/Gambar', 'Design → Themes', 'Ctrl + P', 'F5'],
        answer: 0, explain: 'Tab Insert untuk segala sisipan.' },
      { type: 'mc', q: 'Memulai tayangan dari slide pertama…',
        options: ['F5', 'Esc', 'F12', 'Ctrl + M'],
        answer: 0, explain: 'F5; dari slide aktif = Shift + F5.' },
      { type: 'mc', q: 'Keluar dari tayangan…',
        options: ['Esc', 'Menutup laptop', 'Ctrl + W dua kali', 'Menunggu'],
        answer: 0, explain: 'Esc — kembali ke layar kerja.' },
      { type: 'hotspot', q: 'Klik tombol untuk MENAMBAH slide.',
        img: { kind: 'ppt', props: {} }, accept: ['newslide'],
        explain: 'New Slide — kembaran Ctrl + M.' },
      { type: 'mc', q: 'Membuat seluruh slide berdandan seragam sekali jalan…',
        options: ['Pilih satu tema di tab Design', 'Warnai manual tiap slide', 'Salin-tempel slide pertama terus', 'Pasang animasi'],
        answer: 0, explain: 'Theme = paket desain serasi.' },
      { type: 'mc', q: 'Saat tayangan, menghitamkan layar sejenak…',
        options: ['Tekan B', 'Tekan Esc', 'Cabut kabel', 'Tekan F12'],
        answer: 0, explain: 'B = black; tekan lagi untuk kembali.' },
      { type: 'mc', q: 'Mengirim presentasi untuk dibaca atasan agar tampil sama persis…',
        options: ['Sertakan versi PDF', 'Kirim .pptx saja selalu', 'Foto layar tiap slide', 'Tulis ulang di WA'],
        answer: 0, explain: 'PDF membekukan tampilan di perangkat mana pun.' },
    ],
  },
}

// 7 bab + ujian praktek + ujian teori = 9 langkah Modul 3.
export const M3_ITEMS = [
  'm3.b1', 'm3.b2', 'm3.b3', 'm3.b4', 'm3.b5', 'm3.b6', 'm3.b7', 'm3.praktik', 'm3.final',
]
