// MODUL BONUS — Bekerja Cerdas dengan AI (ChatGPT & Gemini)
// Terbuka untuk SEMUA peserta sejak hari pertama, level apa pun, tanpa gerbang.
// Tidak mempengaruhi Indeks Lentera maupun syarat sertifikat — murni nilai tambah.

export const MODULBONUS = {
  id: 'mb',
  title: 'Modul Bonus — Bekerja cerdas dengan AI',
  intro:
    'Modul istimewa: terbuka untuk SIAPA SAJA sejak hari pertama, di level mana pun — boleh dicicil sambil belajar modul lain. Di kantor modern, staf yang tahu cara memakai AI menyelesaikan pekerjaan lebih cepat dengan hasil lebih rapi. Di sini kamu berkenalan dengan dua asisten AI paling mudah diakses — ChatGPT dan Gemini — lalu belajar jurus terpenting: cara MEMINTA yang benar (prompt), memakainya untuk pekerjaan kantor, menjadikannya guru pribadi untuk naik keterampilan, dan memakainya dengan aman serta jujur. AI tidak menggantikan kamu — orang yang pandai memakai AI yang akan unggul.',
  bab: [
    /* ============ BAB 1 ============ */
    {
      id: 'mb.b1', no: 1,
      title: 'Kenalan: ChatGPT & Gemini, asisten yang bisa salah',
      desc: 'Apa itu AI percakapan, cara mengaksesnya gratis, dan watak aslinya.',
      blocks: [
        { t: 'p', text: 'ChatGPT (buatan OpenAI) dan Gemini (buatan Google) adalah AI PERCAKAPAN: kamu mengetik permintaan dalam bahasa sehari-hari, ia menjawab dalam hitungan detik — menulis surat, merangkum dokumen, menjelaskan rumus Excel, menerjemahkan, memberi ide. Bayangkan asisten kantor yang sangat cepat, sangat luas bacaannya, bekerja 24 jam, dan tidak pernah tersinggung disuruh mengulang.' },
        { t: 'steps', items: [
          'ChatGPT: buka chatgpt.com di browser (Modul 4) — bisa langsung dipakai; membuat akun gratis membuka lebih banyak fitur dan menyimpan riwayat.',
          'Gemini: buka gemini.google.com — masuk dengan akun Google/Gmail yang sudah kamu buat di Modul 4. Di HP, keduanya juga tersedia sebagai aplikasi.',
          'Ketik permintaan di kotak bawah, tekan Enter. Jawaban muncul mengalir. Kamu bisa langsung membalas — AI INGAT percakapan dalam satu obrolan.',
          'Versi gratis keduanya sudah sangat cukup untuk pekerjaan kantor; ada batas pemakaian per hari, dan itu tidak masalah.',
        ]},
        { t: 'h', text: 'Watak yang wajib kamu hafal' },
        { t: 'list', items: [
          'AI sangat PERCAYA DIRI — bahkan saat jawabannya salah. Ini disebut "halusinasi": ia bisa mengarang angka, nama, atau aturan dengan gaya meyakinkan.',
          'AI tidak tahu urusan kantormu — ia hanya tahu apa yang KAMU ceritakan di kotak obrolan.',
          'Karena itu hukum besinya: AI boleh MEMBANTU MEMBUAT, kamu yang WAJIB MEMERIKSA. Nama, angka, tanggal, dan aturan selalu dicek ulang sebelum dipakai.',
        ]},
        { t: 'warn', text: 'Anggap kotak obrolan AI seperti tempat umum: JANGAN PERNAH menempelkan KTP, NIK, nomor rekening, sandi, gaji orang, atau data warga/perusahaan yang rahasia. Samarkan dulu — ganti nama asli dengan "Bapak A", angka sensitif dengan "Rp X".' },
        { t: 'tip', text: 'Pakai keduanya: tanyakan hal yang sama ke ChatGPT dan Gemini lalu bandingkan. Kalau dua-duanya sepakat, kepercayaanmu naik; kalau berbeda, itu tanda harus dicek ke sumber resmi.' },
        { t: 'try', text: 'Buka gemini.google.com ATAU chatgpt.com, lalu ketik: "Perkenalkan dirimu dalam 3 kalimat bahasa Indonesia, lalu sebutkan 3 hal yang bisa kamu bantu untuk staf administrasi." Baca jawabannya — kamu baru saja memakai AI pertamamu.' },
        { t: 'glossary', items: [
          { term: 'AI percakapan', def: 'Program yang diajak mengobrol untuk menghasilkan teks: jawaban, tulisan, ide.' },
          { term: 'Prompt', def: 'Tulisan permintaanmu kepada AI — kualitas prompt menentukan kualitas jawaban.' },
          { term: 'Halusinasi', def: 'Saat AI mengarang fakta dengan gaya meyakinkan. Selalu cek ulang.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Sikap paling benar terhadap jawaban AI…',
          options: ['AI membantu membuat, saya wajib memeriksa', 'AI pasti benar karena komputer', 'AI pasti salah, tak usah dipakai', 'Langsung kirim ke atasan tanpa dibaca'],
          answer: 0, explain: 'AI percaya diri walau salah — pemeriksa terakhir tetap manusia.' },
        { type: 'mc', q: '"Halusinasi" pada AI artinya…',
          options: ['AI mengarang fakta dengan gaya meyakinkan', 'AI melihat hantu', 'AI rusak total', 'AI menolak menjawab'],
          answer: 0, explain: 'Nama, angka, dan aturan dari AI selalu dicek ke sumber asli.' },
        { type: 'mc', q: 'Yang TIDAK boleh ditempel ke kotak obrolan AI…',
          options: ['NIK, sandi, nomor rekening, data rahasia kantor', 'Pertanyaan tentang rumus Excel', 'Draf surat undangan tanpa data sensitif', 'Permintaan ide judul slide'],
          answer: 0, explain: 'Samarkan data sensitif: "Bapak A", "Rp X".' },
        { type: 'mc', q: 'Cara mengakses Gemini…',
          options: ['gemini.google.com dengan akun Google', 'Harus beli komputer khusus', 'Hanya lewat surat resmi', 'Datang ke kantor Google'],
          answer: 0, explain: 'Akun Gmail dari Modul 4 langsung bisa dipakai; ChatGPT di chatgpt.com.' },
      ],
    },

    /* ============ BAB 2 ============ */
    {
      id: 'mb.b2', no: 2,
      title: 'Jurus prompt: resep PINTA',
      desc: 'Cara meminta yang menghasilkan jawaban kelas kantoran, bukan jawaban asal.',
      blocks: [
        { t: 'p', text: 'Bedanya pengguna AI biasa dan pengguna AI andal hanya satu: CARA MEMINTA. "Buatkan surat" menghasilkan surat generik; permintaan yang lengkap menghasilkan surat yang nyaris siap kirim. Hafalkan resep PINTA — empat bahan dalam satu permintaan:' },
        { t: 'list', items: [
          'P — PERAN: beri AI jabatan. "Kamu adalah staf administrasi senior yang teliti…"',
          'IN — INFORMASI: ceritakan bahan & latarnya. "…Acara: rapat ketua RT, Kamis 19 Juni pukul 14.00 di Balai Warga, mengundang 5 ketua RT…"',
          'T — TUGAS: katakan persis apa yang dibuat. "…Buatkan surat undangan resmi…"',
          'A — ATURAN HASIL: bentuk, panjang, bahasa, nada. "…Bahasa Indonesia baku tapi hangat, maksimal 1 halaman, ada tempat tanda tangan, JANGAN pakai kata-kata berlebihan."',
        ]},
        { t: 'h', text: 'Tiga jurus lanjutan' },
        { t: 'steps', items: [
          'Jurus BERTANYA-DULU: akhiri prompt dengan "Sebelum membuat, ajukan 3 pertanyaan yang kamu butuhkan." AI jadi bertanya seperti staf yang baik — jawabanmu membuat hasilnya pas.',
          'Jurus PERBAIKI-BAGIAN: jangan puas pada jawaban pertama. Balas: "Bagus. Perpendek paragraf pembuka, ganti nadanya jadi lebih santai, beri 2 pilihan kalimat penutup." Mengobrol itu gratis.',
          'Jurus CONTOH: tempelkan satu contoh hasil yang kamu sukai (mis. surat lama yang bagus, tanpa data sensitif) lalu minta "buat yang baru dengan gaya seperti contoh ini."',
        ]},
        { t: 'tip', text: 'Satu obrolan = satu urusan. Mulai obrolan baru untuk urusan baru supaya AI tidak tercampur konteks lama. Dan tulis prompt seperti memberi tugas ke orang: kalau manusia akan bingung membacanya, AI juga.' },
        { t: 'warn', text: 'Prompt pendek bukan dosa — untuk pertanyaan sederhana ("apa beda Save dan Save As?") langsung tanya saja. PINTA dipakai saat hasilnya akan DIPAKAI BEKERJA.' },
        { t: 'try', text: 'Praktikkan PINTA sungguhan: minta AI membuat surat undangan rapat RT dengan keempat bahan di atas, lalu pakai jurus perbaiki-bagian minimal satu kali. Bandingkan dengan hasil prompt "buatkan surat undangan" polos — rasakan bedanya.' },
        { t: 'glossary', items: [
          { term: 'PINTA', def: 'Resep prompt: Peran, INformasi, Tugas, Aturan hasil.' },
          { term: 'Iterasi', def: 'Memperbaiki jawaban AI lewat balasan lanjutan, bagian demi bagian.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Empat bahan resep PINTA…',
          options: ['Peran, Informasi, Tugas, Aturan hasil', 'Pendek, Instan, Tanpa data, Asal jadi', 'Pagi, Siang, Sore, Malam', 'Print, Insert, Tab, Alt'],
          answer: 0, explain: 'Beri jabatan, beri bahan, sebut tugas persis, tentukan bentuk hasil.' },
        { type: 'mc', q: 'Jawaban pertama AI kurang pas. Langkah terbaik…',
          options: ['Balas dengan perintah perbaikan yang spesifik', 'Menyerah, kerjakan manual semua', 'Marah-marah di kotak obrolan', 'Kirim saja apa adanya'],
          answer: 0, explain: '"Perpendek pembuka, nada lebih santai" — mengobrol itu gratis.' },
        { type: 'mc', q: '"Sebelum membuat, ajukan 3 pertanyaan dulu" berguna karena…',
          options: ['AI menggali info yang kurang, hasil jadi pas kebutuhan', 'AI jadi takut', 'Menghemat listrik', 'AI menolak bekerja'],
          answer: 0, explain: 'Seperti staf baik: bertanya dulu sebelum mengerjakan.' },
        { type: 'mc', q: 'Memberi AI contoh surat lama yang bagus (tanpa data sensitif) berguna untuk…',
          options: ['AI meniru gaya yang kamu sukai', 'Membuat AI bosan', 'Mengunci akun', 'Tidak ada gunanya'],
          answer: 0, explain: 'Jurus contoh: hasil baru bergaya seperti contohmu.' },
      ],
    },

    /* ============ BAB 3 ============ */
    {
      id: 'mb.b3', no: 3,
      title: 'AI di meja kerja: surat, rekap, slide',
      desc: 'Memakai AI untuk pekerjaan kantor nyata — lebih cepat, hasil tetap kamu yang pegang.',
      blocks: [
        { t: 'p', text: 'Sekarang gabungkan AI dengan semua jurus Modul 1–5. Polanya selalu sama: AI MENYIAPKAN DRAF → kamu MEMINDAHKAN ke Word/Excel/PowerPoint → kamu MERAPIKAN & MEMERIKSA → baru dipakai. AI mempercepat 70% awal; 30% akhir — ketelitian dan tanggung jawab — tetap milikmu.' },
        { t: 'list', items: [
          'SURAT & EMAIL (Word, M1/M4): minta draf dengan PINTA; atau tempel draf burukmu lalu minta "rapikan ejaan dan nadanya, jangan ubah isinya". Balasan email sulit (menolak halus, menagih sopan) — AI jago mencarikan kalimatnya.',
          'RANGKUMAN: tempel pengumuman/notulen panjang (yang tidak rahasia) → "ringkas jadi 5 butir untuk dilaporkan ke atasan".',
          'EXCEL (M2/M5): tanyakan "rumus untuk menjumlah kolom B hanya jika kolom A berisi Snack" — AI memberi rumus + penjelasan. Tempel pesan error/#N/A → AI menerangkan penyebabnya. Jangan tempel isi tabel berdata sensitif; cukup ceritakan strukturnya.',
          'POWERPOINT (M3): "buat kerangka 5 slide laporan kegiatan: judul tiap slide + 3 butir isinya" → kamu tinggal memindahkan dan mempercantik.',
          'TERJEMAHAN & ISTILAH: label Inggris di layar, dokumen berbahasa asing, atau "bahasa halusnya menolak lembur apa ya?" — tanyakan langsung.',
        ]},
        { t: 'steps', items: [
          'Tulis prompt PINTA di ChatGPT/Gemini, sertakan jurus bertanya-dulu bila tugasnya besar.',
          'Salin hasil (blok → Ctrl + C), tempel ke aplikasi tujuannya (Ctrl + V), rapikan format dengan jurus modulmu.',
          'PERIKSA: nama, gelar, tanggal, hari, angka, nomor — kesalahan AI paling sering di sini.',
          'Simpan dengan nama benar (Ctrl + S), perlakukan seperti karyamu — karena memang karyamu.',
        ]},
        { t: 'warn', text: 'Jangan kirim hasil AI mentah-mentah. Atasan menilai KAMU, bukan AI — satu nama salah atau tanggal ngawur yang lolos adalah tanggung jawabmu, bukan tanggung jawab mesin.' },
        { t: 'try', text: 'Ambil tugas Babak 2 Modul 5 (surat undangan ketua RT): minta draf ke AI dengan PINTA, pindahkan ke Word, rapikan, lalu periksa nama-tanggal-jam dengan teliti. Hitung berapa menit kamu hemat.' },
        { t: 'glossary', items: [
          { term: 'Draf', def: 'Tulisan kasar pertama — bahan untuk dirapikan, bukan hasil akhir.' },
          { term: 'Pola AI-kantor', def: 'AI membuat draf → kamu pindahkan → rapikan → PERIKSA → pakai.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Pola kerja AI di kantor yang benar…',
          options: ['AI membuat draf → saya rapikan & periksa → baru dipakai', 'AI membuat → langsung kirim', 'Saya ketik semua, AI menonton', 'AI yang menandatangani'],
          answer: 0, explain: '70% awal dari AI, 30% ketelitian akhir dari kamu.' },
        { type: 'mc', q: 'Bagian yang PALING wajib diperiksa pada draf surat dari AI…',
          options: ['Nama, gelar, tanggal, hari, dan angka', 'Jenis hurufnya', 'Warna layarnya', 'Tidak perlu diperiksa'],
          answer: 0, explain: 'Di situlah halusinasi paling sering menyelinap.' },
        { type: 'mc', q: 'Bingung rumus Excel untuk kebutuhan tertentu…',
          options: ['Ceritakan kebutuhannya ke AI, minta rumus + penjelasan', 'Menyerah pakai kalkulator', 'Ketik angka manual semua', 'Hapus tabelnya'],
          answer: 0, explain: 'AI guru rumus yang sabar — struktur tabel boleh diceritakan, data sensitif jangan.' },
        { type: 'mc', q: 'Minta AI membuat kerangka slide artinya AI memberi…',
          options: ['Judul tiap slide + butir isinya, kamu yang memindahkan & mempercantik', 'File .pptx jadi terkirim ke atasan', 'Proyektor baru', 'Tema warna saja'],
          answer: 0, explain: 'Kerangka dari AI + jurus PowerPoint-mu = slide cepat dan rapi.' },
      ],
    },

    /* ============ BAB 4 ============ */
    {
      id: 'mb.b4', no: 4,
      title: 'AI sebagai guru pribadi: naik keterampilan',
      desc: 'Guru yang sabar 24 jam: menjelaskan, melatih, menguji, dan menyusun rencana belajarmu.',
      blocks: [
        { t: 'p', text: 'Kekuatan AI yang paling mengubah hidup justru bukan membuat surat — tapi MENGAJARI. Ia menjelaskan dengan bahasa apa pun yang kamu minta, tidak pernah lelah ditanya "kenapa", dan bisa menguji kamu balik. Inilah guru pribadi gratis untuk naik kelas keterampilan.' },
        { t: 'list', items: [
          'JURUS "JELASKAN SEPERTI…": "Jelaskan VLOOKUP seperti ke orang yang baru bisa Excel kemarin, pakai analogi pasar." Belum paham? "Lebih sederhana lagi" — ulangi tanpa malu.',
          'JURUS LATIHAN: "Buat 5 soal latihan rumus IF untuk pemula. Tunggu jawabanku satu per satu, lalu nilai dan jelaskan letak salahku."',
          'JURUS GLADI: "Berperanlah sebagai pewawancara kerja posisi staf admin. Ajukan pertanyaan satu per satu, beri masukan atas tiap jawabanku." Bisa juga gladi bicara dengan atasan atau pelanggan yang marah.',
          'JURUS RENCANA: "Susun rencana belajar 30 hari menguasai Excel menengah, 30 menit per hari, untukku yang sudah lulus Excel dasar. Bentuk tabel mingguan."',
          'BAHASA INGGRIS: "Ajak aku percakapan Inggris sederhana tentang pekerjaan kantor; koreksi kesalahanku dengan halus dalam bahasa Indonesia."',
        ]},
        { t: 'p', text: 'Gemini dan ChatGPT juga bisa MEMBACA GAMBAR: foto soal, tangkapan layar pesan error, atau halaman dokumen — unggah lewat ikon gambar/klip di kotak obrolan, lalu bertanya tentang isinya. Layar error yang menakutkan jadi bisa "ditanyakan".' },
        { t: 'tip', text: 'Tutup tiap sesi belajar dengan: "Uji aku 3 pertanyaan tentang yang barusan, jangan tunjukkan jawabannya dulu." Diuji = ingat jauh lebih lama. Dan simpan obrolan belajarmu — riwayat di ChatGPT/Gemini adalah buku catatan gratis.' },
        { t: 'try', text: 'Pilih satu hal yang masih bikin ragu dari Modul 0–5 (misal VLOOKUP atau mail merge). Minta AI menjelaskannya dengan analogi, minta 3 soal latihan, jawab, dan minta nilai. Rasakan punya guru pribadi.' },
        { t: 'glossary', items: [
          { term: 'Gladi peran', def: 'AI berpura-pura jadi pewawancara/atasan/pelanggan untuk tempat latihanmu yang aman.' },
          { term: 'Multimodal', def: 'AI yang bisa membaca gambar/foto, bukan hanya teks.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Penjelasan AI masih terlalu sulit…',
          options: ['Minta "jelaskan lebih sederhana, pakai analogi" — boleh berkali-kali', 'Pura-pura paham', 'Berhenti belajar', 'Salahkan komputer'],
          answer: 0, explain: 'Guru ini tidak pernah lelah dan tidak menghakimi.' },
        { type: 'mc', q: 'Persiapan wawancara kerja dengan AI paling efektif lewat…',
          options: ['Gladi peran: AI jadi pewawancara, menanya satu per satu + masukan', 'Membaca arti mimpi', 'Minta AI datang mewakili', 'Menghafal satu jawaban untuk semua soal'],
          answer: 0, explain: 'Tempat latihan aman — salah di gladi, bukan di hari H.' },
        { type: 'mc', q: 'Foto pesan error di layar bisa…',
          options: ['Diunggah ke AI lalu ditanyakan artinya & solusinya', 'Hanya dipajang', 'Membuat AI rusak', 'Dicetak lalu dibakar'],
          answer: 0, explain: 'ChatGPT & Gemini bisa membaca gambar — error jadi bisa "ditanyakan".' },
        { type: 'mc', q: 'Agar ilmu menempel, akhiri sesi belajar dengan…',
          options: ['Minta AI menguji 3 pertanyaan tanpa menunjukkan jawaban dulu', 'Langsung tutup laptop', 'Minta AI memuji kamu', 'Menghapus riwayat obrolan'],
          answer: 0, explain: 'Diuji membuat ingatan bertahan jauh lebih lama.' },
      ],
    },

    /* ============ BAB 5 ============ */
    {
      id: 'mb.b5', no: 5,
      title: 'Aman, jujur, dan tetap jadi manusianya',
      desc: 'Aturan main memakai AI di dunia kerja — supaya AI mengangkatmu, bukan menjatuhkanmu.',
      blocks: [
        { t: 'p', text: 'AI itu pisau dapur: di tangan yang tertib ia mempercepat segalanya, di tangan yang ceroboh ia melukai. Lima aturan main ini yang membedakan staf yang DIANGKAT oleh AI dari yang dijatuhkan olehnya:' },
        { t: 'list', items: [
          'RAHASIA TETAP RAHASIA. Data warga, data perusahaan, sandi, dan dokumen internal tidak pernah masuk kotak obrolan. Samarkan, atau jangan pakai AI untuk dokumen itu.',
          'PERIKSA SEBELUM PERCAYA. Fakta, angka, pasal aturan, dan nama dari AI dicek ke sumber resmi. Kalau AI menyebut "menurut peraturan X" — cari peraturan X itu sungguhan.',
          'JUJUR SECUKUPNYA. Memakai AI untuk draf itu wajar dan cerdas — seperti memakai kalkulator. Tapi jangan mengaku menguasai hal yang sebenarnya tidak kamu pahami; saat ditanya atasan, kamu yang harus bisa menjelaskan isinya.',
          'JANGAN UNTUK CURANG. Ujian Lentera, tes kerja, dan tugas yang menilai KEMAMPUANMU dikerjakan sendiri — AI dipakai SEBELUMNYA untuk berlatih, bukan SAAT ujian untuk menyontek. (Ingat: ujian Lentera satu layar penuh, dan pindah jendela tercatat.)',
          'KAMU YANG MEMUTUSKAN. AI memberi pilihan dan draf; menimbang mana yang pantas, sopan, dan benar untuk manusia di depanmu — itu pekerjaanmu, selamanya.',
        ]},
        { t: 'h', text: 'Cara mengenali jawaban yang patut dicurigai' },
        { t: 'list', items: [
          'Terlalu pasti untuk hal yang mestinya bergantung situasi ("gajinya pasti Rp…", "aturannya pasti…").',
          'Menyebut sumber/nomor aturan yang tidak bisa kamu temukan saat dicari.',
          'Angka dan tanggal yang "terlalu rapi". Kalau ragu: tanya ulang "yakin? dari mana sumbernya?", bandingkan ke AI satunya, lalu cek sumber resmi.',
        ]},
        { t: 'tip', text: 'Kalimat penutup modul ini layak ditempel di meja: "AI tidak akan mengambil pekerjaanmu — tapi orang yang pandai memakai AI mungkin iya. Jadilah orang itu."' },
        { t: 'try', text: 'Uji nalar kritismu: tanyakan ke AI sesuatu tentang kampungmu atau kantormu yang KAMU tahu jawabannya. Lihat seberapa percaya diri ia menjawab — benar maupun salah. Itulah pelajaran terakhirnya: kamu pemeriksanya.' },
        { t: 'glossary', items: [
          { term: 'Verifikasi', def: 'Mengecek kebenaran ke sumber resmi sebelum dipakai/disebarkan.' },
          { term: 'Integritas', def: 'Jujur tentang cara kerja dan kemampuanmu — modal karier paling awet.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'AI menyebut "menurut Peraturan Desa No. 7" — sikapmu…',
          options: ['Cari peraturan itu sungguhan sebelum dipakai', 'Langsung kutip di surat resmi', 'Pasti benar karena bernomor', 'Tambahkan nomor lain biar meyakinkan'],
          answer: 0, explain: 'AI bisa mengarang sumber dengan gaya meyakinkan — verifikasi dulu.' },
        { type: 'mc', q: 'Memakai AI yang JUJUR dan cerdas contohnya…',
          options: ['Draf surat dibuat AI, kuperiksa & kupahami, siap kujelaskan ke atasan', 'Menyontek AI saat ujian', 'Mengaku ahli hal yang tak kupahami', 'Menempel data warga ke AI biar cepat'],
          answer: 0, explain: 'Seperti kalkulator: alat bantu sah — selama kamu menguasai isinya.' },
        { type: 'mc', q: 'Saat ujian Lentera atau tes kerja, AI dipakai…',
          options: ['SEBELUMNYA untuk berlatih — saat ujian kerjakan sendiri', 'Diam-diam saat ujian', 'Untuk menjawab semua soal tes kerja', 'Untuk menebak isi ujian besok'],
          answer: 0, explain: 'Ujian mengukur kemampuanmu; lagipula pindah jendela saat ujian tercatat.' },
        { type: 'mc', q: 'Keputusan akhir atas dokumen yang dibantu AI ada di…',
          options: ['Kamu — manusia yang menimbang pantas, sopan, dan benar', 'AI sepenuhnya', 'Tidak ada yang bertanggung jawab', 'Komputer kantor'],
          answer: 0, explain: 'AI memberi pilihan; tanggung jawab dan penilaian tetap milikmu.' },
      ],
    },
  ],

  praktik: null,

  /* ============ UJIAN AKHIR (santai, nilai lulus 80) ============ */
  final: {
    id: 'mb.final',
    pass: 80,
    title: 'Ujian akhir Modul Bonus',
    intro: 'Lima belas soal tentang memakai AI dengan cerdas dan aman. Nilai lulus 80, satu kesempatan jawab per soal — santai saja, modul ini bonus: tidak mempengaruhi Indeks maupun sertifikatmu, murni untuk bekalmu sendiri.',
    questions: [
      { type: 'mc', q: 'Dua AI percakapan yang dibahas modul ini…',
        options: ['ChatGPT dan Gemini', 'Word dan Excel', 'Google dan Yahoo', 'Windows dan Android'],
        answer: 0, explain: 'chatgpt.com dan gemini.google.com — keduanya punya versi gratis.' },
      { type: 'mc', q: 'Hukum besi memakai AI untuk kerja…',
        options: ['AI membantu membuat, manusia wajib memeriksa', 'AI selalu benar', 'AI dilarang total', 'Hasil AI langsung dikirim'],
        answer: 0, explain: 'Pemeriksa dan penanggung jawab terakhir tetap kamu.' },
      { type: 'mc', q: 'Resep prompt PINTA…',
        options: ['Peran, Informasi, Tugas, Aturan hasil', 'Pilih, Instal, Nyalakan, Tutup, Aman', 'Pagi, Istirahat, Nanti, Tunda, Akhir', 'Print, Insert, New, Tab, Alt'],
        answer: 0, explain: 'Empat bahan satu permintaan = jawaban kelas kantoran.' },
      { type: 'mc', q: '"Kamu adalah staf administrasi senior yang teliti…" adalah bahan PINTA yang mana?',
        options: ['Peran', 'Informasi', 'Tugas', 'Aturan hasil'],
        answer: 0, explain: 'Memberi AI jabatan menentukan sudut pandang jawabannya.' },
      { type: 'mc', q: 'Jawaban AI hampir pas tapi pembukanya kepanjangan…',
        options: ['Balas: "perpendek paragraf pembuka, sisanya pertahankan"', 'Mulai dari nol di aplikasi lain', 'Terima apa adanya', 'Tutup laptop'],
        answer: 0, explain: 'Iterasi — memperbaiki bagian demi bagian — gratis dan cepat.' },
      { type: 'mc', q: 'Sebelum AI mengerjakan tugas besar, jurus yang membuat hasil pas…',
        options: ['"Ajukan dulu 3 pertanyaan yang kamu butuhkan"', '"Kerjakan asal cepat"', '"Jangan banyak tanya"', '"Jawab sependek mungkin apa pun tugasnya"'],
        answer: 0, explain: 'AI menggali info yang kurang, seperti staf yang baik.' },
      { type: 'mc', q: 'Data yang AMAN ditempel ke AI…',
        options: ['Draf pengumuman umum tanpa data pribadi', 'Daftar NIK warga', 'Sandi email kantor', 'Nomor rekening bendahara'],
        answer: 0, explain: 'Rahasia tetap rahasia; sensitif disamarkan ("Bapak A", "Rp X").' },
      { type: 'mc', q: 'Pola memakai AI untuk membuat slide laporan…',
        options: ['Minta kerangka judul + butir → pindahkan ke PowerPoint → percantik & periksa', 'AI mengirim langsung ke proyektor', 'Foto layar AI jadi slide', 'Tidak mungkin dibantu AI'],
        answer: 0, explain: 'AI menyiapkan 70% awal; sentuhan akhir jurus M3-mu.' },
      { type: 'mc', q: 'Yang paling sering salah pada draf AI sehingga wajib dicek…',
        options: ['Nama, tanggal, hari, dan angka', 'Ukuran huruf', 'Warna latar', 'Jumlah spasi'],
        answer: 0, explain: 'Halusinasi paling suka bersembunyi di detail "meyakinkan".' },
      { type: 'mc', q: 'Pesan error Excel yang membingungkan bisa…',
        options: ['Difoto/ditempel ke AI lalu ditanya arti & solusinya', 'Hanya bisa ke teknisi', 'Diabaikan selamanya', 'Menular ke HP'],
        answer: 0, explain: 'AI membaca teks dan gambar — error jadi bisa "ditanyakan".' },
      { type: 'mc', q: 'Belajar VLOOKUP terasa sulit. Permintaan terbaik ke AI…',
        options: ['"Jelaskan seperti ke pemula pakai analogi, lalu beri 3 soal latihan dan nilai jawabanku"', '"Kerjakan saja semua tugasku selamanya"', '"Jangan jelaskan apa pun"', '"Beri jawaban tanpa penjelasan"'],
        answer: 0, explain: 'AI = guru pribadi: menjelaskan, melatih, menguji.' },
      { type: 'mc', q: 'Persiapan menghadapi pelanggan yang marah bisa dilatih dengan…',
        options: ['Gladi peran: AI berperan jadi pelanggannya, kamu berlatih menjawab', 'Menghindar selamanya', 'Menghafal satu kalimat sakti', 'Menyuruh AI menemui pelanggan'],
        answer: 0, explain: 'Tempat latihan aman sebelum kejadian sungguhan.' },
      { type: 'mc', q: 'AI menjawab sangat yakin tentang hal yang kamu tahu salah. Pelajarannya…',
        options: ['Percaya diri AI bukan jaminan benar — verifikasi selalu', 'AI tak pernah salah, berarti aku yang salah', 'AI sedang bercanda', 'Komputer perlu diganti'],
        answer: 0, explain: 'Gaya meyakinkan ≠ kebenaran. Kamu pemeriksanya.' },
      { type: 'mc', q: 'Saat ujian Lentera atau tes masuk kerja…',
        options: ['AI untuk berlatih sebelumnya; saat ujian kerjakan sendiri', 'AI dibuka diam-diam di jendela lain', 'AI menjawab semua soal', 'Titip jawab ke AI teman'],
        answer: 0, explain: 'Ujian mengukur kamu — dan pindah jendela saat ujian tercatat.' },
      { type: 'mc', q: 'Kalimat penutup modul ini…',
        options: ['Orang yang pandai memakai AI yang akan unggul — jadilah orang itu', 'AI pasti menggantikan semua orang', 'Jauhi AI selamanya', 'AI hanya untuk orang kota'],
        answer: 0, explain: 'AI tidak mengambil pekerjaanmu; orang yang menguasainya mungkin iya.' },
    ],
  },
}

// 5 bab + ujian akhir = 6 langkah Modul Bonus. Tanpa ujian praktek, tanpa gerbang.
export const MB_ITEMS = ['mb.b1', 'mb.b2', 'mb.b3', 'mb.b4', 'mb.b5', 'mb.final']
