// MODUL 2 — Excel Dasar

export const MODUL2 = {
  id: 'm2',
  title: 'Modul 2 — Excel dasar',
  intro:
    'Excel adalah buku tulis kotak-kotak yang bisa BERHITUNG SENDIRI. Daftar belanja, kas RT, stok barang, rekap absen — semua jadi mudah dan tidak pernah salah jumlah. Di modul ini kamu belajar dari mengenal sel sampai membuat tabel yang menghitung otomatis. Seperti biasa: Lentera di kiri, Excel di kanan, dan praktikkan setiap kotak "Coba sekarang".',
  bab: [
    {
      id: 'm2.b1', no: 1,
      title: 'Kenalan dengan Excel',
      desc: 'Sel, alamat sel, Name Box, dan Formula Bar.',
      blocks: [
        { t: 'p', text: 'Buka Excel dengan jurus yang sama: Start, ketik excel, Enter, pilih Blank workbook/Buku kerja kosong. Yang muncul bukan kertas, tapi kotak-kotak — setiap kotak disebut SEL.' },
        { t: 'img', kind: 'excel', props: {}, caption: 'Jendela Excel: kolom berhuruf (A, B, C…), baris berangka (1, 2, 3…), Name Box di kiri atas, dan Formula Bar di sebelahnya.' },
        { t: 'list', items: [
          'Setiap sel punya ALAMAT: huruf kolom + angka baris. Kotak di kolom B baris 3 = sel B3. Seperti alamat rumah — kombinasi jalan dan nomor.',
          'Name Box (kotak kiri atas) selalu menunjukkan alamat sel yang sedang aktif.',
          'Formula Bar (batang panjang di sebelahnya) menunjukkan ISI ASLI sel itu — angka, tulisan, atau rumus.',
          'Sheet/lembar (tab di bawah, "Sheet1") — satu file Excel bisa berisi banyak lembar, seperti buku berhalaman.',
        ]},
        { t: 'tip', text: 'Tersesat di tengah ribuan kotak? Tekan Ctrl + Home — kamu langsung pulang ke sel A1, pojok kiri atas.' },
        { t: 'try', text: 'Buka Excel baru. Klik beberapa sel sambil perhatikan Name Box berubah. Klik sel C5 — pastikan Name Box menulis C5. Tekan Ctrl + Home untuk pulang ke A1.' },
        { t: 'glossary', items: [
          { term: 'Sel', def: 'Satu kotak di Excel.' },
          { term: 'Alamat sel', def: 'Huruf kolom + angka baris, misalnya B3.' },
          { term: 'Name Box', def: 'Kotak penunjuk alamat sel aktif.' },
          { term: 'Formula Bar', def: 'Batang yang menampilkan isi asli sel.' },
          { term: 'Workbook / Sheet', def: 'Buku kerja / lembar di dalamnya.' },
        ]},
      ],
      quiz: [
        { type: 'hotspot', q: 'Klik NAME BOX — kotak yang menunjukkan alamat sel aktif.',
          img: { kind: 'excel', props: {} }, accept: ['namebox'],
          wrong: { formulabar: 'Itu Formula Bar — menampilkan ISI sel. Name Box kotak kecil di kirinya yang berisi alamat seperti D2.' },
          explain: 'Benar! Name Box selalu memberi tahu kamu sedang berdiri di sel mana.' },
        { type: 'mc', q: 'Kotak yang berada di kolom D baris 2 disebut sel…',
          options: ['2D', 'D2', 'DD2', 'Baris D'],
          answer: 1, explain: 'Huruf dulu, angka belakang: D2.' },
        { type: 'mc', q: 'Tersesat jauh di tengah lembar. Cara cepat kembali ke sel A1…',
          options: ['Ctrl + Home', 'Menutup Excel', 'Klik X', 'Enter berkali-kali'],
          answer: 0, explain: 'Ctrl + Home = pulang ke pojok kiri atas.' },
        { type: 'mc', q: 'Yang menampilkan ISI ASLI sebuah sel (termasuk rumusnya) adalah…',
          options: ['Formula Bar', 'Taskbar', 'Recycle Bin', 'Ribbon File'],
          answer: 0, explain: 'Formula Bar — di layar sel tampak hasilnya, di Formula Bar tampak rumus aslinya.' },
      ],
    },
    {
      id: 'm2.b2', no: 2,
      title: 'Mengisi dan memperbaiki sel',
      desc: 'Mengetik data, berpindah dengan Enter/Tab, dan mengedit dengan F2.',
      blocks: [
        { t: 'p', text: 'Mengisi sel: klik selnya, langsung ketik, lalu tekan Enter (turun ke bawah) atau Tab (geser ke kanan). Pola mengisi tabel: ketik, Tab, ketik, Tab… lalu Enter di ujung — Excel otomatis kembali ke kolom awal baris berikutnya.' },
        { t: 'keys', items: [
          { combo: ['Enter'], label: 'Selesai mengisi, pindah ke sel BAWAH' },
          { combo: ['Tab'], label: 'Selesai mengisi, pindah ke sel KANAN' },
          { combo: ['F2'], label: 'Edit/Sunting isi sel tanpa mengetik ulang' },
          { combo: ['Delete'], label: 'Kosongkan isi sel terpilih' },
          { combo: ['Esc'], label: 'Batalkan ketikan yang belum di-Enter' },
        ]},
        { t: 'warn', text: 'Bahaya pemula: mengklik sel berisi lalu langsung mengetik = isi lama TERTIMPA. Untuk MEMPERBAIKI sebagian (misal salah satu huruf), tekan F2 dulu — kursor masuk ke dalam sel, barulah betulkan. Kalau terlanjur tertimpa: Ctrl + Z.' },
        { t: 'p', text: 'Mengetik angka: cukup angkanya saja — 15000, bukan "Rp 15.000". Titik ribuan dan lambang Rp nanti diurus Excel lewat format (Bab 4). Kalau diketik manual, Excel menganggapnya tulisan dan tidak bisa menghitungnya.' },
        { t: 'try', text: 'Buat tabel kecil: A1 ketik Barang, B1 Harga, C1 Jumlah (pakai Tab untuk geser). Lalu isi 3 baris belanjaan di bawahnya — harga angka polos. Salah ketik? Latih F2 untuk membetulkan.' },
        { t: 'glossary', items: [
          { term: 'F2', def: 'Masuk ke dalam sel untuk menyunting.' },
          { term: 'Tertimpa', def: 'Isi lama terganti karena langsung mengetik.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Memperbaiki SATU HURUF yang salah di dalam sel, tanpa mengetik ulang semuanya…',
          options: ['Klik sel, tekan F2, betulkan', 'Klik sel, langsung ketik', 'Hapus seluruh baris', 'Tutup Excel'],
          answer: 0, wrong: { 1: 'Langsung mengetik akan MENIMPA seluruh isi sel. F2 dulu supaya bisa menyunting.' },
          explain: 'F2 = masuk ke dalam sel. Jurus anti-timpa.' },
        { type: 'mc', q: 'Saat mengisi tabel mendatar, tombol untuk pindah ke sel KANAN…',
          options: ['Tab', 'Enter', 'Esc', 'F12'],
          answer: 0, explain: 'Tab ke kanan, Enter ke bawah.' },
        { type: 'mc', q: 'Cara menulis harga lima belas ribu yang BENAR di sel…',
          options: ['15000', 'Rp 15.000 diketik manual', 'lima belas ribu', '15 ribu'],
          answer: 0, explain: 'Angka polos — lambang Rp dan titik ribuan diurus lewat format sel, supaya tetap bisa dihitung.' },
      ],
    },
    {
      id: 'm2.b3', no: 3,
      title: 'Menyimpan, memilih, dan merapikan kolom',
      desc: 'Ctrl+S untuk .xlsx, memilih sel banyak, dan melebarkan kolom.',
      blocks: [
        { t: 'p', text: 'Menyimpan Excel sama persis dengan Word: Ctrl + S, pilih folder LATIHAN, beri nama jelas. Bedanya hanya akhiran filenya: .xlsx. Refleks Ctrl + S tetap berlaku — data kas yang hilang lebih menyakitkan daripada surat yang hilang.' },
        { t: 'h', text: 'Memilih banyak sel sekaligus' },
        { t: 'list', items: [
          'Drag dari satu sel ke sel lain = blok kotak (range), misalnya A1 sampai C5.',
          'Klik HURUF kolom (misal B) = seluruh kolom terpilih. Klik ANGKA baris = seluruh baris.',
          'Ctrl + A = seluruh tabel.',
        ]},
        { t: 'h', text: 'Kolom sempit dan tanda #####' },
        { t: 'p', text: 'Tulisan terpotong atau muncul ##### artinya kolomnya kurang lebar — datanya TIDAK hilang. Obatnya: arahkan mouse ke garis batas antara dua huruf kolom (misal antara B dan C) sampai panahnya berubah dua arah, lalu DOBEL KLIK — kolom melebar pas sendiri (AutoFit). Bisa juga di-drag manual.' },
        { t: 'try', text: 'Simpan tabel belanjamu sebagai "Belanja Dapur [namamu]" di LATIHAN. Sempitkan kolom B sampai muncul #####, lalu sembuhkan dengan dobel klik di batas kolom. Coba klik huruf B untuk memilih seluruh kolom.' },
        { t: 'glossary', items: [
          { term: '.xlsx', def: 'Akhiran file Excel.' },
          { term: 'Range', def: 'Blok beberapa sel, misal A1 sampai C5.' },
          { term: '#####', def: 'Kolom kurang lebar — data aman, tinggal dilebarkan.' },
          { term: 'AutoFit', def: 'Dobel klik batas kolom — lebar menyesuaikan otomatis.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Sel menampilkan #####. Artinya…',
          options: ['Data rusak dan hilang', 'Kolom kurang lebar — data aman', 'Virus', 'Rumus salah'],
          answer: 1, explain: 'Tinggal lebarkan kolomnya — dobel klik batas huruf kolom.' },
        { type: 'mc', q: 'Cara memilih SELURUH kolom B…',
          options: ['Klik huruf B di kepala kolom', 'Klik sel B1 saja', 'Tekan B di keyboard', 'Ctrl + P'],
          answer: 0, explain: 'Klik hurufnya = seluruh kolom; klik angkanya = seluruh baris.' },
        { type: 'mc', q: 'Melebarkan kolom otomatis pas dengan isinya…',
          options: ['Dobel klik garis batas antar huruf kolom', 'Restart laptop', 'Hapus datanya', 'Ctrl + Z'],
          answer: 0, explain: 'AutoFit — dua klik, beres.' },
        { type: 'mc', q: 'File Excel berakhiran…',
          options: ['.xlsx', '.docx', '.pdf', '.jpg'],
          answer: 0, explain: '.xlsx untuk Excel, .docx untuk Word.' },
      ],
    },
    {
      id: 'm2.b4', no: 4,
      title: 'Merapikan tabel: format angka dan garis',
      desc: 'Format Rupiah, titik ribuan, border, dan menebalkan judul.',
      blocks: [
        { t: 'p', text: 'Angka polos 1500000 sulit dibaca. Format membuatnya jadi Rp 1.500.000 TANPA mengubah nilainya — Excel tetap bisa menghitungnya. Ingat aturan emas yang sama: pilih dulu sel-selnya, baru beri perintah.' },
        { t: 'steps', items: [
          'Pilih sel-sel berisi angka (drag).',
          'Di tab Home, grup Number/Angka, klik panah kecil pemilih format.',
          'Pilih Currency/Mata uang atau Accounting — lambang Rp dan titik ribuan muncul.',
          'Angka di belakang koma tidak perlu? Klik tombol Decrease Decimal (panah mengecilkan desimal) sampai hilang.',
        ]},
        { t: 'h', text: 'Garis tabel (Border)' },
        { t: 'p', text: 'Garis kotak-kotak abu di layar TIDAK ikut tercetak. Supaya tabel bergaris saat dicetak: pilih seluruh tabel, di grup Font klik panah pada tombol Borders/Garis (ikon kotak), pilih All Borders/Semua garis.' },
        { t: 'list', items: [
          'Judul kolom (baris pertama) layak ditebalkan: pilih barisnya, Ctrl + B.',
          'Rata tengahkan judul kolom dengan tombol Center — sama seperti di Word.',
          'Warnai tipis baris judul dengan Fill Color/Warna isian (ikon ember cat) bila perlu — secukupnya, jangan pelangi.',
        ]},
        { t: 'try', text: 'Rapikan tabel belanjamu: kolom harga diformat Rupiah tanpa desimal, seluruh tabel diberi All Borders, baris judul ditebalkan dan dirata-tengah. Ctrl + S.' },
        { t: 'glossary', items: [
          { term: 'Format angka', def: 'Cara angka ditampilkan (Rp, titik ribuan) tanpa mengubah nilainya.' },
          { term: 'Border', def: 'Garis tabel yang ikut tercetak.' },
          { term: 'Fill Color', def: 'Warna isian sel.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Mengubah 1500000 menjadi tampil "Rp 1.500.000" yang BENAR…',
          options: ['Pilih selnya, beri format Currency/Accounting', 'Ketik ulang manual dengan huruf Rp', 'Tambah tanda kutip', 'Tidak bisa'],
          answer: 0, wrong: { 1: 'Rp yang diketik manual membuat sel jadi TULISAN — tidak bisa dihitung lagi.' },
          explain: 'Format mengubah tampilan, nilai tetap angka yang bisa dihitung.' },
        { type: 'mc', q: 'Garis kotak abu-abu di layar Excel…',
          options: ['Otomatis ikut tercetak', 'TIDAK ikut tercetak — perlu Borders/All Borders', 'Hanya muncul kalau dicetak', 'Tanda error'],
          answer: 1, explain: 'Garis layar cuma pemandu. Tabel cetak butuh All Borders.' },
        { type: 'mc', q: 'Supaya judul kolom menonjol, kebiasaan yang rapi adalah…',
          options: ['Ditebalkan (Ctrl + B) dan rata tengah', 'Diberi 10 warna', 'Dibiarkan saja', 'Dihapus'],
          answer: 0, explain: 'Tebal + tengah — sederhana dan profesional.' },
      ],
    },
    {
      id: 'm2.b5', no: 5,
      title: 'Rumus pertamamu',
      desc: 'Tanda =, klik sel, dan keajaiban hitung-ulang otomatis.',
      blocks: [
        { t: 'p', text: 'Inilah jantung Excel. Semua rumus diawali tanda sama dengan (=). Ketik =3+4 di sel mana pun, Enter — muncul 7. Tapi kekuatan sebenarnya: rumus yang menunjuk SEL LAIN.' },
        { t: 'img', kind: 'excel', props: { highlight: ['cell', 'formulabar'] }, caption: 'Sel D2 berisi rumus =B2*C2: harga dikali jumlah. Di layar tampak hasilnya; rumus aslinya terlihat di Formula Bar.' },
        { t: 'steps', items: [
          'Klik sel D2 (kolom Total, baris pertama belanjaan).',
          'Ketik = lalu KLIK sel B2 (harga) — alamatnya masuk sendiri ke rumus.',
          'Ketik * (tanda kali), lalu klik sel C2 (jumlah).',
          'Enter. Total muncul. Lihat Formula Bar: isinya =B2*C2.',
        ]},
        { t: 'list', items: [
          'Tanda hitung: + tambah, - kurang, * kali, / bagi.',
          'Keajaiban: ubah angka di B2, dan D2 MENGHITUNG ULANG SENDIRI. Inilah alasan Excel mengalahkan kalkulator.',
          'Menyalin rumus ke bawah: klik sel rumus, arahkan ke kotak kecil di pojok kanan bawah sel (fill handle), drag ke bawah — rumus menyesuaikan barisnya sendiri (=B3*C3, =B4*C4, …).',
        ]},
        { t: 'warn', text: 'Lupa tanda = di depan? Excel menganggapnya tulisan biasa dan tidak menghitung. "B2*C2" tampil apa adanya; "=B2*C2" baru bekerja.' },
        { t: 'try', text: 'Tambahkan kolom Total pada tabel belanjamu. Buat rumus =harga*jumlah di baris pertama, lalu tarik fill handle ke bawah untuk semua baris. Ubah salah satu harga — saksikan total berubah sendiri.' },
        { t: 'glossary', items: [
          { term: 'Rumus', def: 'Perintah hitung yang diawali tanda =.' },
          { term: 'Fill handle', def: 'Kotak kecil di pojok sel untuk menyalin rumus dengan drag.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Setiap rumus Excel selalu diawali…',
          options: ['Tanda = (sama dengan)', 'Tanda Rp', 'Huruf kapital', 'Spasi'],
          answer: 0, explain: 'Tanpa =, Excel menganggapnya tulisan biasa.' },
        { type: 'hotspot', q: 'Klik bagian yang menampilkan RUMUS ASLI sel yang sedang aktif.',
          img: { kind: 'excel', props: {} }, accept: ['formulabar'],
          wrong: { cell: 'Di sel tampak HASILNYA. Rumus aslinya tampil di batang panjang atas.', namebox: 'Itu Name Box — alamat sel. Rumus ada di batang panjang sebelahnya.' },
          explain: 'Benar — Formula Bar, jendela kejujuran setiap sel.' },
        { type: 'mc', q: 'Rumus total harga (harga di B2, jumlah di C2)…',
          options: ['=B2*C2', 'B2*C2', '=B2+C2 selalu', 'Rp B2*C2'],
          answer: 0, explain: 'Diawali =, memakai * untuk kali.' },
        { type: 'mc', q: 'Angka di B2 diubah. Sel D2 yang berisi =B2*C2 akan…',
          options: ['Menghitung ulang otomatis', 'Tetap angka lama', 'Menjadi error', 'Terhapus'],
          answer: 0, explain: 'Hitung-ulang otomatis — keajaiban utama Excel.' },
      ],
    },
    {
      id: 'm2.b6', no: 6,
      title: 'SUM dan AVERAGE — menjumlah satu kolom sekali tekan',
      desc: 'Fungsi siap pakai dan tombol AutoSum.',
      blocks: [
        { t: 'p', text: 'Menjumlahkan 50 baris dengan =D2+D3+D4+… akan membuatmu tua di jalan. Excel punya FUNGSI siap pakai: =SUM(D2:D6) artinya "jumlahkan D2 sampai D6". Titik dua dibaca "sampai".' },
        { t: 'keys', items: [
          { combo: ['Alt', '='], label: 'AutoSum — Excel menebak dan memasang =SUM sendiri' },
        ]},
        { t: 'img', kind: 'excel', props: { highlight: ['autosum'] }, caption: 'Tombol AutoSum (lambang \u03a3) — klik di sel kosong di bawah deretan angka, Excel langsung menjumlahkan.' },
        { t: 'list', items: [
          '=SUM(D2:D6) — jumlah. Cara malas yang pintar: klik sel kosong di bawah kolom angka, klik \u03a3 AutoSum (atau Alt + =), Enter.',
          '=AVERAGE(D2:D6) — rata-rata. Pola sama: =AVERAGE( lalu drag selnya, tutup kurung, Enter.',
          '=MAX(...) nilai terbesar, =MIN(...) terkecil — bonus yang sering berguna.',
        ]},
        { t: 'tip', text: 'Cara aman menulis range: ketik =SUM( lalu DRAG sel-sel yang mau dijumlah dengan mouse — alamat masuk sendiri tanpa salah ketik — lalu tutup kurung dan Enter.' },
        { t: 'try', text: 'Di bawah kolom Total belanjamu: pakai AutoSum untuk jumlah seluruh belanja. Di sel sebelahnya, buat =AVERAGE untuk rata-rata harga. Tulis label "TOTAL" dan "RATA-RATA" di sel kirinya supaya jelas.' },
        { t: 'glossary', items: [
          { term: 'Fungsi', def: 'Rumus siap pakai: SUM, AVERAGE, MAX, MIN.' },
          { term: 'D2:D6', def: 'Range — dibaca "D2 sampai D6".' },
          { term: 'AutoSum', def: 'Tombol \u03a3 pemasang SUM otomatis (Alt + =).' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Menjumlahkan isi sel D2 sampai D6…',
          options: ['=SUM(D2:D6)', '=D2:D6', 'SUM D2-D6', '=JUMLAH(D2;D6) selalu'],
          answer: 0, explain: 'SUM dengan range bertitik-dua: dari-sampai.' },
        { type: 'hotspot', q: 'Klik tombol untuk MENJUMLAH OTOMATIS deretan angka.',
          img: { kind: 'excel', props: {} }, accept: ['autosum'],
          explain: 'Benar — \u03a3 AutoSum, atau tekan Alt + =.' },
        { type: 'mc', q: 'Mencari RATA-RATA nilai di B2 sampai B10…',
          options: ['=AVERAGE(B2:B10)', '=SUM saja', '=RATA(B2:B10)', 'Dihitung kalkulator lalu diketik'],
          answer: 0, explain: 'AVERAGE = rata-rata.' },
        { type: 'mc', q: 'Arti titik dua pada D2:D6…',
          options: ['"sampai" — D2 sampai D6', 'Dibagi', 'Dikali', 'Salah ketik'],
          answer: 0, explain: 'Range dari-sampai.' },
      ],
    },
    {
      id: 'm2.b7', no: 7,
      title: 'Mengurutkan dan menyaring data',
      desc: 'Sort A-Z dan Filter — menemukan apa pun dalam sekejap.',
      blocks: [
        { t: 'p', text: 'Data 100 baris baru terasa berguna kalau bisa diatur: urutkan dari termahal, tampilkan hanya barang tertentu. Dua jurusnya: Sort/Urutkan dan Filter/Saring.' },
        { t: 'steps', items: [
          'Klik satu sel mana pun DI DALAM tabel (jangan blok sebagian — nanti urutannya tercerai dari barisnya).',
          'Tab Data, klik Sort A to Z (urut naik) atau Z to A (urut turun) — atau lewat tombol Sort & Filter di tab Home.',
          'Untuk menyaring: klik Filter — muncul panah kecil di setiap judul kolom.',
          'Klik panah di kolom yang diinginkan, centang hanya nilai yang mau ditampilkan, OK.',
        ]},
        { t: 'warn', text: 'Filter MENYEMBUNYIKAN baris, bukan menghapus. Nomor baris yang meloncat (1, 2, 7, 9) adalah tandanya. Mengembalikan semua: klik panah filter, pilih Clear Filter/Hapus saringan — atau matikan tombol Filter.' },
        { t: 'try', text: 'Di tabel belanjamu: urutkan dari harga termahal (Z to A pada kolom harga). Nyalakan Filter, tampilkan hanya satu barang, lalu hapus saringannya lagi.' },
        { t: 'glossary', items: [
          { term: 'Sort', def: 'Urutkan — A ke Z (naik) atau Z ke A (turun).' },
          { term: 'Filter', def: 'Saring — menampilkan baris tertentu saja, sisanya disembunyikan.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Setelah memakai Filter, baris yang tidak lolos saringan akan…',
          options: ['Terhapus permanen', 'Disembunyikan sementara — bisa dimunculkan lagi', 'Pindah ke Sheet lain', 'Berubah warna merah'],
          answer: 1, explain: 'Filter hanya menyembunyikan. Clear Filter mengembalikan semuanya.' },
        { type: 'mc', q: 'Mengurutkan tabel dari harga TERMAHAL memakai…',
          options: ['Sort Z to A pada kolom harga', 'Sort A to Z', 'Menghapus harga murah', 'Ctrl + P'],
          answer: 0, explain: 'Z to A = besar ke kecil.' },
        { type: 'mc', q: 'Sebelum menekan Sort, posisi yang benar…',
          options: ['Klik satu sel di dalam tabel', 'Blok satu kolom saja', 'Klik di luar tabel', 'Tutup file dulu'],
          answer: 0, wrong: { 1: 'Memblok satu kolom saja bisa membuat kolom itu terurut SENDIRIAN — barisnya tercerai dari data lain.' },
          explain: 'Satu sel di dalam tabel — Excel mengurutkan seluruh baris bersama-sama.' },
      ],
    },
    {
      id: 'm2.b8', no: 8,
      title: 'Mencetak lembar Excel dengan rapi',
      desc: 'Pratinjau, orientasi, dan jurus muat-satu-halaman.',
      blocks: [
        { t: 'p', text: 'Mencetak Excel sedikit lebih licik daripada Word: tabel yang lebar suka terpotong dan tercecer ke halaman dua. Kuncinya tetap sama — Ctrl + P dan PERIKSA PRATINJAU.' },
        { t: 'steps', items: [
          'Tekan Ctrl + P. Lihat pratinjau: apakah semua kolom masuk?',
          'Tabel melebar? Ganti orientasi: Portrait/Tegak menjadi Landscape/Mendatar.',
          'Masih terpotong? Di bagian bawah Settings, ganti "No Scaling" menjadi "Fit Sheet on One Page/Muat satu halaman".',
          'Klik Print/Cetak — atau pilih Microsoft Print to PDF untuk dikirim lewat WA.',
        ]},
        { t: 'tip', text: 'Hanya ingin mencetak sebagian tabel? Blok dulu bagiannya, lalu di layar Ctrl + P ubah "Print Active Sheets" menjadi "Print Selection/Cetak yang dipilih".' },
        { t: 'try', text: 'Ctrl + P pada tabel belanjamu. Coba ganti ke Landscape, lalu Fit Sheet on One Page, perhatikan pratinjau berubah. Simpan sebagai PDF ke folder LATIHAN.' },
        { t: 'glossary', items: [
          { term: 'Portrait / Landscape', def: 'Tegak / mendatar — arah kertas.' },
          { term: 'Fit on One Page', def: 'Mengecilkan otomatis supaya muat satu halaman.' },
          { term: 'Print Selection', def: 'Mencetak hanya bagian yang diblok.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Tabel lebar terpotong saat dicetak. Dua obat utamanya…',
          options: ['Landscape dan Fit Sheet on One Page', 'Hapus kolomnya', 'Cetak dua kali', 'Perbesar hurufnya'],
          answer: 0, explain: 'Putar kertas mendatar, atau minta Excel memuat-muatkan ke satu halaman.' },
        { type: 'mc', q: 'Sebelum menekan Print/Cetak, pekerja teliti selalu…',
          options: ['Memeriksa pratinjau', 'Mematikan printer', 'Menghapus filter', 'Restart laptop'],
          answer: 0, explain: 'Pratinjau dulu — kebiasaan yang sama dari Word.' },
        { type: 'mc', q: 'Mencetak HANYA bagian tabel yang diblok…',
          options: ['Print Selection', 'Print All', 'Print to PDF', 'Fit on One Page'],
          answer: 0, explain: 'Selection = yang dipilih saja.' },
      ],
    },
  ],

  praktik: {
    id: 'm2.praktik',
    title: 'Ujian praktek — Daftar Belanja Dapur',
    pass: 80,
    ext: ['xlsx'],
    brief: [
      'Buka Excel, buat buku kerja baru.',
      'Baris 1: judul kolom — minimal Barang, Harga, Jumlah, Total (boleh tambah).',
      'Isi minimal 5 baris belanjaan dengan harga dan jumlah berupa ANGKA polos.',
      'Kolom Total memakai rumus perkalian harga \u00d7 jumlah (contoh =B2*C2), disalin ke semua baris.',
      'Di bawah kolom Total, buat jumlah keseluruhan memakai =SUM(...) atau tombol AutoSum.',
      'Simpan sebagai .xlsx dengan nama jelas, lalu unggah di sini.',
    ],
    rubric: [
      { id: 'xlsx-valid', label: 'File Excel (.xlsx) terbaca dengan baik' },
      { id: 'header-3', label: 'Baris 1 berisi judul kolom (minimal 3 kolom)' },
      { id: 'baris-5', label: 'Ada minimal 5 baris data' },
      { id: 'ada-angka', label: 'Ada data angka (bukan semua tulisan)' },
      { id: 'ada-kali', label: 'Ada rumus perkalian (harga \u00d7 jumlah)' },
      { id: 'ada-sum', label: 'Ada rumus =SUM(...) untuk jumlah keseluruhan' },
    ],
  },

  final: {
    id: 'm2.final',
    pass: 85,
    title: 'Ujian akhir Modul 2',
    intro: 'Lima belas soal dari semua bab Excel dasar. Satu kesempatan jawab per soal, nilai lulus 85. Belum lulus? Pelajari pembahasan, ulangi — soal diacak ulang.',
    questions: [
      { type: 'mc', q: 'Kotak di kolom C baris 4 disebut sel…', options: ['C4', '4C', 'CC4', 'Kolom 4'], answer: 0, explain: 'Huruf dulu, angka belakang.' },
      { type: 'hotspot', q: 'Klik bagian yang menampilkan rumus asli sel aktif.', img: { kind: 'excel', props: {} }, accept: ['formulabar'], explain: 'Formula Bar — jendela kejujuran sel.' },
      { type: 'mc', q: 'Pulang cepat ke sel A1…', options: ['Ctrl + Home', 'Esc', 'Ctrl + P', 'Tab'], answer: 0, explain: 'Ctrl + Home = pojok kiri atas.' },
      { type: 'mc', q: 'Memperbaiki sebagian isi sel tanpa menimpa…', options: ['F2', 'Langsung ketik', 'Delete', 'F12'], answer: 0, explain: 'F2 masuk ke dalam sel.' },
      { type: 'mc', q: 'Tanda ##### pada sel berarti…', options: ['Kolom kurang lebar', 'Data terhapus', 'Rumus salah', 'File rusak'], answer: 0, explain: 'Lebarkan kolomnya — data aman.' },
      { type: 'mc', q: 'Menulis lima puluh ribu agar bisa dihitung…', options: ['50000', 'Rp 50.000 manual', 'lima puluh ribu', '50 rb'], answer: 0, explain: 'Angka polos; Rp lewat format.' },
      { type: 'mc', q: 'Format Rupiah yang benar diberikan lewat…', options: ['Format Currency/Accounting', 'Mengetik Rp manual', 'Mengganti font', 'Border'], answer: 0, explain: 'Format menjaga angka tetap bisa dihitung.' },
      { type: 'mc', q: 'Supaya garis tabel ikut tercetak…', options: ['Borders, All Borders', 'Garis layar otomatis tercetak', 'Print dua kali', 'Fill Color'], answer: 0, explain: 'Garis abu layar tidak tercetak.' },
      { type: 'mc', q: 'Rumus total (harga B3, jumlah C3)…', options: ['=B3*C3', 'B3*C3', '=B3:C3', '=SUM saja'], answer: 0, explain: 'Diawali =, tanda * untuk kali.' },
      { type: 'mc', q: 'Harga di B3 diubah; sel berisi =B3*C3 akan…', options: ['Menghitung ulang sendiri', 'Tetap', 'Error', 'Kosong'], answer: 0, explain: 'Hitung-ulang otomatis.' },
      { type: 'mc', q: 'Menjumlahkan D2 sampai D9…', options: ['=SUM(D2:D9)', '=D2+D9', '=SUM(D2-D9)', 'D2:D9'], answer: 0, explain: 'Titik dua dibaca "sampai".' },
      { type: 'hotspot', q: 'Klik tombol penjumlah otomatis.', img: { kind: 'excel', props: {} }, accept: ['autosum'], explain: '\u03a3 AutoSum — atau Alt + =.' },
      { type: 'mc', q: 'Rata-rata nilai B2:B8…', options: ['=AVERAGE(B2:B8)', '=SUM/8 selalu', '=MAX(B2:B8)', '=RATA2'], answer: 0, explain: 'AVERAGE = rata-rata.' },
      { type: 'mc', q: 'Setelah Filter, baris yang tak lolos…', options: ['Disembunyikan, bisa kembali', 'Terhapus', 'Pindah sheet', 'Tercetak saja'], answer: 0, explain: 'Clear Filter mengembalikan semuanya.' },
      { type: 'mc', q: 'Tabel lebar terpotong saat cetak; obatnya…', options: ['Landscape / Fit Sheet on One Page', 'Hapus data', 'Print dua kali', 'Kecilkan layar'], answer: 0, explain: 'Putar mendatar atau muat-satukan halaman.' },
    ],
  },
}

export const M2_ITEMS = ['m2.b1','m2.b2','m2.b3','m2.b4','m2.b5','m2.b6','m2.b7','m2.b8','m2.praktik','m2.final']
