// MODUL 5 — Simulasi Satu Hari Kerja (capstone jenjang menengah)
// Aturan bahasa Lentera: label yang TERTULIS di layar selalu disebut dwibahasa.
// Modul ini berbentuk SKENARIO: kamu menjalani satu hari sebagai staf admin.

export const MODUL5 = {
  id: 'm5',
  title: 'Modul 5 — Simulasi satu hari kerja',
  intro:
    'Hari pertama kerja sungguhan dimulai. Modul penutup ini bukan kumpulan tombol baru — ini GLADI BERSIH: kamu menjalani satu hari sebagai staf admin, pagi sampai sore, memakai SEMUA bekal Modul 0–4 dalam alur kerja nyata. Di tengah jalan kamu juga naik kelas: dua jurus jenjang menengah yang paling dicari kantor — Mail Merge (surat massal) dan VLOOKUP (pencari data otomatis). Selesaikan harinya, tulis laporan harianmu, dan kamu bukan lagi "bisa komputer" — kamu SIAP BEKERJA.',
  bab: [
    /* ============ BABAK 1 ============ */
    {
      id: 'm5.b1', no: 1,
      title: 'Pagi: buka hari dengan email',
      desc: 'Skenario pagi — memeriksa kotak masuk, memilah, dan merencanakan kerja.',
      blocks: [
        { t: 'p', text: 'Pukul 08.00. Kamu duduk, menyalakan laptop, masuk dengan sandi. Kebiasaan staf yang baik: hal PERTAMA yang dibuka adalah email — di sanalah tugas hari ini menunggu. Hari ini ada tiga email masuk; mari kita pilah seperti orang berpengalaman.' },
        { t: 'list', items: [
          'Email 1 — dari Bu Ratna (atasan), perihal "Tugas hari ini": minta SURAT UNDANGAN rapat untuk 5 ketua RT, REKAP biaya kegiatan, dan SLIDE laporan singkat. Dikumpulkan sore ini. Inilah pekerjaan utamamu.',
          'Email 2 — dari rekan kerja, perihal kosong, isi "tolong cek lampiran" dengan file aneh berakhiran .apk. Ingat Modul 4: lampiran mencurigakan JANGAN dibuka — tanyakan dulu langsung ke orangnya.',
          'Email 3 — "Selamat! Anda memenangkan undian 100 juta, klik di sini". Kamu tersenyum: phishing klasik. Hapus.',
        ]},
        { t: 'h', text: 'Membalas dengan benar' },
        { t: 'p', text: 'Email Bu Ratna dikirim juga ke dua staf lain. Jawabanmu ("Siap, Bu — saya kerjakan, selesai sebelum jam 4") cukup untuk Bu Ratna saja: tekan Reply/Balas, BUKAN Reply All — dua rekanmu tidak perlu menerima janjimu. Lalu siapkan medan kerja: buat folder baru Documents > Rapat RT (Modul 0), tempat semua file hari ini akan tinggal rapi.' },
        { t: 'tip', text: 'Staf yang tenang membaca SEMUA permintaan dulu, baru bekerja: tiga keluaran hari ini — surat (Word), rekap (Excel), slide (PowerPoint). Satu folder, tiga file, nama jelas.' },
        { t: 'try', text: 'Lakukan sungguhan: buat folder "Rapat RT" di Documents. Balas (Reply) sebuah email di kotak masukmu dengan satu kalimat konfirmasi yang sopan.' },
        { t: 'glossary', items: [
          { term: 'Memilah email', def: 'Membedakan tugas asli, pertanyaan, dan penipuan sebelum bertindak.' },
          { term: 'Folder kerja', def: 'Satu folder per urusan — rumah semua file tugas itu.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Email atasan dikirim ke kamu + 2 rekan. Jawaban "siap saya kerjakan" dikirim lewat…',
          options: ['Reply/Balas — cukup ke atasan', 'Reply All — biar semua tahu', 'Forward ke rekan', 'Email baru ke semua'],
          answer: 0, explain: 'Janji kerjamu urusan kamu dan atasan; jangan penuhi kotak masuk orang.' },
        { type: 'mc', q: 'Lampiran .apk dari rekan dengan perihal kosong…',
          options: ['Jangan dibuka — konfirmasi dulu langsung ke orangnya', 'Buka, kan dari rekan sendiri', 'Teruskan ke grup', 'Instal di laptop kantor'],
          answer: 0, explain: 'Akun rekan bisa dibajak; file .apk di laptop = bendera merah.' },
        { type: 'mc', q: 'Langkah pertama yang rapi sebelum mengerjakan tiga file tugas…',
          options: ['Buat satu folder kerja khusus untuk tugas ini', 'Langsung ketik di mana saja', 'Simpan semua di Desktop acak', 'Kerjakan di HP'],
          answer: 0, explain: 'Documents > Rapat RT — semua keluaran hari ini tinggal di satu rumah.' },
        { type: 'mc', q: '"Selamat! Anda menang undian, klik segera!" — tindakanmu…',
          options: ['Hapus — phishing klasik berciri hadiah + buru-buru', 'Klik, siapa tahu benar', 'Balas minta bukti', 'Kirim data diri'],
          answer: 0, explain: 'Hadiah tak diminta + tekanan waktu = penipuan, selalu.' },
      ],
    },

    /* ============ BABAK 2 ============ */
    {
      id: 'm5.b2', no: 2,
      title: 'Naik kelas: Mail Merge — satu surat untuk banyak nama',
      desc: 'Membuat 5 surat undangan sekaligus dari satu naskah + satu daftar Excel.',
      blocks: [
        { t: 'p', text: 'Tugas pertama: surat undangan untuk 5 ketua RT. Cara pemula: ketik satu surat, ganti nama, simpan, ganti lagi… lima kali. Cara kantoran: MAIL MERGE — Word menggandakan satu naskah dan MENGISI SENDIRI nama-namanya dari daftar Excel. Lima nama atau lima ratus nama, kerjanya sama sebentar.' },
        { t: 'h', text: 'Bahan 1: daftar nama di Excel' },
        { t: 'steps', items: [
          'Buka Excel, buat tabel kecil: A1 ketik Nama, B1 ketik RT.',
          'Isi 5 baris: nama ketua RT dan nomor RT-nya (data latihan boleh karangan).',
          'Simpan di folder Rapat RT dengan nama "Daftar Ketua RT.xlsx". Tutup Excel — Word akan meminjam file ini.',
        ]},
        { t: 'h', text: 'Bahan 2: naskah surat + jurus merge' },
        { t: 'steps', items: [
          'Di Word, tulis surat undanganmu seperti biasa (Modul 1) — tapi kosongkan bagian nama.',
          'Klik tab Mailings/Surat-menyurat → "Select Recipients/Pilih penerima" → "Use an Existing List/Gunakan daftar yang ada" → pilih file Excel tadi.',
          'Letakkan kursor di tempat nama → klik "Insert Merge Field/Sisipkan bidang gabungan" → pilih Nama. Muncul tulisan «Nama» — itu kotak ajaibnya. Lakukan juga untuk «RT».',
          'Klik "Preview Results/Pratinjau hasil" — «Nama» berubah jadi nama sungguhan; panah ◀▶ berpindah orang.',
          'Klik "Finish & Merge/Selesai & gabung" → "Edit Individual Documents/Edit dokumen satu per satu" → All. Word melahirkan dokumen baru berisi 5 surat — satu per ketua RT.',
        ]},
        { t: 'warn', text: 'Tulisan «Nama» berkurung ganda HARUS lahir dari tombol Insert Merge Field. Mengetik tanda « » manual tidak akan tersambung ke Excel — itulah kesalahan mail merge nomor satu.' },
        { t: 'tip', text: 'Mail merge dipakai kantor untuk: undangan, surat tugas, slip honor, label amplop. Sekali paham, kamu menghemat berjam-jam setiap bulan.' },
        { t: 'try', text: 'Jalankan utuh: buat Daftar Ketua RT.xlsx (5 baris), lalu surat undangan ber-«Nama» dan «RT», pratinjau, dan Finish & Merge. Hitung: 5 surat jadi, sekali ketik. Simpan hasil gabungannya di folder Rapat RT.' },
        { t: 'glossary', items: [
          { term: 'Mail Merge', def: 'Menggabungkan satu naskah Word dengan daftar data — lahir banyak surat sekaligus.' },
          { term: 'Merge field («Nama»)', def: 'Kotak isian otomatis yang mengambil isi dari kolom Excel.' },
          { term: 'Recipients', def: 'Daftar penerima — biasanya file Excel.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Membuat 50 surat undangan yang isinya sama tapi namanya beda-beda, paling cepat dengan…',
          options: ['Mail Merge — satu naskah + daftar Excel', 'Mengetik 50 kali', 'Salin-tempel lalu ganti nama manual 50 kali', 'Tulis tangan'],
          answer: 0, explain: 'Word menggandakan dan mengisi nama otomatis dari daftar.' },
        { type: 'mc', q: 'Daftar nama untuk mail merge paling lazim disimpan sebagai…',
          options: ['Tabel Excel (kolom Nama, dst.)', 'Foto daftar hadir', 'Catatan di HP', 'Slide PowerPoint'],
          answer: 0, explain: 'Baris 1 = nama kolom; tiap baris = satu penerima.' },
        { type: 'mc', q: 'Tulisan «Nama» di naskah merge harus dibuat lewat…',
          options: ['Tombol Insert Merge Field', 'Mengetik tanda « » sendiri', 'Salin dari internet', 'Tombol Bold'],
          answer: 0, explain: 'Hanya field asli yang tersambung ke kolom Excel.' },
        { type: 'mc', q: 'Tombol untuk melihat nama sungguhan menggantikan «Nama» sebelum digabung…',
          options: ['Preview Results/Pratinjau hasil', 'Print', 'Save As', 'New Slide'],
          answer: 0, explain: 'Selalu pratinjau dulu — salah kolom ketahuan sebelum 50 surat lahir.' },
      ],
    },

    /* ============ BABAK 3 ============ */
    {
      id: 'm5.b3', no: 3,
      title: 'Naik kelas: VLOOKUP — Excel yang mencari sendiri',
      desc: 'Rekap biaya kegiatan: mengambil harga dari daftar induk secara otomatis, plus IF.',
      blocks: [
        { t: 'p', text: 'Tugas kedua: rekap biaya. Kantormu punya DAFTAR HARGA induk (sewa kursi, snack, spanduk). Saat membuat rekap, pemula menengok daftar itu lalu mengetik ulang harganya — bisa salah ketik, dan kalau harga induk berubah, rekapmu basi. Jurus menengahnya: VLOOKUP — rumus yang MENCARI sendiri ke daftar induk dan mengambil nilainya.' },
        { t: 'h', text: 'Cara membaca VLOOKUP' },
        { t: 'p', text: '=VLOOKUP(A2; Daftar!A:B; 2; FALSE) artinya: "cari isi sel A2 (misal kata Snack) di kolom pertama daftar induk, lalu ambilkan isi KOLOM KE-2 barisnya (harganya), dan harus persis sama (FALSE)". Empat isian itu saja: apa yang dicari; di mana mencarinya; kolom ke berapa yang diambil; persis atau tidak. Catatan kecil: tergantung pengaturan laptop, pemisahnya koma (,) atau titik-koma (;) — kalau satu ditolak Excel, pakai yang satunya.' },
        { t: 'steps', items: [
          'Sheet1 beri nama "Daftar": tabel induk — A: nama barang, B: harga (5 baris).',
          'Sheet2 "Rekap": kolom A barang yang dipakai hari ini, kolom B jumlah.',
          'Di C2 (harga satuan): =VLOOKUP(A2; Daftar!A:B; 2; FALSE) lalu Enter — harga muncul sendiri.',
          'D2 total: =B2*C2 (jurus lama Modul 2). Salin keduanya ke bawah dengan fill handle.',
          'Baris terakhir: =SUM(...) untuk total keseluruhan. Format Rupiah. Rekap selesai.',
        ]},
        { t: 'h', text: 'Bonus 30 detik: IF — sel yang bisa menilai' },
        { t: 'p', text: '=IF(D8>1000000; "Perlu persetujuan"; "Aman") artinya: JIKA total melebihi sejuta, tulis "Perlu persetujuan", selain itu tulis "Aman". IF membuat tabelmu berbicara — dipakai untuk status lunas/belum, lulus/ulang, aman/lewat batas.' },
        { t: 'warn', text: 'Hasil #N/A pada VLOOKUP artinya "tidak ketemu" — hampir selalu karena ejaan beda ("Snack" vs "Snak") atau ada spasi nyasar. Samakan ejaannya, bukan rumusnya yang salah.' },
        { t: 'try', text: 'Bangun rekap dua-sheet di atas dengan data karanganmu: 5 barang di Daftar, 4 barang terpakai di Rekap, VLOOKUP harga, total per baris, SUM, format Rp, dan satu sel IF status. Simpan "Rekap Biaya.xlsx" di folder Rapat RT.' },
        { t: 'glossary', items: [
          { term: 'VLOOKUP', def: 'Rumus pencari: ambil nilai dari tabel lain berdasarkan kata kunci.' },
          { term: '#N/A', def: 'Tanda "tidak ketemu" — biasanya ejaan kunci tidak sama persis.' },
          { term: 'IF', def: 'Rumus penilai: JIKA syarat terpenuhi tulis ini, kalau tidak tulis itu.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Mengambil harga dari daftar induk secara otomatis berdasarkan nama barang…',
          options: ['=VLOOKUP(...)', '=SUM(...)', 'Mengetik ulang sambil menengok', '=AVERAGE(...)'],
          answer: 0, explain: 'VLOOKUP mencari kuncinya dan mengambilkan nilai kolom yang diminta.' },
        { type: 'mc', q: 'Angka "2" pada =VLOOKUP(A2; Daftar!A:B; 2; FALSE) artinya…',
          options: ['Ambil isi kolom ke-2 dari daftar (harganya)', 'Cari dua kali', 'Hanya dua baris teratas', 'Bagi dua hasilnya'],
          answer: 0, explain: 'Nomor kolom yang nilainya diambilkan.' },
        { type: 'mc', q: 'VLOOKUP menghasilkan #N/A. Penyebab tersering…',
          options: ['Ejaan kata kunci tidak sama persis dengan daftar', 'Excel rusak', 'Komputer kurang cepat', 'File terlalu besar'],
          answer: 0, explain: '"Snack" ≠ "Snak " — samakan ejaan, hilangkan spasi nyasar.' },
        { type: 'mc', q: '=IF(D8>1000000; "Perlu persetujuan"; "Aman") akan menulis "Aman" bila…',
          options: ['Isi D8 satu juta ke bawah', 'Isi D8 di atas satu juta', 'Selalu', 'Tidak pernah'],
          answer: 0, explain: 'Syarat tak terpenuhi → IF menulis pilihan keduanya.' },
      ],
    },

    /* ============ BABAK 4 ============ */
    {
      id: 'm5.b4', no: 4,
      title: 'Siang: slide laporan & ritme kerja',
      desc: 'Merangkum hasil pagi menjadi slide singkat, dengan ritme kerja yang sehat.',
      blocks: [
        { t: 'p', text: 'Pukul 13.00, dua tugas beres. Tinggal slide laporan singkat untuk Bu Ratna. Ini panen Modul 3 — dan kesempatan melatih ritme kerja: satu tugas selesai TUNTAS (simpan, rapikan, taruh di folder), baru pindah ke tugas berikutnya. Setengah-setengah di tiga tugas = nol tugas selesai.' },
        { t: 'steps', items: [
          'PowerPoint baru, tema sederhana. Slide 1: "Laporan Persiapan Rapat RT" + namamu.',
          'Slide 2 "Surat undangan": 3 butir — 5 surat selesai via mail merge · daftar penerima tersimpan · siap cetak.',
          'Slide 3 "Rekap biaya": butir total biaya + status IF ("Aman") + sumber harga dari daftar induk.',
          'Slide 4 "Berikutnya": butir yang menunggu keputusan Bu Ratna (jadwal cetak, ruangan).',
          'F5 sekali penuh untuk gladi, perbaiki salah ketik, simpan "Laporan Rapat RT.pptx" di folder kerja.',
        ]},
        { t: 'list', items: [
          'Ctrl + S tiap dua menit — refleks seumur hidup.',
          'Mau rehat ke pantry? Win + L dulu. Selalu.',
          'Layar penuh jendela? Win + Panah membelah layar: bahan kiri, kerja kanan — jurus Lentera sejak hari pertama.',
          'Jangan biarkan notifikasi memecah fokus: selesaikan satu slide, baru lirik email.',
        ]},
        { t: 'tip', text: 'Slide laporan internal tidak perlu indah berlebihan — JELAS dan JUJUR lebih dihargai: apa yang selesai, berapa biayanya, apa yang menunggu keputusan.' },
        { t: 'try', text: 'Buat 4 slide laporan di atas dengan isi versimu. Gladi F5. Simpan di folder Rapat RT. Lalu berdiri, regangkan badan — Win + L sebelum beranjak.' },
        { t: 'glossary', items: [
          { term: 'Tuntas-satu-satu', def: 'Selesaikan dan simpan satu tugas penuh sebelum pindah tugas.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Slide laporan internal yang baik berisi…',
          options: ['Apa yang selesai, angka penting, dan yang menunggu keputusan', 'Animasi sebanyak mungkin', 'Cerita panjang satu paragraf per slide', 'Hanya judul tanpa isi'],
          answer: 0, explain: 'Jelas dan jujur — atasan butuh keputusan, bukan hiburan.' },
        { type: 'mc', q: 'Ritme kerja yang menyelesaikan pekerjaan…',
          options: ['Tuntaskan satu tugas penuh, baru pindah ke berikutnya', 'Kerjakan tiga tugas bersamaan sedikit-sedikit', 'Tunggu disuruh ulang', 'Kerjakan yang paling mudah saja'],
          answer: 0, explain: 'Setengah-setengah di tiga tugas = nol yang selesai.' },
        { type: 'mc', q: 'Meninggalkan meja ke pantry sebentar…',
          options: ['Win + L dulu', 'Biarkan terbuka', 'Matikan laptop total', 'Bawa laptopnya'],
          answer: 0, explain: 'Refleks penutup Lentera — satu detik, data aman.' },
        { type: 'mc', q: 'Membaca bahan sambil mengetik di jendela lain paling nyaman dengan…',
          options: ['Win + Panah — belah layar kiri-kanan', 'Bolak-balik Alt+Tab terus', 'Cetak semua bahan', 'Dua laptop'],
          answer: 0, explain: 'Jurus belah layar — dipakai sejak Modul 0.' },
      ],
    },

    /* ============ BABAK 5 ============ */
    {
      id: 'm5.b5', no: 5,
      title: 'Sore: kirim, arsip, dan tutup hari',
      desc: 'Mengemas tiga keluaran, mengirim dengan benar, dan meninggalkan jejak rapi.',
      blocks: [
        { t: 'p', text: 'Pukul 15.30. Tiga file siap di folder Rapat RT. Saatnya pengiriman — dan di sinilah staf rapi terlihat bedanya: BENTUK file yang dikirim dipilih dengan sadar.' },
        { t: 'list', items: [
          'Surat undangan → Bu Ratna cukup MEMBACA dan mencetak: kirim PDF (F12 → PDF).',
          'Rekap biaya → Bu Ratna mungkin mau MENGUBAH angka: kirim .xlsx asli (rumus VLOOKUP/SUM ikut hidup) — boleh plus PDF-nya.',
          'Slide → untuk DIBACA: PDF; kalau beliau yang akan menayangkan: .pptx.',
        ]},
        { t: 'steps', items: [
          'Tulis satu email ke Bu Ratna: perihal "Persiapan Rapat RT — selesai", isi 3 baris (salam, ringkasan: surat 5 RT + rekap total Rp… status Aman + slide terlampir, penutup bernama).',
          'Lampirkan ketiga file lewat ikon klip — tunggu semua namanya muncul utuh.',
          'Isi To/Kepada PALING AKHIR (kebiasaan emas Modul 4), baca ulang sekali, Send/Kirim.',
          'Arsip: salin folder Rapat RT ke flashdisk ATAU kirim juga ke email sendiri — backup satu menit.',
          'Tutup semua aplikasi dengan sopan, Shut down dari Start. Hari selesai.',
        ]},
        { t: 'tip', text: 'Email pengantar yang merangkum angka penting ("total Rp 850.000 — status Aman") membuat atasan tak perlu membuka lampiran untuk tahu intinya. Itu kelas tersendiri.' },
        { t: 'try', text: 'Kemas sungguhan: jadikan suratmu PDF, lalu kirim email (boleh ke alamatmu sendiri) berisi 3 lampiran + ringkasan 3 baris. Terakhir, salin folder kerjamu ke flashdisk atau email sendiri.' },
        { t: 'glossary', items: [
          { term: 'Email pengantar', def: 'Email berisi ringkasan inti + lampiran lengkap.' },
          { term: 'Arsip harian', def: 'Salinan folder kerja di tempat kedua sebelum pulang.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Atasan perlu MENGUBAH angka rekapmu. File yang dikirim…',
          options: ['.xlsx asli — rumusnya ikut hidup', 'PDF saja', 'Foto tabel', 'Diketik ulang di badan email'],
          answer: 0, explain: 'PDF beku untuk dibaca; .xlsx hidup untuk diolah.' },
        { type: 'mc', q: 'Surat undangan final untuk dicetak atasan paling pas dikirim sebagai…',
          options: ['PDF', '.docx mentah selalu', 'Tangkapan layar', 'Teks WA'],
          answer: 0, explain: 'Bentuk beku — rapi di printer siapa pun.' },
        { type: 'mc', q: 'Urutan mengirim email penting yang aman…',
          options: ['Tulis isi → lampirkan → baca ulang → isi Kepada → kirim', 'Isi Kepada dulu biar tak lupa', 'Kirim dulu, lampiran menyusul', 'Tanpa perihal biar cepat'],
          answer: 0, explain: 'Kepada paling akhir = mustahil terkirim setengah jadi.' },
        { type: 'mc', q: 'Sebelum pulang, folder kerja hari ini…',
          options: ['Disalin ke flashdisk / email sendiri sebagai arsip', 'Dihapus biar bersih', 'Dibiarkan tanpa nama', 'Dipindah ke Recycle Bin'],
          answer: 0, explain: 'Backup satu menit — laptop bisa rusak, kerjamu jangan.' },
      ],
    },
  ],

  /* ============ UJIAN PRAKTEK MODUL 5 (unggah .docx) ============ */
  praktik: {
    id: 'm5.praktik',
    title: 'Ujian praktek — Laporan Harian Simulasi',
    pass: 80,
    ext: ['docx'],
    brief: [
      'Jalani simulasinya sungguhan (Babak 1–5), lalu tulis LAPORAN HARIAN di Word — dokumen yang biasa diminta atasan di akhir hari.',
      'Judul memuat kata "LAPORAN" (misal: LAPORAN HARIAN — PERSIAPAN RAPAT RT), ditebalkan (Ctrl + B) dan rata tengah (Ctrl + E).',
      'Isi pembuka 1–2 kalimat: hari/tanggal simulasi dan tugas dari "Bu Ratna".',
      'Buat DAFTAR bernomor (tombol Numbering) berisi minimal 3 pekerjaan yang kamu selesaikan: surat mail merge, rekap VLOOKUP, slide laporan — sebut hasilnya (misal "5 surat undangan jadi").',
      'Tutup dengan 1–2 kalimat rencana/catatan untuk besok. Total isi minimal 60 kata.',
      'Simpan (Ctrl + S) sebagai .docx bernama jelas di folder kerjamu, lalu unggah di sini.',
    ],
    rubric: [
      { id: 'docx-valid', label: 'File Word (.docx) terbaca dengan baik' },
      { id: 'judul-laporan', label: 'Ada judul memuat kata "LAPORAN"' },
      { id: 'laporan-bold', label: 'Judul laporan ditebalkan (Ctrl + B)' },
      { id: 'laporan-center', label: 'Judul laporan rata tengah (Ctrl + E)' },
      { id: 'ada-list', label: 'Ada daftar bernomor/butir pekerjaan' },
      { id: 'kata-60', label: 'Isi laporan minimal 60 kata' },
    ],
  },

  /* ============ UJIAN AKHIR ============ */
  final: {
    id: 'm5.final',
    pass: 85,
    title: 'Ujian akhir Modul 5',
    intro: 'Lima belas soal situasional — kamu di kursi staf, pilih tindakan terbaik. Satu kesempatan jawab per soal, nilai lulus 85. Belum lulus? Pelajari pembahasan, ulangi — soal diacak ulang.',
    questions: [
      { type: 'mc', q: 'Pagi hari, hal pertama yang dibuka staf admin…',
        options: ['Email — tugas hari ini menunggu di sana', 'Game', 'Media sosial', 'Folder foto'],
        answer: 0, explain: 'Kotak masuk = papan tugas harianmu.' },
      { type: 'mc', q: 'Diminta membuat 30 surat tugas bernama beda-beda…',
        options: ['Mail Merge: satu naskah + daftar Excel', 'Ketik 30 kali', 'Fotokopi lalu tulis tangan namanya', 'Tolak tugasnya'],
        answer: 0, explain: 'Sekali ketik, Word mengisi 30 nama sendiri.' },
      { type: 'mc', q: 'Field «Nama» pada naskah merge berasal dari…',
        options: ['Tombol Insert Merge Field, tersambung kolom Excel', 'Ketikan tanda « » manual', 'Salinan internet', 'Format Bold'],
        answer: 0, explain: 'Hanya field asli yang berganti nama saat digabung.' },
      { type: 'mc', q: 'Sebelum Finish & Merge, langkah bijak…',
        options: ['Preview Results — pastikan nama masuk benar', 'Langsung cetak semua', 'Hapus daftar Excel', 'Ganti tema'],
        answer: 0, explain: 'Salah kolom ketahuan sebelum 30 surat lahir.' },
      { type: 'mc', q: 'Mengambil harga dari sheet daftar induk berdasarkan nama barang…',
        options: ['=VLOOKUP(A2; Daftar!A:B; 2; FALSE)', '=SUM(Daftar!B:B)', 'Mengetik ulang harga', '=B2*C2'],
        answer: 0, explain: 'Cari kuncinya, ambil kolom ke-2, harus persis.' },
      { type: 'mc', q: 'VLOOKUP-mu menghasilkan #N/A untuk "Snack"…',
        options: ['Periksa ejaan/spasi — kunci harus persis sama dengan daftar', 'Restart laptop', 'Hapus daftarnya', 'Ganti komputer'],
        answer: 0, explain: '#N/A = tidak ketemu, hampir selalu soal ejaan.' },
      { type: 'mc', q: 'Sel status otomatis "Perlu persetujuan" bila total > 1 juta memakai rumus…',
        options: ['IF', 'SUM', 'AVERAGE', 'VLOOKUP'],
        answer: 0, explain: 'IF menilai syarat lalu menulis salah satu dari dua jawaban.' },
      { type: 'mc', q: 'Harga di daftar induk berubah. Rekap yang memakai VLOOKUP…',
        options: ['Ikut terbarui otomatis', 'Harus diketik ulang', 'Rusak', 'Terkunci'],
        answer: 0, explain: 'Itulah untungnya merujuk, bukan menyalin.' },
      { type: 'mc', q: 'Tiga tugas sehari. Ritme terbaik…',
        options: ['Tuntaskan satu-satu sampai tersimpan rapi', 'Kerjakan bersamaan sedikit-sedikit', 'Mulai dari yang paling sore', 'Tunggu ditagih'],
        answer: 0, explain: 'Tuntas-satu-satu mengalahkan sibuk-tanpa-selesai.' },
      { type: 'mc', q: 'Atasan ingin bisa MENGUBAH angka rekap yang kamu kirim…',
        options: ['Kirim .xlsx (rumus hidup)', 'Kirim PDF saja', 'Kirim foto', 'Print lalu antar'],
        answer: 0, explain: 'Bentuk hidup untuk diolah; PDF untuk dibaca.' },
      { type: 'mc', q: 'Email pengantar tugas selesai yang baik…',
        options: ['Ringkas angka pentingnya + lampiran lengkap', 'Hanya tulisan "terlampir"', 'Tanpa perihal', 'Sepuluh paragraf basa-basi'],
        answer: 0, explain: 'Atasan tahu inti tanpa membuka lampiran.' },
      { type: 'mc', q: 'Kebiasaan emas sebelum menekan Send pada email penting…',
        options: ['Isi Kepada paling akhir + baca ulang sekali', 'Kirim cepat sebelum lupa', 'Cc semua orang', 'Hapus perihal'],
        answer: 0, explain: 'Kepada kosong = tak mungkin terkirim setengah jadi.' },
      { type: 'mc', q: 'Rekan mengirim file .apk lewat email kantor…',
        options: ['Jangan buka; konfirmasi langsung ke orangnya', 'Buka karena kenal', 'Instal', 'Teruskan ke grup'],
        answer: 0, explain: 'Akun bisa dibajak — .apk di laptop adalah bendera merah.' },
      { type: 'mc', q: 'Sebelum pulang, folder kerja hari ini…',
        options: ['Diarsipkan: salin ke flashdisk atau email sendiri', 'Dibiarkan saja pasti aman', 'Dihapus', 'Dipindah ke Desktop tanpa nama'],
        answer: 0, explain: 'Backup satu menit menyelamatkan kerja seharian.' },
      { type: 'mc', q: 'Meninggalkan meja saat jam kerja…',
        options: ['Win + L', 'Biarkan terbuka', 'Matikan listrik ruangan', 'Tutup setengah layar'],
        answer: 0, explain: 'Refleks penutup: layar terkunci, data terjaga.' },
    ],
  },
}

// 5 babak + ujian praktek + ujian teori = 7 langkah Modul 5.
export const M5_ITEMS = [
  'm5.b1', 'm5.b2', 'm5.b3', 'm5.b4', 'm5.b5', 'm5.praktik', 'm5.final',
]
