// MODUL 4 — Pelengkap Kerja
// Aturan bahasa Lentera: label yang TERTULIS di layar selalu disebut dwibahasa.
// Modul ini tanpa ujian praktek unggah file — puncaknya ujian teori.

export const MODUL4 = {
  id: 'm4',
  title: 'Modul 4 — Pelengkap kerja',
  intro:
    'Word, Excel, dan PowerPoint sudah di tanganmu. Modul terakhir ini mengisi sisanya: keterampilan yang dipakai SETIAP hari kerja tapi jarang diajarkan — mengirim email yang sopan, melampirkan file, memahami PDF, mencetak dan memindai, berselancar dengan aman, dan menjaga tata krama kerja digital. Pendek-pendek babnya, tapi inilah yang membedakan orang yang "bisa komputer" dengan orang yang SIAP BEKERJA.',
  bab: [
    /* ============ BAB 1 ============ */
    {
      id: 'm4.b1', no: 1,
      title: 'Email pertamamu',
      desc: 'Anatomi alamat email, Kepada, Perihal, dan isi yang sopan.',
      blocks: [
        { t: 'p', text: 'Email adalah surat resmi dunia kerja — lamaran, laporan, undangan rapat, semuanya lewat sini. WhatsApp untuk cepat-cepatan; email untuk yang resmi dan perlu jejak. Alamat email bentuknya selalu sama: nama@tempat — misalnya dimas@gmail.com. Satu huruf saja salah, surat nyasar atau gagal terkirim.' },
        { t: 'h', text: 'Tiga kotak wajib saat menulis email' },
        { t: 'list', items: [
          'To/Kepada — alamat email tujuan. Periksa ejaannya dua kali.',
          'Subject/Perihal — JUDUL emailmu. Wajib diisi, singkat dan jelas: "Laporan Kegiatan Juni" — bukan kosong, bukan "penting!!!".',
          'Isi — tubuh suratnya.',
        ]},
        { t: 'h', text: 'Kerangka isi yang sopan' },
        { t: 'steps', items: [
          'Salam pembuka: "Selamat pagi Pak Budi," atau "Yth. Ibu Sari,".',
          'Maksud langsung di kalimat pertama: "Bersama email ini saya kirimkan laporan kegiatan bulan Juni."',
          'Penutup: "Terima kasih." lalu nama lengkapmu.',
          'Baca ulang sekali, baru klik Send/Kirim.',
        ]},
        { t: 'warn', text: 'Tombol Send/Kirim tidak punya tombol tarik-kembali yang andal. Kebiasaan emas: isi kotak To/Kepada PALING AKHIR — selama kosong, email mustahil terkirim sebelum waktunya.' },
        { t: 'tip', text: 'Email kantor dibaca orang sibuk: pendek, jelas, ada perihal. Email tanpa perihal sering dilewati atau masuk curiga spam.' },
        { t: 'try', text: 'Buka layanan email di browser (misal gmail.com), klik Compose/Tulis. Kirim email ke alamat emailmu SENDIRI: perihal "Latihan Lentera", isi tiga baris dengan salam, maksud, dan nama. Klik Send/Kirim, lalu cek masuk di Inbox/Kotak masuk.' },
        { t: 'glossary', items: [
          { term: 'To/Kepada', def: 'Kotak alamat tujuan email.' },
          { term: 'Subject/Perihal', def: 'Judul email — wajib, singkat, jelas.' },
          { term: 'Send/Kirim', def: 'Tombol mengirim — tidak bisa ditarik kembali.' },
          { term: 'Inbox/Kotak masuk', def: 'Daftar email yang kamu terima.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Bentuk alamat email yang BENAR…',
          options: ['dimas@gmail.com', 'dimas.gmail.com', 'dimas@gmail', 'www.dimas.com'],
          answer: 0, explain: 'Selalu nama@tempat — ada @ dan akhiran lengkap.' },
        { type: 'mc', q: 'Subject/Perihal email sebaiknya…',
          options: ['Singkat dan jelas, misal "Laporan Kegiatan Juni"', 'Dikosongkan saja', 'Diisi "penting!!!"', 'Diisi seluruh isi surat'],
          answer: 0, explain: 'Perihal = judul; pembaca sibuk menilai dari sini.' },
        { type: 'mc', q: 'Agar email tidak terkirim sebelum waktunya, kebiasaan amannya…',
          options: ['Isi kotak To/Kepada paling akhir', 'Ketik cepat-cepat', 'Jangan pakai perihal', 'Kirim tengah malam'],
          answer: 0, explain: 'To kosong = mustahil terkirim tak sengaja.' },
        { type: 'mc', q: 'Urutan isi email yang sopan…',
          options: ['Salam → maksud → terima kasih → nama', 'Langsung perintah tanpa salam', 'Nama dulu, isi belakangan', 'Cukup lampiran tanpa tulisan'],
          answer: 0, explain: 'Kerangka tiga bagian: pembuka, maksud, penutup bernama.' },
      ],
    },

    /* ============ BAB 2 ============ */
    {
      id: 'm4.b2', no: 2,
      title: 'Lampiran, balas, teruskan',
      desc: 'Ikon klip, mengunduh lampiran, Reply vs Reply All, Forward.',
      blocks: [
        { t: 'p', text: 'Kekuatan email yang sesungguhnya: mengirim FILE. Laporan Word, rekap Excel, presentasi — semuanya menumpang email sebagai lampiran (attachment). Tandanya ikon KLIP KERTAS.' },
        { t: 'steps', items: [
          'Saat menulis email, klik ikon klip (Attach/Lampirkan).',
          'Jendela pemilih file terbuka — ini jendela yang sama dengan Save As: kamu sudah hafal medannya dari Modul 0.',
          'Cari filemu (Documents…), klik, klik Open/Buka.',
          'Tunggu sampai nama file muncul utuh di bawah email — lampiran besar butuh waktu naik. Baru kirim.',
        ]},
        { t: 'p', text: 'Menerima lampiran? Klik nama filenya lalu pilih Download/Unduh — file tersimpan, biasanya di folder Downloads. Ingat peta folder Modul 0: unduhan selalu mendarat di sana.' },
        { t: 'h', text: 'Tiga tombol balasan — bedanya penting' },
        { t: 'list', items: [
          'Reply/Balas — membalas HANYA ke pengirim. Ini pilihan amanmu sehari-hari.',
          'Reply All/Balas semua — balasanmu dikirim ke pengirim DAN seluruh orang di daftar. Pakai hanya bila semua memang perlu tahu.',
          'Forward/Teruskan — mengirimkan email itu (beserta lampirannya) ke orang LAIN yang belum menerimanya.',
        ]},
        { t: 'warn', text: 'Kecelakaan email paling legendaris di kantor: curhat atau jawaban pribadi terkirim ke SEMUA orang karena salah pencet Reply All. Sebelum mengirim balasan, lirik dulu daftar penerimanya.' },
        { t: 'try', text: 'Balas (Reply) email latihanmu kemarin dengan satu kalimat. Lalu tulis email baru ke dirimu sendiri dan lampirkan file Word surat izin dari Modul 1 — perhatikan ikon klip dan tunggu namanya muncul sebelum mengirim.' },
        { t: 'glossary', items: [
          { term: 'Attachment (lampiran)', def: 'File yang menumpang email — ikon klip.' },
          { term: 'Reply', def: 'Balas ke pengirim saja.' },
          { term: 'Reply All', def: 'Balas ke pengirim dan semua penerima — hati-hati.' },
          { term: 'Forward', def: 'Meneruskan email ke orang lain.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Ikon untuk MELAMPIRKAN file di email…',
          options: ['Klip kertas', 'Bintang', 'Tempat sampah', 'Lup pembesar'],
          answer: 0, explain: 'Klip = attach/lampirkan.' },
        { type: 'mc', q: 'Membalas pertanyaan pribadi dari satu pengirim, padahal email itu dikirim ke 20 orang…',
          options: ['Reply/Balas', 'Reply All/Balas semua', 'Forward', 'Tulis email baru ke semua'],
          answer: 0, explain: 'Reply = hanya ke pengirim. Reply All membuat 20 orang membaca jawabanmu.' },
        { type: 'mc', q: 'Mengirimkan email yang kamu terima ke orang LAIN…',
          options: ['Forward/Teruskan', 'Reply', 'Delete', 'Spam'],
          answer: 0, explain: 'Forward meneruskan isi beserta lampirannya.' },
        { type: 'mc', q: 'File lampiran yang kamu unduh biasanya mendarat di folder…',
          options: ['Downloads', 'Recycle Bin', 'Desktop selalu', 'Drive C langsung'],
          answer: 0, explain: 'Downloads — peta folder dari Modul 0.' },
      ],
    },

    /* ============ BAB 3 ============ */
    {
      id: 'm4.b3', no: 3,
      title: 'PDF: bentuk beku dokumen',
      desc: 'Kenapa PDF, membuat PDF dari aplikasi mana pun, membuka dan mencarinya.',
      blocks: [
        { t: 'p', text: 'PDF sudah tiga kali mampir di modul-modul sebelumnya — kini resmi kita bedah. PDF (Portable Document Format) adalah bentuk BEKU sebuah dokumen: tampilannya terkunci persis sama di laptop, HP, atau saat dicetak siapa pun. Karena itu dunia kerja menyukainya untuk dokumen final: surat jadi, laporan resmi, undangan.' },
        { t: 'list', items: [
          'File kerja (.docx, .xlsx, .pptx) = adonan: bisa diedit, tampilan bisa bergeser di laptop lain.',
          'PDF = kue matang: rapi, terkunci, siap disajikan — tapi tidak untuk diedit lagi.',
          'Kirim PDF bila penerima cukup MEMBACA; kirim file kerja bila penerima perlu MENGEDIT.',
        ]},
        { t: 'h', text: 'Membuat PDF — resep yang sama di mana-mana' },
        { t: 'steps', items: [
          'Dari Word, Excel, atau PowerPoint: tekan F12 (Save As/simpan sebagai).',
          'Di kotak "Save as type/jenis file", ganti ke PDF.',
          'Beri nama jelas, klik Save. File kerja aslimu tetap ada — PDF lahir sebagai kembaran beku.',
        ]},
        { t: 'p', text: 'Membuka PDF cukup dobel klik — terbuka di browser atau aplikasi pembaca PDF. Di dalamnya, sahabat lama bekerja: Ctrl + F mencari kata di dokumen ratusan halaman dalam sekejap.' },
        { t: 'tip', text: 'Menerima PDF untuk diisi-tanda-tangan? Cara paling sederhana di lapangan: cetak, isi dengan pena, lalu pindai kembali (scan — Bab 4).' },
        { t: 'try', text: 'Buka rekap Excel dari Modul 2, tekan F12, pilih jenis PDF, simpan. Dobel klik PDF-nya, tekan Ctrl + F dan cari kata "TOTAL". Bandingkan: PDF rapi terkunci, Excel tetap bisa diedit.' },
        { t: 'glossary', items: [
          { term: 'PDF', def: 'Bentuk beku dokumen — tampil sama di mana pun.' },
          { term: 'Save as type', def: 'Kotak pemilih jenis file di jendela Save As.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Kelebihan utama PDF…',
          options: ['Tampilan terkunci sama di perangkat mana pun', 'Mudah diedit siapa saja', 'Ukurannya selalu paling kecil', 'Hanya bisa dibuka di satu laptop'],
          answer: 0, explain: 'Bentuk beku — itulah gunanya untuk dokumen final.' },
        { type: 'mc', q: 'Membuat PDF dari Word/Excel/PowerPoint…',
          options: ['F12 → ganti jenis file ke PDF → Save', 'Mengganti nama file jadi .pdf', 'Memotret layar', 'Mengirim ke percetakan'],
          answer: 0, explain: 'Save As dengan jenis PDF — file asli tetap ada.' },
        { type: 'mc', q: 'Penerima perlu MENGEDIT dokumenmu. Yang dikirim…',
          options: ['File kerjanya (.docx/.xlsx)', 'PDF', 'Foto dokumen', 'Print-annya saja'],
          answer: 0, explain: 'PDF untuk dibaca; file kerja untuk diedit.' },
        { type: 'mc', q: 'Mencari satu kata di PDF ratusan halaman…',
          options: ['Ctrl + F lalu ketik katanya', 'Membaca dari awal', 'Mencetak semua dulu', 'Tidak mungkin'],
          answer: 0, explain: 'Ctrl + F bekerja di PDF juga.' },
      ],
    },

    /* ============ BAB 4 ============ */
    {
      id: 'm4.b4', no: 4,
      title: 'Mencetak dan memindai',
      desc: 'Dialog cetak di aplikasi mana pun, memilih printer, dan scan dokumen.',
      blocks: [
        { t: 'p', text: 'Kabar baik: kamu SUDAH bisa mencetak — Ctrl + P sudah dilatih di Word dan Excel, dan jurus yang sama berlaku di browser, PDF, dan hampir semua aplikasi. Bab ini merapikan pemahamannya jadi satu peta.' },
        { t: 'h', text: 'Peta layar Print/Cetak — di mana pun sama' },
        { t: 'list', items: [
          'Printer — pastikan NAMA printer yang dipilih benar (kantor bisa punya beberapa; salah pilih = cetakanmu keluar di ruangan lain).',
          'Copies/Rangkap — jumlah salinan.',
          'Pages/Halaman — All/semua, atau tulis nomor tertentu: 1-3 (satu sampai tiga) atau 2,5 (dua dan lima saja). Hemat kertas, hemat tinta.',
          'Orientation — Portrait/tegak untuk surat, Landscape/mendatar untuk tabel lebar.',
          'Pratinjau — SELALU lirik sebelum menekan Print.',
        ]},
        { t: 'h', text: 'Memindai (scan): kertas menjadi file' },
        { t: 'steps', items: [
          'Letakkan dokumen menghadap KACA pemindai, rapat ke sudut penanda.',
          'Di laptop, buka aplikasi pemindai (Windows Scan — atau tombol Scan di mesinnya).',
          'Pilih hasil PDF (untuk dokumen) dan tekan Scan/Pindai.',
          'File hasil pindai masuk ke folder (biasanya Documents atau Pictures > Scans) — temukan, ganti namanya yang jelas, lalu siap dilampirkan ke email.',
        ]},
        { t: 'tip', text: 'Rantai keterampilanmu kini tersambung: dokumen kertas → scan jadi PDF → ganti nama rapi → lampirkan ke email. Empat modul bekerja sama dalam satu alur kerja kantor sehari-hari.' },
        { t: 'try', text: 'Buka PDF apa pun, tekan Ctrl + P: temukan kotak printer, Copies, Pages, dan pratinjau — lalu Esc (tak usah mencetak). Bila ada mesin pemindai: pindai satu lembar jadi PDF dan temukan filenya.' },
        { t: 'glossary', items: [
          { term: 'Copies', def: 'Jumlah rangkap cetakan.' },
          { term: 'Pages 1-3', def: 'Cetak halaman satu sampai tiga saja.' },
          { term: 'Scan (pindai)', def: 'Mengubah kertas menjadi file.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Membuka layar cetak di hampir semua aplikasi…',
          options: ['Ctrl + P', 'Ctrl + M', 'F5', 'Ctrl + ;'],
          answer: 0, explain: 'Print = Ctrl + P, di Word, Excel, browser, PDF.' },
        { type: 'mc', q: 'Mencetak hanya halaman 1 sampai 3…',
          options: ['Isi kotak Pages dengan 1-3', 'Cetak semua lalu buang sisanya', 'Tekan Print tiga kali', 'Tidak bisa'],
          answer: 0, explain: 'Tanda hubung = rentang halaman.' },
        { type: 'mc', q: 'Cetakanmu tidak keluar padahal sudah menekan Print. Periksa pertama…',
          options: ['Nama printer yang terpilih benar atau bukan', 'Ganti laptop', 'Instal ulang Windows', 'Tekan Print 10 kali'],
          answer: 0, explain: 'Salah pilih printer = dokumen keluar di mesin lain.' },
        { type: 'mc', q: 'Hasil scan dokumen kantor paling pas disimpan sebagai…',
          options: ['PDF', 'Lagu', 'Video', 'Shortcut'],
          answer: 0, explain: 'Dokumen = PDF; rapi dan siap dilampirkan.' },
      ],
    },

    /* ============ BAB 5 ============ */
    {
      id: 'm4.b5', no: 5,
      title: 'Internet sehat dan aman',
      desc: 'Browser, kata sandi kuat, mengenali penipuan, menjaga data pribadi.',
      blocks: [
        { t: 'p', text: 'Internet adalah jalan raya: penuh tujuan berguna, tapi ada juga copetnya. Kendaraanmu bernama browser (Chrome, Edge): kotak alamat di atas untuk menuju situs, dan kamu sudah memakainya membuka email. Bab ini tentang berkendara dengan selamat.' },
        { t: 'h', text: 'Kata sandi: kunci rumahmu' },
        { t: 'list', items: [
          'Kuat = PANJANG (12+ karakter) dan campuran: huruf besar-kecil, angka. Kalimat unik mudah diingat: SayaSukaKopi3Gelas! jauh lebih kuat daripada dimas123.',
          'Jangan pakai tanggal lahir, nama anak, atau "123456" — itu tebakan pertama pencuri.',
          'Satu situs penting, satu sandi — kalau satu bocor, yang lain selamat.',
          'JANGAN PERNAH memberikan sandi atau kode OTP kepada siapa pun — petugas bank sungguhan TIDAK PERNAH memintanya.',
        ]},
        { t: 'h', text: 'Mengenali penipuan (phishing)' },
        { t: 'list', items: [
          'Pesan menakut-nakuti + buru-buru: "Akun Anda diblokir 1x24 jam, klik segera!" — tekanan waktu adalah tanda penipu.',
          'Hadiah tiba-tiba: "Selamat! Anda menang undian" padahal tak pernah ikut.',
          'Alamat pengirim aneh: bank-bca@gmail.com — bank resmi tidak memakai gmail.',
          'Lampiran .apk atau file aneh di WhatsApp/email: JANGAN dibuka — itu bisa menguras rekening.',
          'Ragu? JANGAN KLIK. Tanyakan langsung ke kantor resminya lewat nomor yang kamu cari sendiri.',
        ]},
        { t: 'warn', text: 'Data pribadi — foto KTP, nomor rekening, kode OTP — jangan dikirim ke orang tak dikenal atau diunggah sembarangan. Sekali tersebar, tak bisa ditarik kembali.' },
        { t: 'try', text: 'Buka browser, ketik alamat situs resmi mana pun di kotak alamat. Lalu susun satu kata sandi kuat versi kalimat untuk akun emailmu — tulis di ingatan, bukan di kertas yang ditempel di laptop.' },
        { t: 'glossary', items: [
          { term: 'Browser', def: 'Aplikasi menjelajah internet — Chrome, Edge.' },
          { term: 'Phishing', def: 'Penipuan berkedok pesan resmi untuk mencuri data.' },
          { term: 'OTP', def: 'Kode rahasia sekali pakai — jangan diberikan ke siapa pun.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Kata sandi paling KUAT di antara ini…',
          options: ['SayaSukaKopi3Gelas!', 'dimas123', '123456', 'tanggal lahir'],
          answer: 0, explain: 'Panjang + campuran huruf-angka-simbol, dan unik.' },
        { type: 'mc', q: 'SMS: "Rekening diblokir! Kirim kode OTP sekarang." Tindakanmu…',
          options: ['Abaikan — bank resmi tidak pernah meminta OTP', 'Kirim OTP cepat-cepat', 'Balas dengan nomor rekening', 'Teruskan ke teman-teman'],
          answer: 0, explain: 'OTP = kunci rekening. Peminta OTP = penipu, selalu.' },
        { type: 'mc', q: 'Tanda khas pesan penipuan…',
          options: ['Menakut-nakuti dan menyuruh buru-buru klik', 'Bahasa sopan dan tidak memaksa', 'Dikirim jam kerja', 'Ada nama pengirim'],
          answer: 0, explain: 'Tekanan waktu mematikan nalar — itu senjata penipu.' },
        { type: 'mc', q: 'Yang BOLEH dibagikan di internet…',
          options: ['Tulisan/karya yang memang untuk umum', 'Foto KTP', 'Kode OTP', 'Nomor rekening ke orang tak dikenal'],
          answer: 0, explain: 'Data pribadi tetap pribadi — sekali bocor tak bisa ditarik.' },
      ],
    },

    /* ============ BAB 6 ============ */
    {
      id: 'm4.b6', no: 6,
      title: 'Etika dan kebiasaan kerja digital',
      desc: 'Nama file rapi, folder teratur, backup, dan mengunci layar.',
      blocks: [
        { t: 'p', text: 'Bab penutup ini bukan soal tombol — soal KEBIASAAN. Inilah yang membuat rekan kerja dan atasan menilai: "orang ini rapi, bisa dipercaya pegang data".' },
        { t: 'list', items: [
          'Nama file menjelaskan isinya + tanggal: "Laporan Posyandu 2026-06.docx" — bukan "New Document (3) final fix beneran.docx".',
          'Folder per urusan: Documents > Laporan, Documents > Surat. Lima detik menata, lima jam terselamatkan saat mencari.',
          'File penting punya KEMBARAN: salin ke flashdisk (Modul 0 Bab 7) atau kirim ke email sendiri. Laptop bisa rusak kapan saja — pekerjaanmu jangan ikut mati.',
          'Jangan instal aplikasi sembarangan, apalagi bajakan atau dari tautan WA — pintu masuk virus.',
          'Laptop kantor berisi data orang: jangan dipakai akun pribadi yang aneh-aneh, dan jangan biarkan terbuka tanpa pengawas.',
        ]},
        { t: 'h', text: 'Refleks terakhir: kunci layar' },
        { t: 'p', text: 'Setiap kali meninggalkan meja — walau cuma ke toilet — tekan Win + L. Layar terkunci; isi laptop aman dari mata dan tangan jahil. Kembali, masukkan sandi, lanjut bekerja persis di tempat tadi. Inilah refleks penutup yang melengkapi Ctrl + S.' },
        { t: 'keys', items: [
          { combo: ['Win', 'L'], label: 'Lock/kunci layar — setiap meninggalkan meja' },
        ]},
        { t: 'tip', text: 'Dua refleks seumur hidup dari Lentera: Ctrl + S tiap dua menit (pekerjaan tak hilang), Win + L tiap meninggalkan meja (data tak bocor). Keduanya satu detik; keduanya menyelamatkan.' },
        { t: 'try', text: 'Rapikan satu folder: kumpulkan file latihan Lentera ke Documents > Latihan Lentera, ganti nama yang masih berantakan. Salin yang terpenting ke flashdisk atau email sendiri. Terakhir: tekan Win + L, lalu masuk kembali.' },
        { t: 'glossary', items: [
          { term: 'Backup', def: 'Salinan cadangan file penting di tempat kedua.' },
          { term: 'Win + L', def: 'Mengunci layar — pengaman saat meninggalkan meja.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Nama file yang paling baik…',
          options: ['Laporan Posyandu 2026-06.docx', 'New Document (3).docx', 'final fix beneran.docx', 'asdfgh.docx'],
          answer: 0, explain: 'Isi + tanggal — ketemu dalam lima detik, kapan pun.' },
        { type: 'mc', q: 'Backup artinya…',
          options: ['Menyimpan salinan file penting di tempat kedua', 'Menghapus file lama', 'Mematikan laptop dengan benar', 'Memperbesar layar'],
          answer: 0, explain: 'Laptop bisa rusak; kembaran filemu menyelamatkan pekerjaan.' },
        { type: 'mc', q: 'Meninggalkan meja sebentar, laptop kantor menyala…',
          options: ['Tekan Win + L — layar terkunci', 'Biarkan terbuka, kan cuma sebentar', 'Matikan total', 'Tutup setengah layarnya'],
          answer: 0, explain: 'Satu detik mengunci, data orang banyak terlindungi.' },
        { type: 'mc', q: 'Tautan di WA menawarkan aplikasi "penghasil uang", minta diinstal…',
          options: ['Jangan instal — aplikasi sembarangan pintu masuk virus', 'Instal di laptop kantor', 'Instal lalu hapus', 'Teruskan ke grup keluarga'],
          answer: 0, explain: 'Instal hanya dari sumber resmi yang jelas.' },
      ],
    },
  ],

  /* ============ UJIAN AKHIR ============ */
  final: {
    id: 'm4.final',
    pass: 85,
    title: 'Ujian akhir Modul 4',
    intro: 'Lima belas soal pelengkap kerja: email, lampiran, PDF, cetak-pindai, keamanan, dan etika digital. Satu kesempatan jawab per soal, nilai lulus 85. Belum lulus? Pelajari pembahasan, ulangi — soal diacak ulang.',
    questions: [
      { type: 'mc', q: 'Alamat email yang sah…',
        options: ['sari@kantor.co.id', 'sari.kantor.co.id', 'sari@kantor', '@sari.com'],
        answer: 0, explain: 'nama@tempat dengan akhiran lengkap.' },
      { type: 'mc', q: 'Kotak Subject/Perihal diisi…',
        options: ['Judul singkat yang jelas', 'Dikosongkan', 'Seluruh isi surat', 'Tanda seru banyak'],
        answer: 0, explain: 'Perihal = wajah emailmu.' },
      { type: 'mc', q: 'Melampirkan file laporan ke email…',
        options: ['Klik ikon klip, pilih file, tunggu namanya muncul, kirim', 'Tulis nama file di isi email', 'Foto layar laporannya', 'Kirim laptopnya'],
        answer: 0, explain: 'Ikon klip = Attach; tunggu lampiran naik penuh.' },
      { type: 'mc', q: 'Email berisi pertanyaan untukmu, dikirim ke 15 orang. Jawaban pribadimu dikirim lewat…',
        options: ['Reply/Balas', 'Reply All/Balas semua', 'Forward ke semua', 'Grup WA kantor'],
        answer: 0, explain: 'Reply = ke pengirim saja; Reply All = semua membaca.' },
      { type: 'mc', q: 'Meneruskan email beserta lampirannya ke rekan lain…',
        options: ['Forward/Teruskan', 'Reply', 'Delete', 'Tandai bintang'],
        answer: 0, explain: 'Forward mengantarkan utuh ke alamat baru.' },
      { type: 'mc', q: 'Dokumen final dikirim agar tampil sama persis dan tak bisa diubah-ubah…',
        options: ['PDF', '.docx', 'Foto layar', 'Tulisan WA'],
        answer: 0, explain: 'PDF = bentuk beku dokumen.' },
      { type: 'mc', q: 'Membuat PDF dari Word…',
        options: ['F12 → jenis file PDF → Save', 'Ganti nama jadi .pdf', 'Ctrl + M', 'Tidak bisa dari Word'],
        answer: 0, explain: 'Save As dengan jenis PDF.' },
      { type: 'mc', q: 'Mencari kata "honor" di PDF 80 halaman…',
        options: ['Ctrl + F, ketik honor', 'Baca semua halaman', 'Cetak dulu semuanya', 'Minta orang lain'],
        answer: 0, explain: 'Ctrl + F bekerja di PDF.' },
      { type: 'mc', q: 'Mencetak hanya halaman 2 dan 5…',
        options: ['Isi Pages: 2,5', 'Isi Pages: 2-5', 'Cetak semua', 'Tekan Print dua kali'],
        answer: 0, explain: 'Koma = halaman terpilih; tanda hubung = rentang.' },
      { type: 'mc', q: 'Hasil pindai (scan) dokumen disimpan paling pas sebagai…',
        options: ['PDF', 'MP3', 'Shortcut', 'Folder'],
        answer: 0, explain: 'Kertas → PDF → siap dilampirkan.' },
      { type: 'mc', q: 'Kata sandi paling aman…',
        options: ['Kalimat panjang campuran: KopiPagi3Gelas!', '123456', 'Tanggal lahir', 'Nama sendiri'],
        answer: 0, explain: 'Panjang + campuran + unik.' },
      { type: 'mc', q: 'Telepon mengaku dari bank meminta kode OTP…',
        options: ['Tolak dan tutup — bank tak pernah minta OTP', 'Berikan kalau suaranya sopan', 'Berikan setengah kodenya', 'Minta ditelepon ulang lalu berikan'],
        answer: 0, explain: 'Peminta OTP = penipu, tanpa kecuali.' },
      { type: 'mc', q: 'Ciri pesan phishing…',
        options: ['Menakut-nakuti dan memburu-buru agar segera klik', 'Tidak meminta apa-apa', 'Datang dari nomor tersimpan', 'Selalu berbahasa asing'],
        answer: 0, explain: 'Panik yang diburu waktu = senjata penipu.' },
      { type: 'mc', q: 'Meninggalkan laptop kantor sebentar…',
        options: ['Win + L', 'Biarkan terbuka', 'Cabut baterai', 'Tutup aplikasi satu-satu'],
        answer: 0, explain: 'Kunci layar — refleks penutup Lentera.' },
      { type: 'mc', q: 'Nama file laporan paling tepat…',
        options: ['Laporan Kegiatan 2026-06.docx', 'final fix2 beneran.docx', 'Document1.docx', 'laporan punya saya banget.docx'],
        answer: 0, explain: 'Isi + tanggal = ditemukan siapa pun, kapan pun.' },
    ],
  },
}

// 6 bab + ujian teori = 7 langkah Modul 4 (tanpa ujian praktek unggah).
export const M4_ITEMS = [
  'm4.b1', 'm4.b2', 'm4.b3', 'm4.b4', 'm4.b5', 'm4.b6', 'm4.final',
]
