// MODUL 1 — Word Dasar (v2, diperdalam)
// Aturan bahasa Lentera: label yang TERTULIS di layar selalu disebut dwibahasa,
// contoh "Print/Cetak" — karena di layar tertulis Print, dan artinya cetak.

export const MODUL1 = {
  id: 'm1',
  title: 'Modul 1 — Word dasar',
  intro:
    'Masuk ke aplikasi kantoran pertamamu: Microsoft Word — tempat lahirnya surat, laporan, dan dokumen resmi. Di modul ini kamu membuat dokumen sungguhan dari nol: mengetik, merapikan, menyimpan dengan benar, sampai mencetak. Catat satu hal: tombol-tombol di layar bertuliskan bahasa Inggris (Save, Print, Cancel) — Lentera selalu menuliskannya berpasangan, misalnya "Save/Simpan", supaya kamu hafal tulisan aslinya DAN artinya. Pakai jurus belah layar: Lentera di kiri, Word di kanan, dan kerjakan setiap kotak "Coba sekarang".',
  bab: [
    /* ============ BAB 1 ============ */
    {
      id: 'm1.b1', no: 1,
      title: 'Kenalan dengan Word',
      desc: 'Membuka Word, mengenal bagian layar, membuat dan menutup dokumen.',
      blocks: [
        { t: 'p', text: 'Word itu seperti mesin tik super: kertasnya tidak pernah habis, salah ketik tinggal dihapus, hasilnya selalu rapi, dan satu dokumen bisa diperbanyak tanpa mengetik ulang. Hampir semua pekerjaan admin, PA, dan staf kantor menyentuh Word setiap hari — surat izin, berita acara, daftar hadir, laporan kegiatan.' },
        { t: 'h', text: 'Membuka Word' },
        { t: 'steps', items: [
          'Klik tombol Start di pojok kiri bawah.',
          'Langsung ketik: word.',
          'Tekan Enter. Word terbuka.',
          'Pilih "Blank document/Dokumen kosong" untuk mulai dari kertas putih.',
        ]},
        { t: 'tip', text: 'Layar pembuka Word juga menampilkan deretan "template/contoh jadi" (undangan, brosur). Untuk belajar, selalu mulai dari Blank document — supaya kamu paham membangun dokumen dari nol.' },
        { t: 'h', text: 'Peta layar Word' },
        { t: 'img', kind: 'word', props: {}, caption: 'Jendela Word: pita perintah (ribbon) di atas, kertas putih di tengah, bilah status di bawah.' },
        { t: 'list', items: [
          'Ribbon (pita) — deretan tombol perintah di atas. Tab "Home/Beranda" berisi tombol yang paling sering dipakai; ada juga tab File, Insert/Sisip, dan Layout/Tata letak.',
          'Halaman — kertas putih di tengah, tempatmu mengetik.',
          'Kursor teks — garis hitam berkedip di halaman. Di situlah huruf muncul saat kamu mengetik.',
          'Bilah status — baris paling bawah: nomor halaman dan jumlah kata (words).',
          'Ikon disket di pojok kiri atas — tombol Save/Simpan. Kenalan dulu; mulai Bab 3 dia jadi sahabatmu.',
        ]},
        { t: 'p', text: 'Ribbon di laptopmu mungkin sedikit berbeda dandanannya dengan gambar — tiap versi Word memang begitu. Tenang: posisi dan bentuk tombolnya tetap sama, jadi semua yang kamu pelajari di sini berlaku.' },
        { t: 'h', text: 'Menutup Word dengan sopan' },
        { t: 'p', text: 'Klik tombol X di pojok kanan atas. Kalau ada ketikan yang belum disimpan, Word bertanya: "Save/Simpan", "Don\u2019t Save/Jangan simpan", atau "Cancel/Batal". Bacalah pelan — salah pilih bisa membuang pekerjaanmu.' },
        { t: 'keys', items: [
          { combo: ['Ctrl', 'N'], label: 'New/Baru — buka dokumen kosong baru' },
          { combo: ['Ctrl', 'W'], label: 'Close/Tutup — tutup dokumen (Word tetap terbuka)' },
        ]},
        { t: 'try', text: 'Buka Word lewat Start, pilih Blank document. Temukan dengan matamu: ribbon, halaman, kursor berkedip, jumlah kata, ikon disket. Lalu tutup dengan X dan pilih Don\u2019t Save/Jangan simpan — kita belum mengetik apa-apa.' },
        { t: 'glossary', items: [
          { term: 'Word', def: 'Aplikasi untuk membuat dokumen tulisan.' },
          { term: 'Dokumen', def: 'File hasil kerja Word — surat, laporan, daftar.' },
          { term: 'Ribbon', def: 'Pita tombol perintah di bagian atas.' },
          { term: 'Kursor teks', def: 'Garis berkedip penanda tempat huruf muncul.' },
          { term: 'Blank document', def: 'Dokumen kosong — kertas putih untuk mulai dari nol.' },
        ]},
      ],
      quiz: [
        { type: 'hotspot', q: 'Klik bagian tempat kamu MENGETIK di jendela Word ini.',
          img: { kind: 'word', props: {} }, accept: ['page'],
          wrong: { bold: 'Itu tombol B untuk menebalkan huruf. Tempat mengetik adalah kertas putih besar di tengah.', save: 'Itu tombol Save/Simpan. Tempat mengetik adalah kertas putih besar di tengah.' },
          explain: 'Benar! Halaman putih itu kertasmu — kursor berkedip menunggu ketikanmu.' },
        { type: 'mc', q: 'Cara paling cepat membuka Word adalah…',
          options: ['Klik Start, ketik "word", tekan Enter', 'Klik kanan di desktop', 'Tekan tombol power dua kali', 'Buka Recycle Bin'],
          answer: 0, explain: 'Jurus Start + ketik dari Modul 0 berlaku untuk semua aplikasi.' },
        { type: 'mc', q: 'Saat menutup Word, muncul pilihan "Don\u2019t Save". Artinya…',
          options: ['Simpan dokumen', 'JANGAN simpan — ketikan yang belum disimpan akan hilang', 'Cetak dokumen', 'Buka dokumen baru'],
          answer: 1, explain: 'Don\u2019t Save = jangan simpan. Pilih hanya kalau kamu memang rela ketikan itu hilang.' },
        { type: 'mc', q: 'Deretan tombol perintah di bagian atas jendela Word disebut…',
          options: ['Taskbar', 'Ribbon', 'Desktop', 'Kursor'],
          answer: 1, wrong: { 0: 'Taskbar itu bilah di bawah LAYAR WINDOWS. Yang di atas jendela Word namanya lain.' },
          explain: 'Tepat — ribbon, pita tombol. Tab Home/Beranda adalah rumah tombol favoritmu.' },
      ],
    },

    /* ============ BAB 2 ============ */
    {
      id: 'm1.b2', no: 2,
      title: 'Mengetik dan memilih teks',
      desc: 'Memindahkan kursor, ganti paragraf, dan semua jurus memilih (blok) teks.',
      blocks: [
        { t: 'p', text: 'Di Word ada DUA penunjuk: panah putih milik mouse, dan kursor teks yang berkedip. Klik kiri di mana pun pada tulisan = kursor teks pindah ke situ. Huruf selalu muncul di posisi kursor teks, bukan di posisi panah mouse. Ini sering membingungkan pemula — sekarang kamu sudah tahu rahasianya.' },
        { t: 'list', items: [
          'Enter = paragraf baru (turun satu baris). JANGAN tekan Enter di akhir setiap baris — saat baris penuh, Word menurunkan tulisan sendiri secara otomatis.',
          'Backspace = hapus ke kiri; Delete/Del = hapus ke kanan (warisan Modul 0).',
          'Tombol panah = menggeser kursor teks tanpa menghapus — pas untuk membetulkan huruf di tengah kata.',
        ]},
        { t: 'keys', items: [
          { combo: ['Ctrl', 'Panah Kiri'], label: 'Lompat per KATA (lebih cepat dari per huruf)' },
          { combo: ['Home'], label: 'Lompat ke AWAL baris' },
          { combo: ['End'], label: 'Lompat ke AKHIR baris' },
          { combo: ['Ctrl', 'Home'], label: 'Lompat ke awal dokumen' },
          { combo: ['Ctrl', 'End'], label: 'Lompat ke akhir dokumen' },
        ]},
        { t: 'h', text: 'Memilih (mem-blok) teks — kunci semua perapian' },
        { t: 'p', text: 'Sebelum teks bisa ditebalkan, dibesarkan, atau dirapikan, teks itu harus DIPILIH dulu sampai tersorot biru. Ini aturan emas Word: pilih dulu, baru perintah. Word tidak bisa menebak teks mana yang kamu maksud.' },
        { t: 'steps', items: [
          'Sedikit teks: klik di awal, TAHAN, geser sampai akhir, lepas (drag).',
          'Satu kata: dobel klik pada katanya.',
          'Satu paragraf: klik tiga kali cepat pada paragrafnya.',
          'Dari sini sampai sana: klik di awal, lalu tahan Shift dan klik di akhir.',
          'SEMUA isi dokumen: tekan Ctrl + A.',
        ]},
        { t: 'keys', items: [
          { combo: ['Ctrl', 'A'], label: 'Select All/Pilih semua isi dokumen' },
          { combo: ['Shift', 'Panah Kanan'], label: 'Memilih huruf demi huruf dengan keyboard' },
          { combo: ['Ctrl', 'Shift', 'Panah Kanan'], label: 'Memilih kata demi kata — jurus orang kantoran' },
        ]},
        { t: 'warn', text: 'Teks yang sedang tersorot biru akan TERGANTI kalau kamu langsung mengetik. Tidak sengaja kejadian? Jangan panik — Ctrl + Z mengembalikannya (jurus lengkapnya di Bab 7). Untuk membatalkan sorotan dengan aman: klik sekali di area kosong.' },
        { t: 'try', text: 'Buka Word baru, ketik 4\u20135 kalimat tentang dirimu (nama, kampung, pekerjaan impian). Lalu latih semua jurus: dobel klik satu kata, tiga kali klik pada paragraf, Shift + klik, Ctrl + A, lalu klik area kosong. Terakhir: tekan Home, End, Ctrl + Home — rasakan kursor melompat.' },
        { t: 'glossary', items: [
          { term: 'Memilih / blok', def: 'Menyorot teks sampai biru sebelum diberi perintah.' },
          { term: 'Drag', def: 'Tahan klik kiri sambil geser.' },
          { term: 'Paragraf', def: 'Sekumpulan kalimat; dibuat dengan menekan Enter.' },
          { term: 'Home / End', def: 'Tombol lompat ke awal / akhir baris.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Cara tercepat memilih SATU KATA adalah…',
          options: ['Klik sekali pada kata', 'Dobel klik pada kata', 'Tekan Enter', 'Klik kanan dua kali'],
          answer: 1, explain: 'Dobel klik = satu kata tersorot. Tiga kali klik = satu paragraf.' },
        { type: 'mc', q: 'Untuk memilih SEMUA isi dokumen sekaligus, tekan…',
          options: ['Ctrl + A', 'Ctrl + S', 'Alt + Tab', 'Ctrl + P'],
          answer: 0, explain: 'Ctrl + A = All/semua. Berlaku juga di File Explorer.' },
        { type: 'mc', q: 'Kursor teks ada di tengah baris. Untuk melompat ke AKHIR baris itu, tekan…',
          options: ['End', 'Esc', 'Enter', 'Backspace'],
          answer: 0, explain: 'End = akhir baris; Home = awal baris. Pasangan penghemat waktu.' },
        { type: 'mc', q: 'Aturan emas sebelum menebalkan atau membesarkan teks…',
          options: ['Simpan dulu dokumennya', 'Pilih (blok) dulu teksnya sampai tersorot biru', 'Tutup dulu Word-nya', 'Cetak dulu dokumennya'],
          answer: 1, explain: 'Pilih dulu, baru perintah. Tanpa dipilih, Word tidak tahu teks mana yang kamu maksud.' },
        { type: 'mc', q: 'Tombol Enter di Word dipakai untuk…',
          options: ['Menghapus kata', 'Membuat paragraf baru', 'Menyimpan dokumen', 'Memilih semua teks'],
          answer: 1, explain: 'Enter = ganti paragraf. Di tengah paragraf, biarkan Word menurunkan baris sendiri.' },
      ],
    },

    /* ============ BAB 3 ============ */
    {
      id: 'm1.b3', no: 3,
      title: 'Menyimpan dan membuka — Ctrl+S jadi refleks',
      desc: 'Save, Save As, F12, nama file yang baik, dan membuka kembali dokumen.',
      blocks: [
        { t: 'p', text: 'Inilah bab terpenting di seluruh modul. Dokumen yang belum disimpan bisa LENYAP saat listrik padam atau laptop macet — dan di kantor, kehilangan pekerjaan satu hari adalah bencana kecil. Obatnya satu kebiasaan: Ctrl + S, ditekan sesering mungkin. Selesai satu paragraf? Tekan. Mau berdiri ambil minum? Tekan dulu.' },
        { t: 'keys', items: [
          { combo: ['Ctrl', 'S'], label: 'Save/Simpan — jadikan refleks jari' },
          { combo: ['F12'], label: 'Save As/Simpan sebagai — langsung buka jendela simpan-baru' },
        ]},
        { t: 'h', text: 'Menyimpan pertama kali' },
        { t: 'p', text: 'Saat dokumen baru pertama kali disimpan (Ctrl + S), Word otomatis membuka jendela Save As/Simpan sebagai — karena dia perlu tahu dua hal: mau dinamai apa, dan mau ditaruh di mana.' },
        { t: 'img', kind: 'savedialog', props: {}, caption: 'Jendela Save As: lokasi di atas, kotak File name/Nama file di tengah, tombol Save/Simpan di bawah.' },
        { t: 'steps', items: [
          'Tekan Ctrl + S. Jendela Save As/Simpan sebagai muncul.',
          'Pilih lokasi: Documents, lalu folder LATIHAN (buatan kita di Modul 0).',
          'Di kotak File name/Nama file, ketik nama yang JELAS: misalnya Surat Izin Tidak Masuk.',
          'Klik tombol Save/Simpan. Nama dokumen kini tampil di bilah judul paling atas — tanda dia sudah punya rumah.',
        ]},
        { t: 'warn', text: 'Nama file buruk: "Document1", "fix", "baru2", "asdf". Tiga bulan lagi kamu sendiri tidak tahu isinya. Nama file baik menyebut ISI dan kalau perlu TANGGAL: "Surat Izin Dimas 12 Juni". Di kantor, nama file yang jelas = tanda orang yang bisa dipercaya memegang arsip.' },
        { t: 'h', text: 'Save vs Save As — apa bedanya?' },
        { t: 'list', items: [
          'Save/Simpan (Ctrl + S) = menyimpan PERUBAHAN ke file yang sama. Setelah penyimpanan pertama, dia bekerja diam-diam tanpa jendela apa pun. Dipakai terus-menerus.',
          'Save As/Simpan sebagai (tombol F12, atau menu File lalu Save As) = menyimpan sebagai file BARU — untuk membuat salinan dengan nama atau tempat lain, sementara file asli tetap utuh. Contoh: "Surat Izin Andri" disimpan-sebagai "Surat Izin Rusdi", tinggal ganti nama orangnya.',
        ]},
        { t: 'tip', text: 'Jurus kantoran: jarang ada yang mengetik surat dari nol setiap hari. Mereka membuka surat lama, F12 (Save As) dengan nama baru, lalu mengubah isinya. Cepat, dan file lama selamat.' },
        { t: 'h', text: 'Membuka dokumen lama' },
        { t: 'list', items: [
          'Cara 1: buka File Explorer, masuk folder LATIHAN, dobel klik dokumennya.',
          'Cara 2: buka Word — layar awal menampilkan daftar Recent/Terbaru; klik nama dokumenmu.',
          'Cara 3 (di dalam Word): Ctrl + O lalu pilih filenya.',
        ]},
        { t: 'keys', items: [{ combo: ['Ctrl', 'O'], label: 'Open/Buka — membuka dokumen dari dalam Word' }]},
        { t: 'try', text: 'Ketik 2 kalimat, simpan ke Documents/LATIHAN dengan nama "Latihan Word [namamu]". Tutup Word. Buka lagi lewat File Explorer (dobel klik). Tambah satu kalimat, tekan Ctrl + S — perhatikan: tidak ada jendela muncul, perubahan tersimpan diam-diam. Terakhir, tekan F12 dan simpan salinan bernama "Latihan Word [namamu] versi 2".' },
        { t: 'glossary', items: [
          { term: 'Save', def: 'Simpan — menimpa file yang sama (Ctrl + S).' },
          { term: 'Save As', def: 'Simpan sebagai — melahirkan file baru (F12).' },
          { term: '.docx', def: 'Akhiran file dokumen Word.' },
          { term: 'Recent', def: 'Terbaru — daftar dokumen yang baru dibuka.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Pasangan tombol untuk MENYIMPAN yang harus jadi refleks…',
          options: ['Ctrl + S', 'Ctrl + P', 'Alt + F4', 'Ctrl + A'],
          answer: 0, explain: 'Ctrl + S — selesai satu paragraf, tekan. Mau berdiri, tekan dulu.' },
        { type: 'mc', q: 'Tombol pintas untuk langsung membuka jendela Save As/Simpan sebagai…',
          options: ['F12', 'F5', 'Esc', 'Ctrl + N'],
          answer: 0, explain: 'F12 = Save As. Jurus membuat salinan bernama baru dalam sekali tekan.' },
        { type: 'hotspot', q: 'Klik kotak tempat MENGETIK NAMA FILE pada jendela ini.',
          img: { kind: 'savedialog', props: {} }, accept: ['filename'],
          wrong: { savebtn: 'Itu tombol Save/Simpan — diklik TERAKHIR. Nama file diketik dulu di kotak panjang.', location: 'Itu lokasi penyimpanan. Kotak nama file ada di samping tulisan "File name".' },
          explain: 'Benar! Di situlah nama jelas dokumenmu diketik.' },
        { type: 'hotspot', q: 'Nama sudah diketik, lokasi sudah benar. Klik tombol untuk MENYELESAIKAN penyimpanan.',
          img: { kind: 'savedialog', props: {} }, accept: ['savebtn'],
          explain: 'Tepat — Save/Simpan. Dokumen kini hidup aman di folder pilihanmu.' },
        { type: 'mc', q: 'Kamu mau membuat SALINAN surat dengan nama lain tanpa mengubah aslinya. Gunakan…',
          options: ['Save (Ctrl + S)', 'Save As (F12)', 'Delete', 'Ctrl + Z'],
          answer: 1, wrong: { 0: 'Ctrl + S menimpa file yang sama. Untuk salinan baru, ada perintah satunya.' },
          explain: 'Save As/Simpan sebagai = lahir file baru, file lama tetap utuh.' },
        { type: 'mc', q: 'Nama file yang BAIK untuk surat izin sakit adalah…',
          options: ['Document1', 'fix banget', 'Surat Izin Sakit Andri 12 Juni', 'asdfgh'],
          answer: 2, explain: 'Nama menyebut isi (dan tanggal) — tiga bulan lagi tetap ketemu dalam 5 detik.' },
      ],
    },

    /* ============ BAB 4 ============ */
    {
      id: 'm1.b4', no: 4,
      title: 'Mempercantik huruf',
      desc: 'Bold, Italic, Underline, ukuran, jenis huruf, dan menyalin format.',
      blocks: [
        { t: 'p', text: 'Tiga tombol sakti di tab Home/Beranda: B (Bold/tebal), I (Italic/miring), U (Underline/garis bawah). Ingat aturan emas Bab 2: PILIH teksnya dulu sampai tersorot biru, baru klik tombolnya. Klik tombol yang sama sekali lagi untuk membatalkan efeknya.' },
        { t: 'img', kind: 'word', props: { highlight: ['bold', 'italic', 'underline'] }, caption: 'Tombol B, I, U di grup Font. Tombol yang sedang aktif tampak menyala.' },
        { t: 'keys', items: [
          { combo: ['Ctrl', 'B'], label: 'Bold/Tebal — judul dan kata penting' },
          { combo: ['Ctrl', 'I'], label: 'Italic/Miring — istilah asing' },
          { combo: ['Ctrl', 'U'], label: 'Underline/Garis bawah' },
        ]},
        { t: 'h', text: 'Ukuran dan jenis huruf' },
        { t: 'img', kind: 'word', props: { highlight: ['fontsize'] }, caption: 'Kotak angka di grup Font = ukuran huruf (font size). Kotak nama di sebelahnya = jenis huruf (font).' },
        { t: 'list', items: [
          'Ukuran standar dokumen kantor: 11 atau 12. Judul boleh 14\u201316.',
          'Jenis huruf aman dan resmi: Calibri, Arial, atau Times New Roman (banyak instansi pemerintah memintanya). Pilih satu, pakai konsisten di seluruh dokumen.',
          'Cara mengubah: pilih teksnya, klik kotak ukuran/jenis huruf, pilih nilainya — atau ketik angkanya langsung lalu Enter.',
        ]},
        { t: 'h', text: 'Ubah besar-kecil huruf tanpa mengetik ulang' },
        { t: 'keys', items: [{ combo: ['Shift', 'F3'], label: 'Memutar kapital: kecil semua, Besar Awal, BESAR SEMUA — pilih teks dulu' }]},
        { t: 'p', text: 'Salah mengetik judul dengan huruf kecil semua? Jangan dihapus — pilih teksnya, tekan Shift + F3 beberapa kali sampai bentuknya pas. Penghemat waktu favorit orang kantoran.' },
        { t: 'warn', text: 'Dokumen resmi bukan undangan ulang tahun: jangan campur banyak jenis huruf dan warna-warni. Satu jenis huruf, hitam, rapi — itu yang terlihat profesional dan enak dibaca atasan.' },
        { t: 'try', text: 'Di dokumen latihanmu: tebalkan namamu (pilih, Ctrl + B), miringkan satu kata, garis bawahi satu kata, besarkan baris pertama jadi 14, lalu pilih baris itu dan tekan Shift + F3 sampai jadi BESAR SEMUA. Jangan lupa Ctrl + S.' },
        { t: 'glossary', items: [
          { term: 'Bold', def: 'Tebal — untuk penekanan (Ctrl + B).' },
          { term: 'Italic', def: 'Miring (Ctrl + I).' },
          { term: 'Underline', def: 'Garis bawah (Ctrl + U).' },
          { term: 'Font', def: 'Jenis huruf, misalnya Calibri atau Arial.' },
          { term: 'Font size', def: 'Ukuran huruf; 11\u201312 untuk isi dokumen.' },
        ]},
      ],
      quiz: [
        { type: 'hotspot', q: 'Klik tombol untuk MENEBALKAN teks yang sudah dipilih.',
          img: { kind: 'word', props: {} }, accept: ['bold'],
          wrong: { italic: 'Itu I — Italic/miring. Tombol penebal adalah huruf B tegak gemuk di sebelah kirinya.', underline: 'Itu U — Underline/garis bawah. Tombol penebal adalah huruf B.' },
          explain: 'Benar! B untuk Bold/tebal. Jalan pintasnya Ctrl + B.' },
        { type: 'hotspot', q: 'Klik kotak untuk mengubah UKURAN huruf.',
          img: { kind: 'word', props: {} }, accept: ['fontsize'],
          explain: 'Tepat — kotak angka itu font size/ukuran huruf. 11\u201312 untuk isi, 14\u201316 untuk judul.' },
        { type: 'mc', q: 'Urutan yang BENAR untuk menebalkan kata "PENTING"…',
          options: ['Klik tombol B, lalu cari katanya', 'Pilih kata "PENTING" sampai tersorot, lalu tekan Ctrl + B', 'Hapus katanya, ketik ulang lebih keras', 'Tekan Ctrl + S dua kali'],
          answer: 1, explain: 'Pilih dulu, baru perintah — aturan emas yang sama untuk semua perapian.' },
        { type: 'mc', q: 'Judul terlanjur diketik huruf kecil semua. Cara tercepat menjadikannya BESAR SEMUA…',
          options: ['Hapus lalu ketik ulang', 'Pilih teksnya, tekan Shift + F3 sampai kapital', 'Tekan Caps Lock saja', 'Cetak lalu tulis tangan'],
          answer: 1, explain: 'Shift + F3 memutar bentuk kapital tanpa mengetik ulang.' },
        { type: 'mc', q: 'Ukuran huruf yang wajar untuk ISI surat resmi…',
          options: ['8', '11 atau 12', '36', '72'],
          answer: 1, explain: '11\u201312 nyaman dibaca. Ukuran raksasa hanya untuk spanduk.' },
      ],
    },

    /* ============ BAB 5 ============ */
    {
      id: 'm1.b5', no: 5,
      title: 'Merapikan paragraf',
      desc: 'Rata kiri/tengah/kanan/justify, spasi baris, dan anatomi surat resmi.',
      blocks: [
        { t: 'p', text: 'Perataan menentukan wajah dokumen. Kabar baiknya: untuk merapikan paragraf, cukup letakkan kursor teks DI DALAM paragrafnya — tidak perlu memblok semuanya — lalu klik tombol perataan.' },
        { t: 'img', kind: 'word', props: { highlight: ['alignleft', 'aligncenter', 'alignright', 'justify'] }, caption: 'Empat tombol perataan di grup Paragraph: Align Left/rata kiri, Center/tengah, Align Right/rata kanan, Justify/rata kiri-kanan.' },
        { t: 'keys', items: [
          { combo: ['Ctrl', 'L'], label: 'Align Left/Rata kiri — bawaan untuk tulisan biasa' },
          { combo: ['Ctrl', 'E'], label: 'Center/Rata tengah — untuk JUDUL' },
          { combo: ['Ctrl', 'R'], label: 'Align Right/Rata kanan — untuk tanggal surat' },
          { combo: ['Ctrl', 'J'], label: 'Justify — isi surat resmi, rapi kiri dan kanan' },
        ]},
        { t: 'h', text: 'Anatomi surat resmi Indonesia' },
        { t: 'steps', items: [
          'Judul (mis. SURAT IZIN TIDAK MASUK KERJA): rata tengah, tebal, ukuran 14.',
          'Tempat dan tanggal (mis. Batam, 12 Juni 2026): rata kanan.',
          'Pembuka (Kepada Yth. ...): rata kiri.',
          'Isi surat: justify dengan spasi 1.5 — kedua tepi lurus seperti koran.',
          'Penutup dan tanda tangan: rata kiri atau kanan sesuai kebiasaan kantor.',
        ]},
        { t: 'h', text: 'Spasi antar baris' },
        { t: 'p', text: 'Tulisan terasa sesak? Longgarkan: pilih paragrafnya, lalu di grup Paragraph klik tombol Line and Paragraph Spacing (ikon garis dengan panah naik-turun) dan pilih 1.5. Dokumen resmi Indonesia umumnya memakai spasi 1.5; skripsi bahkan 2.' },
        { t: 'warn', text: 'Jangan membuat judul "di tengah" dengan menekan spasi berkali-kali — di laptop lain posisinya pasti meleset. Rata tengah yang benar hanya satu: Ctrl + E.' },
        { t: 'try', text: 'Bangun kerangka surat di dokumen latihanmu mengikuti anatomi di atas: judul tengah-tebal-14, tanggal rata kanan, isi 2 paragraf justify spasi 1.5. Ctrl + S!' },
        { t: 'glossary', items: [
          { term: 'Perataan', def: 'Posisi paragraf: kiri, tengah, kanan, atau justify.' },
          { term: 'Justify', def: 'Rata kiri dan kanan sekaligus — gaya surat resmi.' },
          { term: 'Spasi baris', def: 'Jarak antar baris; 1.5 paling umum untuk dokumen resmi.' },
        ]},
      ],
      quiz: [
        { type: 'hotspot', q: 'Klik tombol untuk membuat judul berada di TENGAH halaman.',
          img: { kind: 'word', props: {} }, accept: ['aligncenter'],
          wrong: { alignleft: 'Itu rata kiri. Perhatikan ikonnya — yang rata tengah, garis-garisnya terpusat.', justify: 'Itu Justify — semua garisnya sama panjang. Rata tengah garisnya terpusat.' },
          explain: 'Benar! Center/rata tengah, jalan pintasnya Ctrl + E.' },
        { type: 'mc', q: 'Isi surat resmi yang kedua tepinya lurus rapi memakai perataan…',
          options: ['Rata kiri', 'Rata kanan', 'Rata tengah', 'Justify (Ctrl + J)'],
          answer: 3, explain: 'Justify — gaya koran dan surat dinas.' },
        { type: 'mc', q: 'Tempat dan tanggal surat ("Batam, 12 Juni 2026") biasanya diletakkan…',
          options: ['Rata kanan (Ctrl + R)', 'Rata tengah', 'Di halaman dua', 'Di dalam tabel'],
          answer: 0, explain: 'Rata kanan — kebiasaan surat Indonesia.' },
        { type: 'mc', q: 'Membuat judul berada di tengah yang BENAR adalah…',
          options: ['Menekan spasi berkali-kali sampai terlihat tengah', 'Kursor di paragraf judul, tekan Ctrl + E', 'Menambah Enter di kiri judul', 'Memperbesar huruf saja'],
          answer: 1, explain: 'Spasi manual pasti meleset di laptop lain. Ctrl + E selalu tepat di tengah.' },
      ],
    },

    /* ============ BAB 6 ============ */
    {
      id: 'm1.b6', no: 6,
      title: 'Daftar dan penomoran',
      desc: 'Bullets, Numbering, dan anak daftar dengan Tab.',
      blocks: [
        { t: 'p', text: 'Daftar membuat informasi gampang dibaca: daftar belanja, urutan kerja, susunan acara, perlengkapan rapat. Word punya dua jenis: Bullets/daftar titik untuk hal yang urutannya bebas, dan Numbering/daftar angka untuk langkah yang berurutan.' },
        { t: 'img', kind: 'word', props: { highlight: ['bullets', 'numbering'] }, caption: 'Dua tombol daftar di grup Paragraph: Bullets (titik-titik) dan Numbering (1-2-3).' },
        { t: 'steps', items: [
          'Klik tombol Numbering — angka 1. muncul otomatis.',
          'Ketik isi pertama, tekan Enter — angka 2. muncul sendiri.',
          'Terus sampai selesai.',
          'Mau berhenti dari daftar? Tekan Enter pada baris kosong (atau klik lagi tombol Numbering).',
        ]},
        { t: 'h', text: 'Anak daftar' },
        { t: 'keys', items: [
          { combo: ['Tab'], label: 'Masuk satu tingkat — jadi anak daftar (1 menjadi a)' },
          { combo: ['Shift', 'Tab'], label: 'Keluar satu tingkat — kembali ke daftar utama' },
        ]},
        { t: 'tip', text: 'Jangan membuat nomor dengan mengetik "1." manual — kalau ada isi disisipkan di tengah, kamu harus mengubah semua nomor sendiri. Tombol Numbering mengurus penomoran ulang OTOMATIS: sisipkan di mana pun, angka menyesuaikan sendiri.' },
        { t: 'try', text: 'Buat daftar bernomor "Rencana Besok" berisi 4 kegiatan. Jadikan kegiatan ke-2 punya 2 anak daftar (tekan Tab). Lalu buat daftar Bullets "Barang Bawaan" berisi 3 barang. Ctrl + S.' },
        { t: 'glossary', items: [
          { term: 'Bullets', def: 'Daftar bertanda titik — urutan tidak penting.' },
          { term: 'Numbering', def: 'Daftar berangka — untuk langkah berurutan.' },
          { term: 'Anak daftar', def: 'Daftar di dalam daftar; dibuat dengan Tab.' },
        ]},
      ],
      quiz: [
        { type: 'hotspot', q: 'Klik tombol untuk membuat daftar BERNOMOR (1, 2, 3).',
          img: { kind: 'word', props: {} }, accept: ['numbering'],
          wrong: { bullets: 'Itu Bullets — daftar titik. Yang bernomor ada angka kecil 1-2-3 di ikonnya, tepat di sebelahnya.' },
          explain: 'Benar! Numbering — angkanya melanjutkan diri sendiri tiap kamu menekan Enter.' },
        { type: 'mc', q: 'Saat sedang membuat daftar, menekan Tab di awal baris akan…',
          options: ['Menghapus daftarnya', 'Membuat baris itu jadi ANAK daftar (masuk satu tingkat)', 'Menyimpan dokumen', 'Mencetak dokumen'],
          answer: 1, explain: 'Tab masuk, Shift + Tab keluar — naik-turun tingkat daftar.' },
        { type: 'mc', q: 'Daftar langkah memasak yang URUTANNYA penting sebaiknya memakai…',
          options: ['Bullets (titik)', 'Numbering (angka)', 'Huruf tebal semua', 'Spasi panjang'],
          answer: 1, explain: 'Urutan penting = angka. Kalau urutan bebas, Bullets cukup.' },
        { type: 'mc', q: 'Keunggulan tombol Numbering dibanding mengetik "1." manual…',
          options: ['Hurufnya lebih besar', 'Nomor menyesuaikan OTOMATIS saat isi disisipkan atau dihapus', 'Dokumennya jadi berwarna', 'Tidak ada bedanya'],
          answer: 1, explain: 'Penomoran otomatis — sisipkan di tengah, semua nomor bergeser sendiri.' },
      ],
    },

    /* ============ BAB 7 ============ */
    {
      id: 'm1.b7', no: 7,
      title: 'Salin, pindah, dan cari di dalam dokumen',
      desc: 'Ctrl C/X/V/Z/Y di dalam tulisan, plus Ctrl+F untuk menemukan kata.',
      blocks: [
        { t: 'p', text: 'Jurus salin-tempel dari Modul 0 bekerja juga di DALAM tulisan — dan inilah yang membuatmu cepat: memindah kalimat, menggandakan bagian, membatalkan kesalahan tanpa panik.' },
        { t: 'keys', items: [
          { combo: ['Ctrl', 'C'], label: 'Copy/Salin teks terpilih' },
          { combo: ['Ctrl', 'X'], label: 'Cut/Potong teks terpilih (untuk dipindah)' },
          { combo: ['Ctrl', 'V'], label: 'Paste/Tempel di posisi kursor teks' },
          { combo: ['Ctrl', 'Z'], label: 'Undo/Batalkan — bisa berkali-kali, mundur terus' },
          { combo: ['Ctrl', 'Y'], label: 'Redo/Maju lagi (kebalikan Ctrl + Z)' },
        ]},
        { t: 'steps', items: [
          'Memindah kalimat: pilih kalimatnya, Ctrl + X (kalimat hilang — tenang, dia di saku digital).',
          'Klik posisi tujuan — kursor teks pindah ke sana.',
          'Ctrl + V. Kalimat muncul di rumah barunya.',
        ]},
        { t: 'h', text: 'Mencari kata di dokumen panjang' },
        { t: 'keys', items: [{ combo: ['Ctrl', 'F'], label: 'Find/Cari — semua kata yang cocok disorot kuning' }]},
        { t: 'p', text: 'Tekan Ctrl + F, ketik kata yang dicari, dan Word menyorot semuanya. Di dokumen 20 halaman, ini menghemat bermenit-menit mata melotot. Versi lanjutannya: Ctrl + H (Replace/Ganti) — mengganti satu kata di SELURUH dokumen sekali jalan, misalnya semua "2025" menjadi "2026".' },
        { t: 'keys', items: [{ combo: ['Ctrl', 'H'], label: 'Replace/Ganti — cari dan ganti kata di seluruh dokumen' }]},
        { t: 'tip', text: 'Ctrl + Z adalah sahabat terbaik pemula: apa pun kekacauannya — teks terhapus, format berantakan, tempel salah tempat — tekan Ctrl + Z sampai keadaan pulih. Word mengingat puluhan langkah ke belakang.' },
        { t: 'try', text: 'Di dokumen latihan: pindahkan kalimat terakhir menjadi kalimat pertama dengan Ctrl + X dan Ctrl + V. Hapus satu paragraf, hidupkan lagi dengan Ctrl + Z. Cari namamu dengan Ctrl + F. Terakhir, pakai Ctrl + H untuk mengganti satu kata di seluruh dokumen.' },
        { t: 'glossary', items: [
          { term: 'Cut', def: 'Potong — memotong untuk dipindahkan (Ctrl + X).' },
          { term: 'Undo', def: 'Batalkan langkah terakhir (Ctrl + Z).' },
          { term: 'Find', def: 'Cari kata di dokumen (Ctrl + F).' },
          { term: 'Replace', def: 'Ganti kata di seluruh dokumen (Ctrl + H).' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Memindahkan satu kalimat ke tempat lain: pilih kalimat, lalu…',
          options: ['Ctrl + C, klik tujuan, Ctrl + V (kalimat jadi dua)', 'Ctrl + X, klik tujuan, Ctrl + V', 'Tekan Delete saja', 'Ctrl + S berkali-kali'],
          answer: 1, wrong: { 0: 'Itu MENYALIN — kalimatnya jadi dobel. Untuk memindah, potong dulu dengan X.' },
          explain: 'Cut lalu Paste — kalimat pindah rumah, tidak berganda.' },
        { type: 'mc', q: 'Tidak sengaja menghapus satu paragraf penting. Penyelamatnya…',
          options: ['Ctrl + Z', 'Ctrl + P', 'Tutup Word cepat-cepat', 'Tekan Enter banyak-banyak'],
          answer: 0, explain: 'Ctrl + Z — mundur selangkah demi selangkah sampai paragrafmu hidup lagi.' },
        { type: 'mc', q: 'Mengganti semua tulisan "2025" menjadi "2026" di dokumen 30 halaman paling cepat dengan…',
          options: ['Ctrl + H (Replace/Ganti)', 'Mencari satu-satu dengan mata', 'Mengetik ulang dokumennya', 'Ctrl + B'],
          answer: 0, explain: 'Ctrl + H — sekali jalan, seluruh dokumen terganti.' },
        { type: 'mc', q: 'Mencari kata "honorarium" di dokumen 15 halaman paling cepat dengan…',
          options: ['Membaca dari awal pelan-pelan', 'Ctrl + F lalu ketik katanya', 'Mencetak dulu semuanya', 'Ctrl + A'],
          answer: 1, explain: 'Ctrl + F — Word yang melotot, bukan matamu.' },
      ],
    },

    /* ============ BAB 8 ============ */
    {
      id: 'm1.b8', no: 8,
      title: 'Mencetak dan membuat PDF',
      desc: 'Ctrl+P, pratinjau, mengatur halaman dan kertas, serta menyimpan PDF.',
      blocks: [
        { t: 'p', text: 'Dokumen selesai dan tersimpan — saatnya jadi kertas. Satu kebiasaan pekerja teliti: SELALU lihat pratinjau (preview) dulu sebelum menekan Print/Cetak, supaya tidak ada kertas dan tinta terbuang untuk hasil yang salah.' },
        { t: 'keys', items: [{ combo: ['Ctrl', 'P'], label: 'Print/Cetak — buka layar cetak beserta pratinjaunya' }]},
        { t: 'img', kind: 'printdialog', props: {}, caption: 'Layar Print/Cetak: tombol Print, Copies/jumlah salinan, pilihan printer, dan pratinjau dokumen di kanan.' },
        { t: 'steps', items: [
          'Tekan Ctrl + P.',
          'Periksa PRATINJAU di sebelah kanan: judul di tengah? tanggal di kanan? tidak ada halaman kosong nyasar?',
          'Pastikan nama printer berstatus Ready/Siap. Status Offline berarti printer mati atau kabelnya lepas.',
          'Atur Copies/salinan kalau butuh lebih dari satu lembar.',
          'Klik tombol Print/Cetak. Ambil hasilnya di printer.',
        ]},
        { t: 'tip', text: 'Mau mencetak halaman tertentu saja? Di bagian Settings, ganti "Print All Pages/Cetak semua halaman" menjadi Custom Print, lalu ketik nomornya — 2 (halaman dua saja) atau 1-3 (halaman satu sampai tiga). Hemat kertas, hemat tinta.' },
        { t: 'h', text: 'Ukuran kertas: A4 dan F4' },
        { t: 'p', text: 'Kantor Indonesia memakai dua ukuran: A4 (standar internasional) dan F4/Folio (sedikit lebih panjang — favorit instansi pemerintah). Mengaturnya: tab Layout/Tata letak, klik Size/Ukuran, pilih. Kalau hasil cetak terpotong bawahnya, biasanya ukuran kertas di Word tidak sama dengan kertas di printer.' },
        { t: 'h', text: 'Menyimpan sebagai PDF' },
        { t: 'p', text: 'PDF adalah bentuk "beku" dokumen: tampilannya tidak berubah di HP atau komputer mana pun, dan tidak bisa terketik-ketik tanpa sengaja — sempurna untuk dikirim lewat WA atau email. Caranya: di daftar printer pada layar Ctrl + P, pilih "Microsoft Print to PDF", klik Print/Cetak, lalu beri nama dan simpan — persis seperti Save As.' },
        { t: 'warn', text: 'Mengirim dokumen penting ke orang lain? Kirim PDF-nya, bukan file Word-nya — supaya isinya tidak bergeser atau terubah di laptop orang.' },
        { t: 'try', text: 'Buka dokumen latihanmu, tekan Ctrl + P, periksa pratinjau baik-baik. Cek ukuran kertas di Layout, Size. Lalu ubah printer menjadi Microsoft Print to PDF dan simpan PDF-nya di folder LATIHAN dengan nama yang jelas.' },
        { t: 'glossary', items: [
          { term: 'Pratinjau', def: 'Preview — tampilan hasil cetak sebelum dicetak.' },
          { term: 'Copies', def: 'Salinan — jumlah lembar yang dicetak.' },
          { term: 'F4 / Folio', def: 'Kertas sedikit lebih panjang dari A4; umum di kantor Indonesia.' },
          { term: 'PDF', def: 'Dokumen beku yang tampil sama di semua perangkat.' },
        ]},
      ],
      quiz: [
        { type: 'mc', q: 'Pasangan tombol untuk membuka layar cetak…',
          options: ['Ctrl + P', 'Ctrl + S', 'Ctrl + F', 'Alt + Tab'],
          answer: 0, explain: 'Ctrl + P — Print/Cetak. Pratinjaunya langsung tampil di kanan.' },
        { type: 'hotspot', q: 'Pratinjau sudah diperiksa dan benar. Klik tombol untuk MULAI MENCETAK.',
          img: { kind: 'printdialog', props: {} }, accept: ['printbtn'],
          wrong: { copies: 'Itu Copies/jumlah salinan. Tombol pencetaknya yang besar berwarna oranye bertuliskan Print.', printer: 'Itu pilihan printer. Tombol pencetaknya yang besar di atas.' },
          explain: 'Benar! Print/Cetak — dan kertas pun keluar.' },
        { type: 'mc', q: 'Hasil cetak selalu terpotong di bagian bawah. Kemungkinan besar penyebabnya…',
          options: ['Ukuran kertas di Word tidak sama dengan kertas di printer (A4 vs F4)', 'Tintanya habis', 'Dokumennya terlalu bagus', 'Laptopnya kepanasan'],
          answer: 0, explain: 'Samakan: tab Layout, Size di Word dengan kertas yang terpasang di printer.' },
        { type: 'mc', q: 'Dokumen penting mau dikirim lewat WA agar tidak berubah-ubah. Bentuk terbaiknya…',
          options: ['File Word (.docx) langsung', 'PDF', 'Foto layar laptop', 'Diketik ulang di WA'],
          answer: 1, explain: 'PDF — beku, rapi, dan terbuka sama persis di HP siapa pun.' },
      ],
    },
  ],

  /* ============ UJIAN PRAKTEK (unggah file nyata) ============ */
  praktik: {
    id: 'm1.praktik',
    title: 'Ujian praktek — Surat Izin',
    pass: 80,
    ext: ['docx'],
    brief: [
      'Buka Word, buat dokumen baru (Blank document).',
      'Ketik surat izin tidak masuk kerja versimu sendiri, minimal 40 kata.',
      'Baris pertama: judul yang memuat kata SURAT IZIN — tebal (Ctrl + B) dan rata tengah (Ctrl + E).',
      'Sertakan satu daftar bernomor (Numbering), misalnya daftar pekerjaan yang dititipkan.',
      'Beri sentuhan: minimal satu kata miring (Ctrl + I) atau bergaris bawah (Ctrl + U).',
      'Simpan sebagai .docx dengan nama jelas, lalu unggah file itu di sini.',
    ],
    rubric: [
      { id: 'docx-valid', label: 'File Word (.docx) terbaca dengan baik' },
      { id: 'judul-surat', label: 'Memuat judul berisi kata "SURAT IZIN"' },
      { id: 'judul-bold', label: 'Judul ditebalkan (Bold)' },
      { id: 'judul-center', label: 'Judul rata tengah (Center)' },
      { id: 'ada-list', label: 'Ada daftar bernomor / bullets' },
      { id: 'gaya-tambahan', label: 'Ada teks miring atau bergaris bawah' },
      { id: 'kata-40', label: 'Panjang isi minimal 40 kata' },
    ],
  },

  /* ============ UJIAN AKHIR ============ */
  final: {
    id: 'm1.final',
    pass: 85,
    title: 'Ujian akhir Modul 1',
    intro:
      'Ujian ini berisi 18 soal dari semua bab Word dasar. Setiap soal hanya boleh dijawab SATU KALI. Nilai lulus: 85 (boleh salah maksimal 2 soal). Belum lulus? Pelajari pembahasannya, buka lagi bab yang ragu, lalu ulangi — soal akan diacak ulang.',
    questions: [
      { type: 'mc', q: 'Cara paling cepat membuka Word…',
        options: ['Start, ketik "word", Enter', 'Klik kanan desktop', 'Buka Recycle Bin', 'Tekan F12'],
        answer: 0, explain: 'Jurus Start + ketik — untuk semua aplikasi.' },
      { type: 'hotspot', q: 'Klik tempat MENGETIK pada jendela Word ini.',
        img: { kind: 'word', props: {} }, accept: ['page'],
        explain: 'Halaman putih di tengah — di situ kursor teks berkedip.' },
      { type: 'mc', q: 'Memilih SATU KATA paling cepat dengan…',
        options: ['Dobel klik pada katanya', 'Ctrl + P', 'Klik kanan tiga kali', 'Menekan Spasi'],
        answer: 0, explain: 'Dobel klik = satu kata; tiga klik = satu paragraf.' },
      { type: 'mc', q: 'Melompat ke AKHIR baris dengan satu tombol…',
        options: ['End', 'Esc', 'Tab', 'F5'],
        answer: 0, explain: 'End = akhir baris, Home = awal baris.' },
      { type: 'mc', q: 'Tombol yang harus jadi REFLEKS setiap selesai mengetik sebagian…',
        options: ['Ctrl + S', 'Ctrl + X', 'Esc', 'Ctrl + F'],
        answer: 0, explain: 'Ctrl + S — Save/Simpan, dokumen aman dari listrik padam.' },
      { type: 'mc', q: 'Tombol pintas yang langsung membuka jendela Save As/Simpan sebagai…',
        options: ['F12', 'F2', 'Ctrl + N', 'Alt + Tab'],
        answer: 0, explain: 'F12 — jurus membuat salinan bernama baru dalam sekali tekan.' },
      { type: 'hotspot', q: 'Klik kotak tempat mengetik NAMA FILE.',
        img: { kind: 'savedialog', props: {} }, accept: ['filename'],
        explain: 'Kotak panjang di samping "File name/Nama file".' },
      { type: 'mc', q: 'Nama file paling BAIK…',
        options: ['Surat Undangan RT 05 Agustus', 'Document2', 'finalbangetfix', 'zzz'],
        answer: 0, explain: 'Nama menyebut isi — mudah ditemukan kapan pun.' },
      { type: 'hotspot', q: 'Klik tombol untuk MENEBALKAN teks terpilih.',
        img: { kind: 'word', props: {} }, accept: ['bold'],
        explain: 'B — Bold/tebal. Jalan pintas Ctrl + B.' },
      { type: 'mc', q: 'Sebelum memberi perintah tebal/miring/besar, teks harus…',
        options: ['Dipilih (diblok) dulu', 'Dihapus dulu', 'Dicetak dulu', 'Disimpan sebagai PDF'],
        answer: 0, explain: 'Pilih dulu, baru perintah — aturan emas Word.' },
      { type: 'mc', q: 'Mengubah tulisan kecil menjadi BESAR SEMUA tanpa mengetik ulang…',
        options: ['Pilih teks, tekan Shift + F3', 'Hapus lalu ketik ulang', 'Tekan Caps Lock saja', 'Ctrl + P'],
        answer: 0, explain: 'Shift + F3 memutar bentuk kapital.' },
      { type: 'mc', q: 'Judul surat di tengah halaman memakai…',
        options: ['Ctrl + E (Center/rata tengah)', 'Spasi berkali-kali', 'Ctrl + Z', 'Tab berkali-kali'],
        answer: 0, explain: 'Spasi manual pasti meleset di laptop lain — Ctrl + E selalu tepat.' },
      { type: 'hotspot', q: 'Klik tombol perataan JUSTIFY (rata kiri-kanan).',
        img: { kind: 'word', props: {} }, accept: ['justify'],
        explain: 'Ikon dengan semua garis sama panjang — gaya surat resmi.' },
      { type: 'mc', q: 'Daftar LANGKAH yang urutannya penting memakai…',
        options: ['Numbering (angka)', 'Bullets (titik)', 'Huruf kapital semua', 'Garis bawah'],
        answer: 0, explain: 'Urutan penting = angka, dan Word menomori ulang otomatis.' },
      { type: 'mc', q: 'MEMINDAHKAN kalimat (bukan menggandakan): pilih kalimat lalu…',
        options: ['Ctrl + X, klik tujuan, Ctrl + V', 'Ctrl + C, Ctrl + V', 'Delete, lalu ketik ulang', 'Ctrl + B'],
        answer: 0, explain: 'Cut lalu Paste — pindah rumah, tidak berganda.' },
      { type: 'mc', q: 'Mengganti semua "2025" menjadi "2026" di seluruh dokumen sekali jalan…',
        options: ['Ctrl + H (Replace/Ganti)', 'Ctrl + F saja', 'Mengetik ulang', 'Ctrl + A lalu Delete'],
        answer: 0, explain: 'Replace mencari sekaligus mengganti.' },
      { type: 'hotspot', q: 'Pratinjau sudah benar. Klik tombol untuk MENCETAK.',
        img: { kind: 'printdialog', props: {} }, accept: ['printbtn'],
        explain: 'Tombol Print/Cetak besar — setelah pratinjau diperiksa.' },
      { type: 'mc', q: 'Mengirim dokumen penting lewat WA agar tampil sama di semua HP…',
        options: ['Kirim sebagai PDF', 'Kirim file .docx', 'Kirim foto layar', 'Ketik ulang di chat'],
        answer: 0, explain: 'PDF — bentuk beku dokumen.' },
    ],
  },
}

// 8 bab + ujian praktek + ujian akhir = 10 langkah Modul 1.
export const M1_ITEMS = [
  'm1.b1', 'm1.b2', 'm1.b3', 'm1.b4', 'm1.b5', 'm1.b6', 'm1.b7', 'm1.b8', 'm1.praktik', 'm1.final',
]
