// P3K — Pertolongan Pertama Pada Komputer.
// "1001" masalah umum dan jurus cepat menyelesaikannya, berbagi halaman dengan Kamus Pintasan.
// Tiap entri: q = masalahnya, fix = cara menyelesaikan, jurus = nama jurus (chip),
// k = tombol kombinasi (opsional, tampil sebagai kbd seperti kamus).

export const P3K = [
  {
    cat: 'Komputer pada umumnya',
    items: [
      { q: 'Layar membeku / laptop hang, tidak bergerak sama sekali',
        fix: 'Sabar 30 detik dulu — sering pulih sendiri. Masih beku? Tekan Ctrl + Alt + Delete → Task Manager → pilih program bertuliskan "Not responding" → End Task.',
        k: ['Ctrl', 'Alt', 'Delete'], jurus: 'Task Manager' },
      { q: 'Satu program macet tidak mau ditutup',
        fix: 'Klik kanan ikon programnya di taskbar → Close window. Tetap bandel: Ctrl + Alt + Delete → Task Manager → End Task program itu saja — yang lain tetap aman.',
        k: ['Ctrl', 'Alt', 'Delete'], jurus: 'End Task' },
      { q: 'Laptop terasa lambat sekali',
        fix: 'Tutup program dan tab yang tidak sedang dipakai (laptop seperti meja: makin penuh makin sempit). Belum membaik: Restart — obat paling mujarab nomor satu.',
        jurus: 'Tutup & Restart' },
      { q: 'Tidak sengaja menghapus file',
        fix: 'Tenang, belum hilang. Buka Recycle Bin di Desktop → klik kanan file → Restore — file pulang ke tempat asalnya.',
        jurus: 'Recycle Bin → Restore' },
      { q: 'File ada tapi lupa disimpan di mana',
        fix: 'Buka File Explorer → ketik nama filenya di kotak Search kanan atas. Atau buka aplikasinya (Word/Excel) → File → Recent: daftar file yang baru dibuka.',
        jurus: 'Search / Recent' },
      { q: 'Wi-Fi tidak tersambung',
        fix: 'Klik ikon Wi-Fi di pojok kanan taskbar → pastikan Wi-Fi menyala & mode pesawat mati → pilih nama jaringan → masukkan sandi dengan teliti. Masih gagal: restart laptop, lalu restart router (cabut listriknya 10 detik).',
        jurus: 'Ikon Wi-Fi' },
      { q: 'Jendela "hilang" tertumpuk jendela lain',
        fix: 'Tekan Alt + Tab untuk melihat dan memilih semua jendela yang terbuka. Mau menata dua jendela berdampingan: Win + Panah kiri/kanan — jurus belah layar.',
        k: ['Alt', 'Tab'], jurus: 'Lihat semua jendela' },
      { q: 'Tidak sengaja menutup file sebelum menyimpan',
        fix: 'Buka lagi aplikasinya — biasanya muncul panel Document Recovery / AutoRecover berisi versi terakhir. Pelajarannya seumur hidup: Ctrl + S tiap dua menit.',
        k: ['Ctrl', 'S'], jurus: 'AutoRecover' },
      { q: 'Tampilan layar mendadak terlalu besar / terlalu kecil',
        fix: 'Itu zoom yang tergeser. Ctrl + Plus memperbesar, Ctrl + Minus memperkecil; di browser Ctrl + 0 mengembalikan ke 100%. Sering kejadian karena Ctrl tertekan sambil memutar roda mouse.',
        k: ['Ctrl', '0'], jurus: 'Reset zoom' },
      { q: 'KETIKAN JADI HURUF BESAR SEMUA',
        fix: 'Tombol Caps Lock tertekan tanpa sengaja — tekan sekali lagi untuk mematikannya (lampu indikatornya padam).',
        jurus: 'Caps Lock' },
      { q: 'Mau meninggalkan meja / mau pulang',
        fix: 'Tinggal sebentar: Win + L — layar terkunci, kerjaan aman. Pulang: simpan semua (Ctrl + S), tutup aplikasi, Start → Shut down. Tombol power ditekan lama HANYA untuk darurat hang total.',
        k: ['Win', 'L'], jurus: 'Kunci / Shut down' },
      { q: 'Suara tidak keluar',
        fix: 'Klik ikon speaker di taskbar → naikkan volume & pastikan tidak ter-mute (ikon dicoret). Pakai speaker/headset: cek kabel atau sambungan Bluetooth-nya.',
        jurus: 'Ikon speaker' },
    ],
  },
  {
    cat: 'Word',
    items: [
      { q: 'Mengetik di tengah kalimat malah MENIMPA huruf di depannya',
        fix: 'Tombol Insert tertekan (mode timpa). Tekan Insert sekali lagi — kembali ke mode sisip yang normal.',
        jurus: 'Tekan Insert' },
      { q: 'Salah hapus / salah edit / dokumen mendadak berantakan',
        fix: 'Ctrl + Z membatalkan langkah terakhir — boleh ditekan berkali-kali mundur jauh. Kelewatan mundur? Ctrl + Y maju lagi.',
        k: ['Ctrl', 'Z'], jurus: 'Undo' },
      { q: 'Ada garis merah / biru bergelombang di bawah kata',
        fix: 'Itu penanda ejaan & tata bahasa — TIDAK ikut tercetak. Klik kanan katanya untuk melihat usulan perbaikan, atau abaikan bila memang nama orang/tempat.',
        jurus: 'Klik kanan kata' },
      { q: 'Menempel teks dari internet, formatnya ikut kacau',
        fix: 'Tempel tanpa format: Ctrl + Shift + V, atau klik panah kecil tombol Paste → Keep Text Only — teksnya masuk, gayanya mengikuti dokumenmu.',
        k: ['Ctrl', 'Shift', 'V'], jurus: 'Paste polos' },
      { q: 'Jarak antar baris / antar paragraf terlalu renggang',
        fix: 'Blok teksnya → tab Home → ikon Line and Paragraph Spacing (panah atas-bawah) → pilih 1.0 atau 1.15, dan klik Remove Space After Paragraph.',
        jurus: 'Line Spacing' },
      { q: 'Ada halaman kosong di akhir yang tidak bisa dihapus',
        fix: 'Klik di halaman kosong itu → tekan Ctrl + Shift + 8 untuk menampilkan tanda paragraf (¶) → hapus tanda ¶ / Page Break yang tersisa dengan Backspace. Tekan Ctrl + Shift + 8 lagi untuk menyembunyikan.',
        k: ['Ctrl', 'Shift', '8'], jurus: 'Tampilkan ¶' },
      { q: 'Tulisan terlanjur huruf besar semua / kecil semua',
        fix: 'Tidak perlu mengetik ulang: blok teksnya → tekan Shift + F3 berulang — berputar antara kecil semua, Besar Tiap Kata, dan BESAR SEMUA.',
        k: ['Shift', 'F3'], jurus: 'Putar kapital' },
      { q: 'Gambar tidak mau digeser ke posisi yang diinginkan',
        fix: 'Klik gambarnya → klik ikon Layout Options yang muncul di pojoknya → pilih Square (With Text Wrapping) — gambar jadi bebas digeser dan teks mengalir di sekitarnya.',
        jurus: 'Layout Options' },
      { q: 'Penomoran daftar kacau — lanjut dari daftar lama / tidak mulai dari 1',
        fix: 'Klik kanan pada nomor yang salah → pilih Restart at 1 (mulai dari satu) atau Continue Numbering (melanjutkan) sesuai kebutuhan.',
        jurus: 'Klik kanan nomor' },
      { q: 'Word tertutup / mati listrik sebelum sempat menyimpan',
        fix: 'Buka Word lagi — panel Document Recovery biasanya menawarkan versi penyelamatan. Tidak muncul: File → Info → Manage Document → Recover Unsaved Documents.',
        jurus: 'Document Recovery' },
      { q: 'Hasil cetak terpotong / tidak rapi',
        fix: 'SELALU intip dulu: File → Print menampilkan pratinjau persis hasil kertas. Terpotong? Tab Layout → Margins → Normal, dan pastikan ukuran kertas A4.',
        jurus: 'Print Preview' },
      { q: 'Mencari satu kata di dokumen panjang',
        fix: 'Ctrl + F lalu ketik katanya — semua temuan disorot. Mau mengganti massal (mis. "Bapak" jadi "Ibu"): Ctrl + H (Replace) → Replace All.',
        k: ['Ctrl', 'F'], jurus: 'Find / Replace' },
    ],
  },
  {
    cat: 'Excel',
    items: [
      { q: 'Sel berisi ##### bukan angka',
        fix: 'Bukan error — kolomnya kurang lebar untuk angkanya. Klik dua kali garis batas di kepala kolom (mis. antara B dan C) → kolom melebar pas otomatis.',
        jurus: 'Lebarkan kolom' },
      { q: 'VLOOKUP menghasilkan #N/A',
        fix: '#N/A artinya "tidak ketemu" — hampir selalu ejaan kunci tidak sama persis ("Snack" vs "Snak ") atau ada spasi nyasar. Samakan ejaannya dengan daftar; rumusmu kemungkinan besar sudah benar.',
        jurus: 'Cek ejaan kunci' },
      { q: 'Muncul #DIV/0!',
        fix: 'Rumusmu membagi dengan nol atau sel kosong. Periksa sel pembaginya — isi angkanya, atau perbaiki rujukan rumus.',
        jurus: 'Cek pembagi' },
      { q: 'Muncul #VALUE!',
        fix: 'Ada teks ikut dihitung — misal sel berisi "Rp 5.000" yang diketik manual. Isi sel dengan ANGKA POLOS (5000), lalu pakai Format Rupiah untuk tampilannya.',
        jurus: 'Angka polos' },
      { q: 'Muncul #REF!',
        fix: 'Sel yang dirujuk rumus sudah terhapus. Tekan Ctrl + Z untuk membatalkan penghapusan, lalu rapikan rumusnya pelan-pelan.',
        k: ['Ctrl', 'Z'], jurus: 'Undo dulu' },
      { q: 'Rumus tampil sebagai tulisan "=SUM(...)", tidak menghitung',
        fix: 'Dua kemungkinan: format selnya Text (ubah ke General lalu ketik ulang rumusnya), atau mode tampil-rumus aktif tak sengaja — tekan Ctrl + ` (tombol di kiri angka 1) untuk mengembalikan.',
        k: ['Ctrl', '`'], jurus: 'Mode rumus' },
      { q: 'Mengetik 1/2 berubah sendiri jadi tanggal 1-Feb',
        fix: 'Excel menebak itu tanggal. Format selnya ke Text dulu sebelum mengetik, atau awali ketikan dengan tanda kutip satu: \u00271/2.',
        jurus: 'Format Text' },
      { q: 'Angka panjang (NIK/no. HP) berubah jadi 1,23E+11 atau ujungnya jadi 0',
        fix: 'Angka 16 digit harus disimpan sebagai TEKS: format sel Text dulu baru ketik, atau awali dengan kutip satu \u0027. NIK bukan untuk dihitung, jadi aman sebagai teks.',
        jurus: 'NIK = Text' },
      { q: 'Hasil SUM = 0 padahal kolom jelas berisi angka',
        fix: 'Angkanya tersimpan sebagai teks (cirinya rata kiri). Blok angkanya → klik ikon tanda seru kuning yang muncul → Convert to Number — SUM langsung hidup.',
        jurus: 'Convert to Number' },
      { q: 'Habis Sort, data jadi acak — nama dan angkanya tidak sebaris lagi',
        fix: 'Segera Ctrl + Z! Pelajaran emasnya: sebelum Sort, blok SELURUH tabel (atau cukup klik satu sel di dalam tabel), jangan memblok satu kolom saja.',
        k: ['Ctrl', 'Z'], jurus: 'Undo + blok semua' },
      { q: 'Baris judul ikut hilang saat tabel digulir ke bawah',
        fix: 'Bekukan: tab View → Freeze Panes → Freeze Top Row. Baris judul jadi menempel terus di atas seberapa pun kamu menggulir.',
        jurus: 'Freeze Top Row' },
      { q: 'Tabel terpotong saat dicetak',
        fix: 'File → Print → di pengaturan paling bawah pilih Fit Sheet on One Page. Tabel sangat lebar: ganti Orientation ke Landscape di halaman yang sama.',
        jurus: 'Fit One Page' },
    ],
  },
  {
    cat: 'PowerPoint',
    items: [
      { q: 'Mau mulai presentasi dari slide yang sedang dibuka, bukan dari awal',
        fix: 'Tekan Shift + F5 — tayang mulai slide ini. F5 polos selalu mulai dari slide 1.',
        k: ['Shift', 'F5'], jurus: 'Mulai dari sini' },
      { q: 'Saat presentasi, di layarmu malah muncul catatan & slide kecil-kecil',
        fix: 'Itu Presenter View nyasar ke layar yang salah. Saat tayang, klik ⋯ / Display Settings → Swap Presenter View and Slide Show — penonton melihat slide penuh, kamu melihat catatan.',
        jurus: 'Swap display' },
      { q: 'Teks meluber keluar kotak / mengecil sendiri sampai tak terbaca',
        fix: 'Isinya kebanyakan untuk satu slide. Pecah jadi dua slide, atau perbesar kotak teksnya. Ingat jurus M3: maksimal 5–6 butir pendek per slide.',
        jurus: 'Pecah slide' },
      { q: 'Gambar pecah / buram saat ditayangkan',
        fix: 'Gambar kecil dipaksa membesar pasti pecah. Masukkan ulang gambar asli yang ukurannya cukup besar, dan perbesar dari SUDUT supaya tidak gepeng.',
        jurus: 'Gambar asli' },
      { q: 'Slide baru tata letaknya beda sendiri',
        fix: 'Klik kanan slide itu di panel kiri → Layout → pilih tata letak yang sama dengan slide lain (mis. Title and Content). Seragam itu rapi.',
        jurus: 'Samakan Layout' },
      { q: 'Urutan slide salah',
        fix: 'Di panel kecil sebelah kiri: klik slide-nya, tahan, lalu seret ke posisi yang benar. Selesai.',
        jurus: 'Seret di panel' },
      { q: 'Tulisan tidak terbaca — warnanya tenggelam di latar',
        fix: 'Pakai aturan kontras: latar gelap = teks putih, latar terang = teks gelap. Paling aman: pilih tema bawaan dari tab Design dan ikuti warna temanya.',
        jurus: 'Kontras / tema' },
      { q: 'Keluar dari mode presentasi',
        fix: 'Tekan Esc — kembali ke tampilan kerja. (Esc juga jurus keluar dari hampir semua mode layar penuh.)',
        k: ['Esc'], jurus: 'Esc' },
      { q: 'Layar penonton mendadak hitam saat presentasi',
        fix: 'Kemungkinan tombol B tertekan (Black — jeda sengaja). Tekan B lagi untuk kembali; W untuk layar putih. Bukan itu: cek kabel proyektor, lalu Win + P pilih Duplicate.',
        jurus: 'Tombol B / Win+P' },
      { q: 'Nomor slide tidak muncul',
        fix: 'Tab Insert → Slide Number → centang Slide number → Apply to All. Penonton (dan kamu) jadi tahu posisi.',
        jurus: 'Insert Slide Number' },
      { q: 'File terlalu besar untuk dikirim email',
        fix: 'Klik salah satu gambar → tab Picture Format → Compress Pictures → pilih untuk semua gambar. Atau kirim versi PDF (F12 → pilih PDF) — kecil dan rapi untuk dibaca.',
        jurus: 'Compress / PDF' },
      { q: 'Video atau suara di slide tidak berbunyi saat tayang',
        fix: 'Media baru berjalan di mode tayang (F5), bukan di mode kerja. Cek juga volume laptop tidak mute, dan pastikan filenya disisipkan (Insert), bukan sekadar tertaut dari folder lain.',
        jurus: 'Cek mode & volume' },
    ],
  },
]
